### ISSUE TITLE
如何直接获内容的纯文本和html格式的内容

### ISSUE THREAD

**Issue by callmesoul** [hinesboy/mavonEditor#1]
如何直接获内容的纯文本和html格式的内容。
我是做一博客的，列表页想显示部分的纯文本，详情页才显示markdow格式。

文档好像没有这两个接口，这两个接口还是挺需要的，有空加上谢谢

**Comment by hinesboy** [comment]
用v-model绑定的数据源就是纯文本，双向绑定的，可以新增方法主动获取这些数据，谢谢提醒

**Comment by hinesboy** [comment]
我觉得v-model 和 @change 两种实时获取数据的方式已经完全满足开发需求，当文本发生改变时候 ， 绑定的数据实时变动，同时 @change事件也实时回传数据, 已经是做了两种方式，至于主动获取文本反而破坏了MVVM的思想，而且显得有些多余，刚动手准备写的时候，想到了这些。您有什么好的想法，我们可以继续探讨一下（列表展示博客，列表中的多条文本数据 应该不需要从编辑器中获得 ， 而是从数据库等其他数据源获取， 而是在进入详情页时候将某条文本传入编辑器，此时，若文本发生变动，v-model 和 @change都会通知您 ， 您可以做持久化操作等  ， 您也可以主动触发save方法执行回调， 不知我理解的对不对 ， 是否符合您的业务逻辑）

**Comment by callmesoul** [comment]
@hinesboy 对的，我现在就是用@change获取html内容，再通过js去了html标签就是纯文本了，就变成了摘要了。

**Comment by chigagoga** [comment]
> 我觉得v-model 和 @change 两种实时获取数据的方式已经完全满足开发需求，当文本发生改变时候 ， 绑定的数据实时变动，同时 @change事件也实时回传数据, 已经是做了两种方式，至于主动获取文本反而破坏了MVVM的思想，而且显得有些多余，刚动手准备写的时候，想到了这些。您有什么好的想法，我们可以继续探讨一下（列表展示博客，列表中的多条文本数据 应该不需要从编辑器中获得 ， 而是从数据库等其他数据源获取， 而是在进入详情页时候将某条文本传入编辑器，此时，若文本发生变动，v-model 和 @change都会通知您 ， 您可以做持久化操作等 ， 您也可以主动触发save方法执行回调， 不知我理解的对不对 ， 是否符合您的业务逻辑）

这边的需求是这样的 在一个编辑页面使用编辑器去保存文本 但是在另外一个页面纯展示markdown格式的内容 所以想通过方法去获取纯html 但是保存给后端并不是html文本

**Comment by NingerJohn** [comment]
> @hinesboy 对的，我现在就是用@change获取html内容，再通过js去了html标签就是纯文本了，就变成了摘要了。

大佬，你是如何获取到html代码的？好奇编辑完的内容，就是纯文本，如何预览呢？是不是需要再安装一个插件？
