### ISSUE TITLE
怎么样手动设置为 单栏 编辑 |预览 模式?

### ISSUE THREAD

**Issue by gongdf** [hinesboy/mavonEditor#10]
怎么样手动设置为 单栏 编辑 |预览 模式?

**Comment by CHENXCHEN** [comment]
通过ref获得组件实例，然后直接更改组件实例的变量值

**Comment by gongdf** [comment]
就是这里
屏幕分辨率低于768px ，自动取消【单栏 | 双栏】编辑模式 ，更改为【编辑 | 预览】切换 ， 并且取消【沉浸式阅读】模式( > 768px 的眼睛图标为【阅读模式】 , 反之为【编辑 |预览】)
在pc怎么手动设置为低于768px的效果
在mavon-editor.vue里没找到控制这个的变量，请麻烦指点。。

**Comment by hinesboy** [comment]
暂时没有该模式控制参数，随浏览器尺寸变化，你在什么应用场景中需要手动控制？

**Comment by gongdf** [comment]
我现在是想要gitbub上的这个预览功能，不需要全屏预览

**Comment by gongdf** [comment]
![git](https://user-images.githubusercontent.com/18187732/27125700-b3d478b6-5127-11e7-8a4d-d6da69a87eb1.png)

**Comment by hinesboy** [comment]
明白了，我们会考虑如何将预览模式融合进去，现在有单双栏编辑、全屏预览、768px适配，直接加进去有点不合适，要对这些模式做些微调

**Comment by gongdf** [comment]
嗯，O(∩_∩)O谢谢

**Comment by hinesboy** [comment]
@gongdf 已经添加default_open字段 配合 subfield字段可以设置你想要达到的效果，可参考API
