### ISSUE TITLE
Error in callback for watcher "d_value": "Error: Input data should be a String"

### ISSUE THREAD

**Issue by zgj233** [hinesboy/mavonEditor#100]
这是vue捕获的报错
```http
Error in callback for watcher "d_value" : Error: Input data should be a String
```
目前没有发现功能上不能使用，但是这个报错是哪里来的呢？

**Comment by hinesboy** [comment]
v-model 或者 @value绑定的值正确否？

**Comment by zgj233** [comment]
@hinesboy 这个报错不是从我自己的程序里面来的，是从mavonEditor 里面抛出来的， 我 ``` v-model ``` 没有问题, 功能上面也是可以使用的。不知道是哪里的异常了。

**Comment by hinesboy** [comment]
前面有同学提出类似问题，是因为绑定的变量不是string类型，mavon对props：d_value做了类型检查，确定下绑定的变量始终是string类型

**Comment by zgj233** [comment]
@hinesboy  OK， 我有一个地方赋值成null了。
