### ISSUE TITLE
有没有什么办法终止图片的录入，在 imgAdd 执行之后？

### ISSUE THREAD

**Issue by zgj233** [hinesboy/mavonEditor#101]
``` imgAdd ``` 执行后图片就直接被赋值给 ```<input>```
但是如果我这里通过 file.size 判断出图片过大， 想取消对于 ```<input>``` 的赋值该怎么办？
或者可不可以给出一个 imgAddBefore 的勾子， 让我们可以先判断 图片类型、大小， 然后再决定要不要将图片赋值给 ```<input>``` ?

还有个问题，当我调用了
 ```js
self.$refs.editor.$refs.toolbar_left.$imgDelByFilename(pos);
```
图片被删除了， 但是Markdown 里面还是会有 ```![图片](./0)``` 的字样？

**Comment by CHENXCHEN** [comment]
1. `imgAddBefore`钩子不好实现，你可以在添加之后在`imgAdd`里判断，不符合就删去
2. `$imgDelByFilename`仅删除图片，没有处理`markdown`内容

**Comment by zgj233** [comment]
@hinesboy  希望作者能够参考下[vue-core-image-upload](https://github.com/Vanthink-UED/vue-core-image-upload/blob/master/src/vue-core-image-upload.vue) 中，对于大图片上传的处理方式。就是先判断图片的大小， 图片如果超过了用户规定的大小，就直接抛出错误。图片大小合格，再去赋值给```<input>```
```js
if (e.target.files[0].size > this.maxFileSize) {
            var formatSize;
            if (parseInt(this.maxFileSize / 1024 / 1024) > 0) {
                formatSize = (this.maxFileSize / 1024 / 1024).toFixed(2) + 'MB';
            } else if (parseInt(this.maxFileSize / 1024) > 0) {
                formatSize = (this.maxFileSize / 1024).toFixed(2) + 'kB';
            } else {
                formatSize = options.maxFileSize.toFixed(2) + 'Byte';
            }
            console.warn('FILE IS TOO LARGER MAX FILE IS ' + formatSize);
            return this.__dispatch('errorhandle','FILE IS TOO LARGER MAX FILE IS ' + formatSize);
        }
```

**Comment by ImagineZzf** [comment]
我想问一下，图片不符合，通过$imgDelByFilename删除了图片，但是markdown里的内容怎么删除掉？@CHENXCHEN

**Comment by CHENXCHEN** [comment]
@ImagineZzf 您可以通过正则表达式替换处理`md`源代码，将其从`markdown`之内替换掉。

**Comment by CHENXCHEN** [comment]
在下个版本添加一个删除的操作函数

**Comment by CHENXCHEN** [comment]
@ImagineZzf **Version 2.4.16** 完善了 `$imgDelByFilename`，在调用这个函数删除了图片之后，也随之将其从文档中删除了
@zgj233 **Version 2.4.16** 添加了 `image_filter` 函数，详细见 [props文档](https://github.com/hinesboy/mavonEditor#props)
