### ISSUE TITLE
请问,我如何清除掉编辑器里的内容

### ISSUE THREAD

**Issue by Yela528** [hinesboy/mavonEditor#102]
比如,我已经根据 change事件获取到 编辑器里的内容,
提交表单后,由于 我并没有刷新页面,请问该怎么清除掉编辑器里的内容.. 我在其他issue里没找到方法!

**Comment by CHENXCHEN** [comment]
如果你使用v-model绑定了值,直接更改v-model绑定的变量值为空字符就可以

**Comment by Yela528** [comment]
哈哈 十分感谢,已解决!
