### ISSUE TITLE
渲染md的br标签问题

### ISSUE THREAD

**Issue by piumnl** [hinesboy/mavonEditor#104]
我在编辑器里面写了如下两行字，为什么会插入 br 标签呢？md换行语法不是回车吧。
```
一行内容，
之后的内容。
```
结果
```
一行内容，
之后的内容。
```
预期
```
一行内容，之后的内容。
```

**Comment by CHENXCHEN** [comment]
原换行是行末两个空格或两个换行 这种方式太反人类, 被禁用了

**Comment by piumnl** [comment]
我比较习惯两个换行符进行换行，因为我也会在其他诸如 vscode 的工具中写 md 文件，为了统一，我想启用 __两个换行符实现换行__ 的这个功能，有什么办法吗？

_行末加空格换行_ 确实反人类 >_<，特别是对于习惯给工具设置了自动删除行末空格的人来说简直是不给活路！

**Comment by CHENXCHEN** [comment]
哈哈,的确是,设置了自动删除行末空格就曾经让人绝望.
如果你想启用默认的换行,可以通过获取`mavon-editor`的引用实例,假设为`md`,通过以下代码设置
```javascript
md.s_markdown..set({ breaks: true });
```

**Comment by piumnl** [comment]
我自定义了一个组件，组件中 `mavonEditor` 元素通过 `ref` 属性来定位实例，并在组件的 `mounted()` 方法中执行如下
```
this.$refs.md.s_markdown.set({ breaks: true });
```
我发现并没有作用，是我写的方式不对？
