### ISSUE TITLE
应用的github样式与github网站上的markdown样式区别很大

### ISSUE THREAD

**Issue by RoseEnd** [hinesboy/mavonEditor#106]
github上的
![2](https://user-images.githubusercontent.com/19225061/31664949-ea9d35f4-b379-11e7-8e43-8b4ff8e555cf.png)
编辑器的
![z a_s_nf78q 6loypn_ b99](https://user-images.githubusercontent.com/19225061/31664962-f63b35a0-b379-11e7-9fae-380a9382f1a6.png)

**Comment by CHENXCHEN** [comment]
没有启用代码高亮,见[demo](https://hinesboy.github.io/mavonEditor/dist/)

**Comment by RoseEnd** [comment]
你好，代码高亮是有开启的，但是样式不是github的样式

![k z5b t at m g ihhu](https://user-images.githubusercontent.com/19225061/31703938-89a2c74e-b411-11e7-9498-3218bd263de6.png)

**Comment by CHENXCHEN** [comment]
@RoseEnd 试试更改(code_style样式)[https://github.com/hinesboy/mavonEditor#props]

**Comment by RoseEnd** [comment]
你好，设置为hybird的样式或者xcode的样式都可以，就是使用github的不行

**Comment by RoseEnd** [comment]
哦，我看了一下highLight包本身的github样式就是如此，可能是很久之前的了

**Comment by CHENXCHEN** [comment]
是的,`hljs`自带的样式是这样的
