### ISSUE TITLE
/dist/mavon-editor.js 中含有 const 关键字

### ISSUE THREAD

**Issue by dailybird** [hinesboy/mavonEditor#107]
导致大部分安卓手机和较低版本浏览器都无法正常显示页面

**Comment by CHENXCHEN** [comment]
目前可暂时将`dist/mavon-editor.js`中的`const`替换(只有一处),这个是webpack打包的问题,暂时还没找到解决方法

**Comment by dailybird** [comment]
明白，已经这么做了。

希望能在之后的版本中，将打包配置修改一下，比如引入 babel。

感谢作者~

**Comment by CHENXCHEN** [comment]
**v2.4.5**修复了该问题
