### ISSUE TITLE
有无办法在md中使用相对路径图片？

### ISSUE THREAD

**Issue by raaay0608** [hinesboy/mavonEditor#111]
其实问题和mavonEditor本身关系不太大。

前后端分离的CMS系统，例如前端URL `http://localhost:8000`，JSON后端+图片下载在`http://localhost:8001`，图片下载URL为类似`http://localhost:8001/images/123456`这样。

如果使用相对路径在md中使用图片，那么使用`/images/123456`后，浏览器会尝试去前端服务器`http://localhost:8000/images/123456`下载图片，于是404。

因为不能保证固定的IP或域名，暂时还是希望使用相对的图片路径。

所以想请教一下，有无办法解决这个问题？比如前端Server上“代理”从后端Server下载图片，或者前后端使用一个Server？

后端是Express.js搭建而成，如果借助SSR，或者借助nginx能实现功能也可以考虑

**Comment by CHENXCHEN** [comment]
为何不使用绝对路径图片URL呢?
如果不想采用绝对路径
可以尝试在nginx处配置8000端口的location规则
当URL匹配`/image/`前缀时,有两种方法可采用:
1. 内部跳转`rewrite`到`8001端口`
2. 配置`root`路径到图片目录或某脚本(如PHP)
