### ISSUE TITLE
如何在其他地方应用编辑器里的html样式呢

### ISSUE THREAD

**Issue by hh23485** [hinesboy/mavonEditor#113]
我存储了html文本的值，在下次页面渲染的时候，我希望在编辑器以外的地方展示，虽然html标签都还在，但已经没有编辑器里的样式了，请问怎么样添加markdown的样式上去呢。

**Comment by hh23485** [comment]
.markdown-body 解决了

**Comment by blog3zhuge** [comment]
请问你是怎么解决的？markdown-body的样式来源于哪里呢？

**Comment by hh23485** [comment]
@blog3zhuge 过了很久了，我记不太清。我记得是引入mavonEditor时同时引入的，我直接设置了class就可以了

**Comment by CHENXCHEN** [comment]
@blog3zhuge `markdown`, `hljs`, `katex`的样式都提取出来了, 位于`dist/`之下
