### ISSUE TITLE
md转换的html渲染问题

### ISSUE THREAD

**Issue by sunface-io** [hinesboy/mavonEditor#116]
render得到的html完全没有样式，要怎么才能显示出mavonEditor的preview里的样式。

紧急求助，非常感谢

PS:是不是引入mavonEditor/src/lib/css/markdown.css就可以?

**Comment by sunface-io** [comment]
只引用上面的css貌似不够，比如代码段的样式就不对，不能换行

**Comment by hinesboy** [comment]
参考props中的code_style字段，有三种代码高亮样式 默认使用的是code-github

**Comment by sunface-io** [comment]
是不是要引入什么js啊？

**Comment by sunface-io** [comment]
自己写的div中，代码块始终不行
