### ISSUE TITLE
[紧急求助]官网demo中代码片段生成的html在显示时没有任何换行

### ISSUE THREAD

**Issue by sunface-io** [hinesboy/mavonEditor#118]
真心紧急求助，如下图：
这是代码段生成的html
![20d5feec-4478-45d6-9875-5e002ac17ce2](https://user-images.githubusercontent.com/7036754/32315540-71958a38-bfe7-11e7-93c9-ad4a11bc5cb9.png)
这里看得出来，都是span，不会换行，下图可以证明：
![509d868c-38de-44b4-b0f3-cc90c8f2abd9](https://user-images.githubusercontent.com/7036754/32315584-ae1394c8-bfe7-11e7-9d13-3cee3a3eba88.png)

**Comment by sunface-io** [comment]
知道了，编辑器里的html显示和save后的render格式不一样，render带有换行等格式

**Comment by xiejesses** [comment]
能请教下你是如何解决的吗？我通过 `change` 事件和 `save` 事件一样都没有换行标签。
