### ISSUE TITLE
能不能实现多图上传？

### ISSUE THREAD

**Issue by tianshuai** [hinesboy/mavonEditor#120]
多图上传对于编辑需要还是很必要的，如果作者能提供这个接口或功能，那太好了，或者有没有修改插件实现之个功能的？

**Comment by CHENXCHEN** [comment]
`多图上传`是指的 选择多图上传吗？
目前 直接拖是支持多文件的，但多文件选择还不支持。

**Comment by CHENXCHEN** [comment]
`多图上传`是指的 选择多图上传吗？
目前 直接拖是支持多文件的，但多文件选择还不支持。
你指的 提供接口和 功能 需要什么样的 可以详细描述下？

**Comment by CHENXCHEN** [comment]
**Version 2.4.16** 提供了多图上传

**Comment by tianshuai** [comment]
后来才发现支持拖拽功能的
