### ISSUE TITLE
ssr中报错：window is not defined

### ISSUE THREAD

**Issue by liuyueershihao** [hinesboy/mavonEditor#121]
我用 vue 的 ssr 框架 nuxt，用 yarn add mavon-edito 安装后，直接用了一个 editor.vue ，内容直接拷贝官网实例

    <template>
        <div id="editor">
            <mavon-editor style="height: 100%"></mavon-editor>
        </div>
    </template>
    <script>
    // Local Registration
    import { mavonEditor } from 'mavon-editor'
    import 'mavon-editor/dist/css/index.css'
    export default {
        name: 'editor',
        components: {
            mavonEditor
            // or 'mavon-editor': mavonEditor
        }
    }
    </script>
    <style>
    #editor {
        margin: auto;
        width: 80%;
        height: 580px;
    }
    </style>

然后就报 window is not defined 的错误了。
我知道原因是因为 ssr 的问题。但是有什么办法可以解决吗

**Comment by CHENXCHEN** [comment]
配置中对`mavon-editor`禁用`ssr`即可
```javascript
module.exports = {
// ...
  plugins: [{
    src: '~plugins/mavon-editor',
    ssr: false
  }],
// ...
}
```

**Comment by haoxl3** [comment]
楼主请问你是怎么解决的？我加上楼上那段代码还是报错，报document is not defined

**Comment by LimyronChin** [comment]
请问一下，上述配置是在Nuxt环境下忽略MavonEditor的SSR，如果使用原生的服务端渲染，如何配置以达到忽略SSR的目的？

**Comment by zsirfs** [comment]
@CHENXCHEN您说的配置是什么配置啊。只有这个代码。不知道怎么弄啊？
