### ISSUE TITLE
using the awesome mavonEditor in English

### ISSUE THREAD

**Issue by indrajitdan** [hinesboy/mavonEditor#123]
I need one help.  
I am trying to get the toolbar icon hovers in English. Tried with this
`<mavon-editor :language="en" :placeholder="hi"></mavon-editor>`
But it doesnot work.
I am new to vue.. please forgive my ignorance :)

**Comment by indrajitdan** [comment]
I made it to work with :language="'en'"

**Comment by GrayedFox** [comment]
The colon is shorthand for 'v-bind' which is an instruction to tell Vue that the next bit of data is an object (or arrray) - i.e. not a string.

You don't need to add the colon when specifying the language, since it's a string variable, thus:

`language="en"`

Should work just fine
