### ISSUE TITLE
Error - using with nuxt / ssr

### ISSUE THREAD

**Issue by indrajitdan** [hinesboy/mavonEditor#124]
When i am using with nuxt making ssr false, 
`{ src: '~/plugins/mavon-editor', ssr: false }`
it works well when routing from different page.
But it fails - when i reload the page

> The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

How to solve this issue? Thanks in advance :)

**Comment by CHENXCHEN** [comment]
Could you show me a live demo?
I tested and it works well when reloading the page.

**Comment by JustLikeU** [comment]
Hello, I have the same problem. How did you solve it?
