### ISSUE TITLE
点击markdown语法帮助modal框里面的链接，没反应

### ISSUE THREAD

**Issue by irenexixi** [hinesboy/mavonEditor#125]
如图

![image](https://user-images.githubusercontent.com/7159225/32772557-2de59048-c961-11e7-8835-19d97e3b690c.png)

![image](https://user-images.githubusercontent.com/7159225/32772653-7bf3c714-c961-11e7-970f-6477d2c49f99.png)

**Comment by shenanheng** [comment]
求大神解答!!!!!!快来大神啊

**Comment by CHENXCHEN** [comment]
这是一个bug，正在排查。

**Comment by hinesboy** [comment]
已经修复 :)

**Comment by irenexixi** [comment]
@hinesboy 感谢大神
