### ISSUE TITLE
请教一下该如何上传图片

### ISSUE THREAD

**Issue by m92fia** [hinesboy/mavonEditor#126]
上传后的图片，在编辑区显示为 
![图片](./0)

右侧的 html 预览区看到是 <img src=base64....

v-model 绑定的内容只是 markdown 的纯文本，那图片该怎么传怎么引用呢？

最好能提供完整例子，谢谢！

**Comment by CHENXCHEN** [comment]
您指的 “图片该怎么引用” 是什么意思，可以详细描述下问题和期望吗？

**Comment by m92fia** [comment]
我又翻了一下前面的帖子，你看看我理解得对不对:
上传图片需要增加  @imgAdd 方法，在这里捕捉上传的文件，再构建 FormData 上传到服务器上，再拼接一个绝对URL来替换 `![图片](./0)`

是这样操作么？

我本来以为是直接能处理成 base64编码一起随 markdown 上传的，感觉这样或许还更方便

**Comment by CHENXCHEN** [comment]
是的,使用`$vm.$img2Url`仅是将`md`源文件中的内部路径转换为`url`,但不会改变`上传图片`下的引用地址
如果想改变引用 请参考`$vm.$imgUpdateByUrl`
