### ISSUE TITLE
build过后的文件体积过大

### ISSUE THREAD

**Issue by Eamonnzhang** [hinesboy/mavonEditor#13]
看到dist里面的mavon-editor.js有900+kb，在项目里用webpack打包后，基本上占据了js文件的一半。
![image](https://user-images.githubusercontent.com/9126544/27210671-9d7aa80a-5286-11e7-8bf9-9e418c6391d3.png)

**Comment by linguowei** [comment]
我也有这个问题，看了作者的`package.json`文件里面的`dependencies`依赖了好多东西

**Comment by CHENXCHEN** [comment]
用命令安装mavon-editor，`devDependencies`中的包是不会安装的。
主要大头在于highlight.js以及katex的体积，我们正做拆分优化，自动按需加载所需hljs语言文件。。

**Comment by CHENXCHEN** [comment]
@Eamonnzhang @linguowei **2.0.1** 已发布，将hljs高亮文件拆分按需加载，主要体积缩减到418kb，过段时间空了将katex也拆分异步加载，应该能缩减到200+kb.

**Comment by Eamonnzhang** [comment]
@CHENXCHEN  你好，请问在vue-cli搭建的环境中怎么使用2.0以后的版本，按照文档中的步骤配置webpack，编译后，提示 hljs.cpp.js 找不到。

**Comment by CHENXCHEN** [comment]
@Eamonnzhang 可以贴下webpack的配置和运行详情吗？
另，加个配置选项选择是否高亮代码是个好主意。。将在下版改进。

**Comment by CHENXCHEN** [comment]
@Eamonnzhang **2.0.6**版本添加了props: ishljs，可以选择是否高亮代码.

**Comment by DullSky** [comment]
katex并不是必需的，用到的用户群很少，可以去掉

**Comment by CHENXCHEN** [comment]
@DullSky 很不幸，你所说的那部分用户群包括我。:)

**Comment by CHENXCHEN** [comment]
**Version 2.4.7 Release**
