### ISSUE TITLE
通过$vm.$img2Url上传图片，在图片列表部分无同步，无发删除是url的图片

### ISSUE THREAD

**Issue by feicong666** [hinesboy/mavonEditor#130]

**Comment by CHENXCHEN** [comment]
描述不清楚

**Comment by leftstick** [comment]
我也遇到这个问题了，参考文档关于[图片上传](https://github.com/hinesboy/mavonEditor#%E5%9B%BE%E7%89%87%E4%B8%8A%E4%BC%A0)的部分，图片上传完毕以后，需要通过`$vm.$img2Url(pos, url);`修改编辑器里的图片地址，譬如：把编辑器里的`[图片](./1)`，替换成`[图片](真正的url)`。这个部分没有问题。

然后不太正确的地方是`toolbar`里的上传图片按钮，点击之后会有已上传的图片列表，但这个列表里仍然是之前的`./1`，而没有被替换成真正的URL，[源码位置](https://github.com/hinesboy/mavonEditor/blob/master/src/mavon-editor.vue#L418)，实例如下：

![2018-04-08 2 29 56](https://user-images.githubusercontent.com/1059956/38464039-583b0a0e-3b39-11e8-8fa5-b6d2a342d3c0.png)

所以问题就出现了，当点击列表后面的“删除”按钮后，列表里内容没了，但编辑器里的那段代码依旧在，请看


![2018-04-08 2 31 40](https://user-images.githubusercontent.com/1059956/38464052-96541f74-3b39-11e8-952d-7d74c061e080.png)

**Comment by zikuai** [comment]
这个我也遇到了

**Comment by CHENXCHEN** [comment]
参考上传图片的[详情文档](https://github.com/hinesboy/mavonEditor/blob/master/doc/cn/upload-images.md#%E5%9B%BE%E7%89%87%E4%BA%8B%E4%BB%B6)，通过使用`$vm.$refs.toolbar_left.$imgUpdateByFilename`函数可以达成你的要求

**Comment by leftstick** [comment]
@CHENXCHEN  感谢，虽然麻烦了点，但经过你提醒我尝试了下面操作，可以正确处理所有上传图片地址修改后受影响的位置

```javascript
// 替换editor中的'./${pos}'为真实的url
this.$refs.md.$img2Url(pos, oss.fullUrl)

// 从点击“上传”按钮打开的下拉列表里删除 './${pos}' 对应的选项
this.$refs.md.$refs.toolbar_left.$imgDelByFilename(pos)

// 向点击“上传”按钮打开的下拉列表里添加新的图片选项，对应真正的的url，和文件对象
this.$refs.md.$refs.toolbar_left.$imgAddByFilename(oss.fullUrl, file)
```

这样的话，目前来说就能解决如下图演示的问题了：


![issue](https://user-images.githubusercontent.com/1059956/38488528-58538ac4-3c16-11e8-893d-2a8b6a146ad2.gif)
