### ISSUE TITLE
为什么默认就是剧中的?

### ISSUE THREAD

**Issue by borankux** [hinesboy/mavonEditor#131]
![image](https://user-images.githubusercontent.com/19632179/32994361-291c4626-cda1-11e7-8b47-7c91bd3e200f.png)

**Comment by hinesboy** [comment]
默认不居中，检查下是不是你在外层设置了text-align

**Comment by borankux** [comment]
谢谢。虽然没找到父级元素的剧中部分，但是直接在编辑器上靠左成功。nice editor by the way .👍
