### ISSUE TITLE
IE下报错

### ISSUE THREAD

**Issue by HoLoveSalt** [hinesboy/mavonEditor#132]
![image](https://user-images.githubusercontent.com/11827771/33004766-8c2d34f8-cdfd-11e7-8cda-4a0818c61188.png)
![image](https://user-images.githubusercontent.com/11827771/33004770-9230c59a-cdfd-11e7-90a6-949632db8ab4.png)
IE下报错，有个const

**Comment by CHENXCHEN** [comment]
#140

**Comment by CHENXCHEN** [comment]
**v2.4.5**修复了该问题
