### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by RoseEnd** [hinesboy/mavonEditor#133]
bash类型的代码块无法高亮
``` bash
cd laradock
```
看了一下是无法异步加载hljs.bash.js文件

**Comment by wenghaoping** [comment]
加了:ishljs="true",不生效啊,直接http://localhost:8060/js/hljs.cpp.js net::ERR_ABORTED
报错,不是写入就可以直接生效的吗,忧伤啊,

**Comment by CHENXCHEN** [comment]
Version **2.4.0** 已发布，代码高亮抛弃本地继承而使用`cdnjs`外链，`mavon-editor`将自动按需加载对应的语法高亮文件

**Comment by wenghaoping** [comment]
hljs parsing file is missing. mavon-editor will autoload https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js

更新最新的2.4后,用了这个,出现这个问题,代码高亮不起作用

**Comment by CHENXCHEN** [comment]
抱歉, `markdown`的`css`默认使用的`github-markdown-css`, 它的某些样式跟`hljs`冲突了 下个版本修正

**Comment by wenghaoping** [comment]
那我现在咋办,去掉markdown的样式?还是先用别的办法,起码先高亮能用起来吧,老铁?

**Comment by CHENXCHEN** [comment]
现在md高亮和hljs高亮都是可以正常使用的,只是切换`hljs`的配色方案会有问题

**Comment by CHENXCHEN** [comment]
**v2.4.2**修复了样式冲突问题
