### ISSUE TITLE
通过 change 事件获取解析后的 html 没有换行标签，如何解决？

### ISSUE THREAD

**Issue by xiejesses** [hinesboy/mavonEditor#134]
例如：
```
width: 800px;
margin: 0 auto;
```
获取解析后的 html 为：

```<pre class="hljs"><code class="">width: 800px; margin: 0 auto; </code></pre>```

中间缺少换行标签，有试过 `save` 事件，照样不行，请问如何解决。

**Comment by hinesboy** [comment]
html没换行应该没问题的吧，浏览器渲染时候会根据元素类型及css样式来换行，是这个意思吗？
