### ISSUE TITLE
code_style 切换高亮问题，页面刷新后高亮消失， 修改源码中文件也不起作用，小白求指导

### ISSUE THREAD

**Issue by Blackloser** [hinesboy/mavonEditor#135]
代码截图如下
![image](https://user-images.githubusercontent.com/26319882/33158266-711c4f1c-d043-11e7-8891-bf36146bef93.png)
还未刷新页面之前
![image](https://user-images.githubusercontent.com/26319882/33158278-8d54079c-d043-11e7-8858-cc994dca4c18.png)
刷新页面之后
![image](https://user-images.githubusercontent.com/26319882/33158287-9a64b5d0-d043-11e7-851d-cafcf93b7c07.png)
控制台
![image](https://user-images.githubusercontent.com/26319882/33158290-a2d541e4-d043-11e7-9952-0f79214d84d7.png)

**Comment by Blackloser** [comment]
@hinesboy  大神，指导下

**Comment by CHENXCHEN** [comment]
抱歉, `markdown`的`css`默认使用的`github-markdown-css`, 它的某些样式跟`hljs`冲突了 下个版本修正

**Comment by Blackloser** [comment]
好哒  期待下一个版本  thanks

**Comment by CHENXCHEN** [comment]
**v2.4.2** 已发布 修复了样式冲突的问题

**Comment by Blackloser** [comment]
可以出一个releases  这样可以方便看到每个版本的迭代都更新了什么

**Comment by CHENXCHEN** [comment]
可以啊, 现在更新日志位于这里[LOG.md](https://github.com/hinesboy/mavonEditor/blob/master/LOG.md)
