### ISSUE TITLE
设置default_open报错

### ISSUE THREAD

**Issue by bill-mark** [hinesboy/mavonEditor#137]
报错:
vue.esm.js?4d65:574 [Vue warn]: Property or method "preview" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
原始代码:

        <mavon-editor style="height: 100%"
                      :ishljs = "true"
                      :editable="false" 
                      :toolbarsFlag="false" 
                      :subfield="true"
                      :value="mockdata" 
                      :default_open="preview">
        </mavon-editor>

..

**Comment by bill-mark** [comment]
如上

**Comment by bill-mark** [comment]
最新进展:
不能动态设置,这么设置可以  default_open="preview",但是请问我想只展示预览不展示编辑区域怎么弄

**Comment by CHENXCHEN** [comment]
将`subfield`设置为`false`

**Comment by bill-mark** [comment]
可以了 谢谢

**Comment by CHENXCHEN** [comment]
`default_open`是支持动态设置的, 你要确保data定义了`preview`变量, 并且`preview`变量值为`edit`或`preview`, 不可以通过`:default_open`的方式传字符串, 在`vuejs`中, 此处放的是变量 而不是值
