### ISSUE TITLE
高亮文件,公司不让用外链CDN怎么办

### ISSUE THREAD

**Issue by bill-mark** [hinesboy/mavonEditor#138]
请问能发个高亮文件的文件夹吗 让代码去这里面找
具体怎么弄我也不太清楚,求救啊

**Comment by CHENXCHEN** [comment]
暂时你可以参考/使用老版本(**2.3.1**)
在下个版本, 我们会提供一种禁用外链和 指定链接 按需加载的方式.

**Comment by CHENXCHEN** [comment]
**Version 2.4.2 Release** 支持本地按需加载

**Comment by Mrzyang** [comment]
大佬，能发一份教程吗，我公司内网也存在这个问题，https://github.com/hinesboy/mavonEditor/blob/master/doc/cn/no-cnd.md  
中写的方法看得不是很理解，尝试了各种方法没成功，本人从事后端开发，前端不是很了解，麻烦指导一下， 邮箱 846965599@qq.com，感激不尽！
