### ISSUE TITLE
引入后手机只有chrome能访问，其他浏览器都是空白

### ISSUE THREAD

**Issue by Tyrone2333** [hinesboy/mavonEditor#140]
mavon_editor_test.vue : 

`    import {Loading} from 'vux'`
 `   import {mavonEditor} from 'mavon-editor'`
  `  import 'mavon-editor/dist/css/index.css'`
  `  import axios from 'axios'`

只是引入了mavonEditor而已，用`<router-link to="/mavon_editor_test">`跳转，在手机和pc chrome都正常，可以传图片，但在所有其他手机浏览器都白屏。vue-router去掉`import mavon_editor_test`就正常了

**Comment by CHENXCHEN** [comment]
这是因为导出的`dist`中包含`const`的缘故导致

**Comment by CHENXCHEN** [comment]
**v2.4.5**修复了该问题
