### ISSUE TITLE
关于代码高亮问题，一直关注这个

### ISSUE THREAD

**Issue by wenghaoping** [hinesboy/mavonEditor#141]
用的是最新的版本2.4.7，在之前也有同样问题，就是语法不高亮显示，报错

![image](https://user-images.githubusercontent.com/21232705/33249352-0512a404-d365-11e7-8c9f-e6f119d451c5.png)
上一个版本也是这样的错误，原来以为是不是代码里不是最新的，我这已经是新建了一个项目，然后下载这个组件，再映入，还是这个问题，我有点绝望啊。~~~
![image](https://user-images.githubusercontent.com/21232705/33249407-3dee4184-d365-11e7-9178-1d8bb5847e56.png)

**Comment by wenghaoping** [comment]
![image](https://user-images.githubusercontent.com/21232705/33249475-baad9d28-d365-11e7-95c3-2fbc221f331d.png)
高亮的js其实是加载了吧，因为我里面用了elementui和bootstrap，怀疑会不会样式冲突了，才发现，现在里面有些引用的地方会显示红色完全是bootstrap的样式，如果把他们两个都去了，
![image](https://user-images.githubusercontent.com/21232705/33249514-fd016420-d365-11e7-8e99-19743e5d14b3.png)
好像更不对了，感觉，求解。我也是你一更新，我就更新啊

**Comment by CHENXCHEN** [comment]
能建立一个`demo`项目吗?我看看相关引入

**Comment by wenghaoping** [comment]
好的，我马上建好上传

**Comment by wenghaoping** [comment]
https://github.com/wenghaoping/vue-story

样式在main里引入的，main里还有element的样式和bootstrap的样式，组件是在views下的index页面使用，数据来源是我自己的一个地址，里面是md的语法，这是零时写的一个demo，谢谢帮忙看

目前使用在http://www.wenghaoping.com  个人博客里面。

**Comment by CHENXCHEN** [comment]
明白

**Comment by CHENXCHEN** [comment]
@wenghaoping 你的代码md语法不真正.
如下所示
\```c++
int main()
{
    printf("hello world!");
}
\```
```c++
int main()
{
    printf("hello world!");
}
```

**Comment by wenghaoping** [comment]
这，这，这，这特么就尴尬了啊，这太不好意思了啊，我真是，
```language

```

我每次写还都把这个language删掉，我都没意识到，这里要写东西，羞愧，羞愧，谢谢楼主，祝你越来越帅，

**Comment by chf-gh** [comment]
previes 变量要添加单引号，我就栽倒这里了。
这是我的配置：

                          <mavon-editor
                            ref="mavonArea"
                            class="md"
                            :ishljs = "true"
                            :value="item.text?item.text:''"
                            :subfield = "false"
                            :defaultOpen = "'preview'"
                            :toolbarsFlag = "false"
                            :editable="false"
                            :boxShadow="false"
                            :placeholder="'暂无内容'"
                            codeStyle="github"
                            :scrollStyle="false"  ></mavon-editor>
