### ISSUE TITLE
样式引入不进去问题

### ISSUE THREAD

**Issue by mmd0308** [hinesboy/mavonEditor#142]
问题描述:
在markdown编辑页面样式没有问题,当我把render 保存进数据库,在其他页面如下引入内容.
 <div id="content" v-html="form.arContentHtml">
                {{ form.arContentHtml }}
  </div>
import 'mavon-editor/dist/css/index.css' 引入样式,但是样式引入不进去?不能这样吗?还是我引入方式有问题.谢谢解答

**Comment by CHENXCHEN** [comment]
从**v2.4.0**起就将`markdown`的css文件以及`hljs`相关css文件都独立开了,相关文件位于[dist之下](https://github.com/hinesboy/mavonEditor/tree/master/dist)
