### ISSUE TITLE
有没有办法在写的文章里引用项目中别的组件？

### ISSUE THREAD

**Issue by wangxiangyao** [hinesboy/mavonEditor#144]
比如，一篇推荐商品的文章，想在文章中引用商品预览组件（主要想要的功能：用户是否标志喜欢，商品是否为新品，是否为热销，点击商品路由到商品详情页）。

有个思路：
  1.写特定内容的链接
  2.markdown文章被解析后，拿到html
  3.手动替换特定的a标签，等于说动态加载组件

这个思路能行的通么？有没有更好的方法？

**Comment by hinesboy** [comment]
可以自行添加markdown-it的解析规则，具体参考[markdown-it](https://github.com/markdown-it/markdown-it)文档

**Comment by wangxiangyao** [comment]
棒棒哒，你觉得这个功能有没有必要加上去？感觉好像会更灵活一些
