### ISSUE TITLE
兼容性极差

### ISSUE THREAD

**Issue by liyuechun** [hinesboy/mavonEditor#145]
兼容性极差，差评

**Comment by hinesboy** [comment]
PC展示在IE上会有些问题待调整，其他问题望反馈，我们积极修复

**Comment by juchao110** [comment]
火狐浏览器下无法上传图片

**Comment by hinesboy** [comment]
@juchao110 在火狐上图片下拉菜单（v2.4.8后）无法点击，已修复（v2.4.15），其他上传功能在火狐正常

**Comment by juchao110** [comment]
@hinesboy OK，多谢完善

**Comment by juchao110** [comment]
@hinesboy npm install 提示包不存在，是否同步上去了？

**Comment by hinesboy** [comment]
@juchao110 已经发布，gh-pages分支已经成功引入新版本 2.4.15 ,[查看演示网页](https://hinesboy.github.io/mavonEditor/dist/)

**Comment by juchao110** [comment]
@hinesboy 问下 我的mac能install成功但是其他人的Windows一直报错，找不到包
![1](https://user-images.githubusercontent.com/28338109/34331753-8b79a56e-e964-11e7-905e-7211e323b0e3.png)

**Comment by hinesboy** [comment]
@juchao110 
我本地通过npm全局安装试了下，是可以找到2.4.15版本的
![image](https://user-images.githubusercontent.com/26454305/34331887-d7e8d84c-e965-11e7-8433-6ce15f2ed0e2.png)
npm的hub上面也是有2.4.15版本的
![image](https://user-images.githubusercontent.com/26454305/34331889-dbbaf69e-e965-11e7-926b-058738ce73b4.png)
**cnpm确实只能安装2.4.14版本，这个应该是cnpm的问题 没有及时去同步npm的数据**
![image](https://user-images.githubusercontent.com/26454305/34331913-18e326ae-e966-11e7-8632-dd192bada505.png)
yarn 中也能找到2.4.15版本
![image](https://user-images.githubusercontent.com/26454305/34331951-6976785a-e966-11e7-8668-8153188b8ba9.png)
