### ISSUE TITLE
请问有没有办法把html代码重新解析成md源码

### ISSUE THREAD

**Issue by Tyrone2333** [hinesboy/mavonEditor#146]
我把html保存在数据库,想修改内容的时候设置初始值但是显示的是一大坨html,请问有没有办法把html代码重新解析成md源码就像当初编辑的那样?且包含图片

**Comment by hinesboy** [comment]
比较麻烦，我写过to-markdown的解析，结果会根原本有些出入，最好能直接保存md字符串  需要用的时候重新解析

**Comment by Tyrone2333** [comment]
@hinesboy 那么正确的修改文章姿势应该是怎样的?我不可能让我的客户直接操作html吧

**Comment by Tyrone2333** [comment]
关了页面就没md啊,数据库只存了html

**Comment by yasinshaw** [comment]
@Tyrone2333  数据库可以再另外存一个md的字段哇， 你保存的时候可以同时保存md和html内容。

**Comment by hinesboy** [comment]
所以一般做markdown编辑，多数入库是md，而不是html ，如果没有特殊需求，还是保存md吧，无论从大小还是灵活性都较优

**Comment by CHENXCHEN** [comment]
若想编辑,请存md,若想展示,请存html

**Comment by Tyrone2333** [comment]
@hinesboy @CHENXCHEN 我试一下,以前没用过md编辑器,稍后再来反馈
