### ISSUE TITLE
what if i don't want to use katex 

### ISSUE THREAD

**Issue by yuanfux** [hinesboy/mavonEditor#147]
How do I prevent katex from loading ?

**Comment by CHENXCHEN** [comment]
refere to [this](https://github.com/hinesboy/mavonEditor/blob/master/doc/en/no-cnd.md), disable `katex` auto loading.

**Comment by yuanfux** [comment]
I've already set the external_link to false, but i still got errors saying

> external_link.markdown_css is not a function, if you want to disabled this error log, set external_link.markdown_css to function or false

>external_link.katex_css is not a function, if you want to disabled this error log, set external_link.katex_css to function or false

>external_link.katex_js is not a function, if you want to disabled this error log, set external_link.katex_js to function or false

here is my code
`
<mavon-editor :ishljs="false" :external_link="false" ></mavon-editor>
`

and I also tried

`
<mavon-editor :ishljs="false" :external_link="externalLink" ></mavon-editor>
`
`
private externalLink: object = {
        markdown_css: false,
        katex_css: false,
        katex_js: false
      };
`
The errors still popped up.

**Comment by CHENXCHEN** [comment]
sorry about this, if you set `markdown_css`, `katex_css`, `katex_js` to `false`,  `mavon-editor` will not automatic loading thease files.
But it still print errors, this is a bug at [L290](https://github.com/hinesboy/mavonEditor/blob/e56ed538e6424c0dee86d550b7dd37c2b91bf4f3/src/mavon-editor.vue#L290)
You can ignore it in this version(**v2.4.10**), i will fix it in next version.
Thanks for your feedback. 
Have a nice day!

**Comment by CHENXCHEN** [comment]
**v2.4.11** fix it.
