### ISSUE TITLE
从数据库中直接调用文档内容，图片如何直接显示修改或删除

### ISSUE THREAD

**Issue by qm8956** [hinesboy/mavonEditor#148]
我将文档保存到数据库中时，从数据空中直接提取数据，图片是个路径，如何显示并修改呢，还是说我将图片文件直接保存成编码的方式

**Comment by hinesboy** [comment]
@qm8956 最新图片上传文档已经完善，先参考下README.md

**Comment by qm8956** [comment]
谢谢，看到了，刚才忘记说我的场景了，在做一个个人博客功能，别人在看文章时是不能进行编辑的，只能是预览模式，自己的文章是可以重新编辑的，两种模式下图片显示不出来，有一个专门的文件服务器，图片统一存放图片服务器中，重新编辑时，因为没有事件，图片也无法从文件服务器中删除。非常感谢作者，功能真的很强大。之前在简书上写文章，所以想实现一个简书写文章的功能。

**Comment by yasinshaw** [comment]
@qm8956 
1. 你在数据库里设置一个md一个render， 给别人看时查render，自己编辑时查md；
2. 重新编辑没有删除图片时间，你可以写一个函数来比对编辑前和编辑后，如果图片少了，就通知图片服务器删除改图片。
3. 具体做法：查到md后，从中提取出所有的图片url，用正则匹配![title](url)，放到一个数组里；编辑完成后保存md时，再匹配一次。将两次匹配的结果进行比对，如果发现图片被删除了，就通知图片服务器。
