### ISSUE TITLE
希望能单独显示导航栏

### ISSUE THREAD

**Issue by sunface-io** [hinesboy/mavonEditor#149]
Hi 大神们l:
先展示网页给用户的时候，需要隐藏工具栏，但是这样就开启不了导航栏了，如果能给用户展示导航栏那是最好的，因为希望能支持下

**Comment by hinesboy** [comment]
@sunface-io 你可以先主动调用内部事件`$vm.$refs.toolbar_right.$clicks('navigation')` , `$vm`表示编辑器实例，如何获取可以参考**README.md中图片上传部分**.

 如果此类需求较多，会考虑以后版本添加此功能

**Comment by sunface-io** [comment]
好的，谢谢
