### ISSUE TITLE
如何关闭toolbars工具栏的某个那按钮？外部样式覆盖问题

### ISSUE THREAD

**Issue by Panfen** [hinesboy/mavonEditor#150]
1.文档中说的
toolbars： {
    bold: false
}
在组件中应该怎么添加？

2.外部样式覆盖问题， <style scoped>情况下，工具栏右边部分设置width:28%无效，但是
.v-note-wrapper{
   min-height: 406px;
}
有效，

<style> 去掉scoped情况下工具栏右边部分设置width:28%有效，但是最小高度设置失效

**Comment by hinesboy** [comment]
1.  默认所有按键都展示， 如果你不需要所有，就需要重新覆盖 toolbars 对象 
``` javascript
// html
<mavonEditor :toolbars="toolbars"></mavonEditor>

data() {
     return {
       // 需要什么功能 就设置该字段为true
        toolbars： {
            bold: true,
            ...
        }
    };
}

```

2.  关于min-height的设置，我尝试了下，无论有没有scoped都会生效。
由于mavon本身设置了scoped，会导致样式无法渗透到mavon内部子元素，所以出现设置mavon内部元素的width不生效，具体可以参考这里[vue css 作用域](https://vue-loader.vuejs.org/zh-cn/features/scoped-css.html)

**Comment by Panfen** [comment]
感谢您的答复，关于min-height可以试一下代码：(scoped)
.v-note-wrapper{
    min-height: 406px;
}
是有效的

**Comment by hinesboy** [comment]
好的，另一个问题可以尝试下用 刚才的文档中提供的渗透方法 ， 我还没有尝试过 :)
