### ISSUE TITLE
Error in nextTick: "TypeError: Cannot read property '$refs' of undefined"

### ISSUE THREAD

**Issue by daweihe** [hinesboy/mavonEditor#151]
在vue-cli中使用mavonEditor，出现这样的报错，怎么解决？
![image](https://user-images.githubusercontent.com/19821675/33758310-b0329d04-dc38-11e7-9798-da8355bbcab5.png)

**Comment by daweihe** [comment]
另外，如何获取markdown书写内容的html源码，刚学vue不就，文档里提供的几个事件没明白怎么用

**Comment by CHENXCHEN** [comment]
我无法从这个报错获得其它信息, 如果可以请新建个`demo`项目以便于查错
另: `vue-cli`项目参考[gh-pages分支](https://github.com/hinesboy/mavonEditor/tree/gh-pages)

**Comment by daweihe** [comment]
重建个项目又好了

**Comment by SmileAjh** [comment]
打开帮助就会触发这个报错,定位到是源码中这行代码报错@CHENXCHEN 
![15771573441814](https://user-images.githubusercontent.com/18346430/71391392-e29d2a00-263e-11ea-976f-ee9d9cba1a87.png)
`toolbars: {
help:true
        }`
