### ISSUE TITLE
引入 markdownIt 对象失效

### ISSUE THREAD

**Issue by xu-snow** [hinesboy/mavonEditor#156]
### 版本 
2.4.13

###  引入markdownIt用途
使用 markdownIt.render(xxx)  处理字符串输出html,不需要引入mavonEditor 组件

### 问题与解决方式
引入 markdownIt 对象失效: 
```
import { markdownIt } from 'mavon-editor
// markdownIt  显示为undefined
```
之前的版本（2.4.13之前）是可以的，明显是更新版本后发生的Bug,然后我看了下源码，发现`markdown-it` 在源码里引入的方式是通过
 `mixins: [markdown]`  关键字，跟之前的方式就不一样了，不能通过 `markdownIt: mavonEditor.data().s_markdown` 导出了。
我的解决方式是 通过
```
import { mavonEditor } from 'mavon-editor'
const  markdownIt  = mavonEditor.mixins[0].data().s_markdown  // 这个相当于之前的markdownIt 对象了
```
这种做法可正常运行
但是这种方式就很不科学

### 期望
直接导出 markdownIt ，不希望通过 xxx.data().s_markdown 的方式，我现在还想不通为什么要这样导出，作者可以的话能否告诉一下？ 我看之前的/src/index.js 入口文件 就是通过下面方式导出markdown
```
 const markdown = require('./lib/core/markdown');
 const VueMavonEditor = {		 
      markdownIt: markdown,	
      mavonEditor: mavonEditor,
```

**Comment by CHENXCHEN** [comment]
这部分是我和 @hinesboy 讨论之后做出的决定, 这个版本代码是我写的.
1.  **2.4.13** 版本导出的 `markdown-it` 是 `mavon-editor` 实例化之前就已经被实例化,
这是不合理的, 因为我们希望在 `mavon-editor` 实例化的时候才实例化 `markdown-it` ,
所以我们将 `markdown-it` 作为子组件在 `mixins` 引入
2. 这是为了 **3.0.0** 版本作准备, 我们计划在 **3.0.0** 时将 `mavon-editor` 给插件化, 支持`插件自定义`/`菜单自定义`/`语法自定义`/`扩展自定义`等, 而将 `mavon-editor` 给抽离出来非常重要
3. 您若只希望使用 `mavon-editor` 提供的 `markdown-it`, 
您可以
通过实例化 `mavon-editor` 并通过引用获得其下的 `s_markdown` (推荐)
或
将 `mavon-editor/src/lib/mixins/markdown.js` 中的作为子组件加入到您的父组件 `mixins` 中(这种方法并不需要加载 `mavon-editor` 就可以获得一个 `markdown-it` 实例)

**Comment by xu-snow** [comment]
感觉回答
您的两种方式我都试用了，但是都有错误
第一种推荐的方法,我的代码:
``` js
import { mavonEditor } from 'mavon-editor' // 引入mavonEditor 
const _mavonEditor = Vue.extend(mavonEditor) //创建一个类
const markdownIt = (new _mavonEditor({
}))['s_markdown']
// console.log(markdownIt)
```
这种方法得到的`markdownIt` 是可以正常使用的，但是会报错（不影响使用）
![image](https://user-images.githubusercontent.com/16769796/34155334-e580e3ee-e4f3-11e7-9a82-9188fd08fe25.png)

第二种就是直接报错了，因为`mavon-editor/src/lib/mixins/markdown.js` 文件引入很多包，而我没下这些包

上述两种方式我感觉都不是解决问题的方法。我不能理解你的这句话 “因为我们希望在 mavon-editor 实例化的时候才实例化 markdown-it” ，但markdown-it 其实是一个方法，`mavon-editor` 是否实例化不影响markdown-it的使用。如果要配置化的话，是可以通过其他方法修改 markdown-it的配置。

现在我想的合理办法是：就不从你的库里面引入 markdown-it，而是引入自己 markdown-it 的 包，然后自己配置一下。

**Comment by CHENXCHEN** [comment]
抱歉， 可能是我的描述不够清楚，我考虑的是 `vue` 的组件实例挂载之后， 通过组件引用来进行操作，
刚才重新 `review` 了一遍代码，发现如下方式确实可以获取到 `markdown-it`:
```javascript
import { mavonEditor } from 'mavon-editor' // 引入mavonEditor 
const markdownIt = mavonEditor.mixins[0].data().s_markdown;
```
我本意是想于组件挂载时才实例化 `markdown-it`, 结果没有处理正确，在挂载前就实例化了，
这里其实是个 `bug`，可以在实例化之前就获得 `markdown-it` 实例，
不过为了保证兼容性，在 **2.\*.\*** 版本暂不将它独立，
我会更正暴露 `markdown-it` 的方法，在下个版本，可以如 **2.4.13** 之前一样导出 `markdown-it`。

我们希望 每一个 `mavon-editor` 都应该拥有独立的 `markdown-it` 实例，目前暴露的情况会导致
所有通过 `vue` 挂载的 `mavon-editor` 组件都公用了同一个 `markdown-it` 实例，这可能会导致一些问题，
实际上您通过 `mavonEditor.mixins[0].data().s_markdown` 来获得 `markdown-it` 实例也无不可。

更改 `markdown-it` 处理方式的另一个原因：
以下方式导出的 `markdownIt` 与 `mavon-editor` 内部的 `markdown-it` 不是同一个实例
```javascript
 const markdown = require('./lib/core/markdown');
 const VueMavonEditor = {		 
      markdownIt: markdown,	
      mavonEditor: mavonEditor,
```

您完全可以自己引入 **markdown-it** 然后自己配置相关插件，**mavon-editor** 本质上是个
`markdown` 编辑器，不应当对外承担解析器的责任，我们计划在 **3.\*** 版本
将编辑器与解析器部分独立开

感谢您的反馈！
祝您生活愉快！

**Comment by CHENXCHEN** [comment]
**v2.4.14**
