### ISSUE TITLE
图片预览有问题？

### ISSUE THREAD

**Issue by lenve** [hinesboy/mavonEditor#159]
我的图片上传代码是这样的： 

```
        uploadFileRequest("/article/uploadimg", formdata).then(resp=> {
          var json = resp.data;
          if (json.status == 'success') {
           //在这里处理回调问题
            _this.$refs.md.$imgUpdateByUrl(pos, json.msg)
          } else {
            _this.$message({type: json.status, message: json.msg});
          }
        });
```  

这时显示结果是这样的：  

![p1](https://user-images.githubusercontent.com/6023444/34216407-2790bda0-e5e3-11e7-81db-785d2c79ab78.png)

编辑区域的```./0```没有被替换掉，但是可以正常预览，如果我将回调改成下面这样：  

```
        uploadFileRequest("/article/uploadimg", formdata).then(resp=> {
          var json = resp.data;
          if (json.status == 'success') {
            _this.$refs.md.$imgUpdateByUrl(pos, json.msg)
            _this.$refs.md.$img2Url(pos, json.msg)
          } else {
            _this.$message({type: json.status, message: json.msg});
          }
        });
```  

此时就无法预览了，如下：  

![p2](https://user-images.githubusercontent.com/6023444/34216511-863b923a-e5e3-11e7-9575-f2467674c4eb.png)

以上两种情况，图片都是可以正常传到服务器的。被这个问题困住了，不知道其他小伙伴有没有遇到？大神帮忙解答下。我希望编辑区的```./0```能被替换为图片地址，同时又能正常预览

**Comment by hinesboy** [comment]
@lenve 
在这里只需要使用`$img2Url`这个方法就行了，我尝试`@imgAdd`中替换url
> 没有使用`@imgAdd`替换时url时

![5 8b c g rotfk 6 mm6](https://user-images.githubusercontent.com/26454305/34236489-c3ab6dda-e632-11e7-8db2-ece783d96d11.png)

> 使用`@imgAdd`替换markdown源码中url为http图片地址（我随便找的在线图片）

![image](https://user-images.githubusercontent.com/26454305/34236178-1c30a1ac-e631-11e7-98ee-2ec24bd5f13d.png)
![_ wr y79 t8zp y 63pult9](https://user-images.githubusercontent.com/26454305/34236482-bbfb9a9c-e632-11e7-9766-9c0b2a1d2bd5.png)

是没有问题的，你可以先检查下mavon是否最新版`2.4.14`,有问题我们继续沟通:)

**Comment by lenve** [comment]
@hinesboy 
我找到原因了，回调时候返回的图片路径里不能有空格，有空格就会出现我上面说的问题，没空格就正常了。

**Comment by hinesboy** [comment]
@lenve 在服务端可以做一下encode处理

**Comment by lenve** [comment]
@hinesboy 
嗯，已解决

**Comment by zikuai** [comment]
我也遇到了这样的问题

**Comment by songlinsheep** [comment]
对，我也遇到了这个问题。

**Comment by songlinsheep** [comment]
同时，图片url不能包含反斜线
