### ISSUE TITLE
如何使用异步组件来加载 mavonEditor 呢？

### ISSUE THREAD

**Issue by smartymoon** [hinesboy/mavonEditor#16]
根据 vue 的文档，可以通过下面这种方式实现异步加载
````
Vue.component('async-webpack-example', function (resolve) {
  // 这个特殊的 require 语法告诉 webpack
  // 自动将编译后的代码分割成不同的块，
  // 这些块将通过 Ajax 请求自动下载。
  require(['./my-async-component'], resolve)
})
```
这里的 ./my-async-component 是一个 vue 组件。
可是直接 require('mavon-editor') 得到的并不是 vue 组件
这里要如何处理呢？

**Comment by smartymoon** [comment]
![z jk 4agwtx3_h fz jgr1](https://user-images.githubusercontent.com/12489528/27508097-efe282bc-5910-11e7-971b-0f3ef8f7f790.png)
 同屏预览，没有出现，不知是哪里配置的不对

**Comment by CHENXCHEN** [comment]
@smartymoon 如果宽度<768px 同屏预览会改为单屏编辑和单屏预览

**Comment by CHENXCHEN** [comment]
```javascript
var mavonEditor = require('mavon-editor')
Vue.component('mavon-editor', _r.mavonEditor)
```
或
```javascript
var mavonEditor = require('mavon-editor')
Vue.use(mavonEditor)
```
都可行

**Comment by smartymoon** [comment]
谢谢您的回复，我在文档中有看到这两种引入 mavonEditor 组件的方式。
现在的困惑是因为组件体积比较大，所以我想使用 vue 的异步组件来缩小 app.js 的体积。
从而在编辑视图中，ajax 引入组件。
而您回复的两种方式都会直接将组件打包到主文件中。
有没有办法可以运用异步组件来加载 mavonEditor 呢？

**Comment by CHENXCHEN** [comment]
如果你使用的webpack的话，可以参考[code splitting](https://webpack.js.org/guides/code-splitting/)，若想异步加载的话，可以参考[require.ensure](https://webpack.js.org/guides/code-splitting-async/#require-ensure-)来异步加载mavon-editor
