### ISSUE TITLE
编辑完成后的内容展示页面中，如何去掉预览界面的外边框。

### ISSUE THREAD

**Issue by blog3zhuge** [hinesboy/mavonEditor#162]
你好，有一个问题，在API中似乎没有编辑完成后用于展示的方法，现在我用的是去掉编辑部分的预览窗口，但是总是带有编辑器的外边框，请问有没有什么办法或者api可以仅对md文本进行解析，不带有外边框呢？

**Comment by hinesboy** [comment]
@blog3zhuge 目前根据API设置后
![image](https://user-images.githubusercontent.com/26454305/34355413-0a011460-ea70-11e7-9e88-3d4ca538eadb.png)

可以如下展示
![cusg ofwo9 wpg la 0a9 n](https://user-images.githubusercontent.com/26454305/34355390-cb762b2c-ea6f-11e7-82c6-6ecc275ac5cc.png)
如果不需要 固定高度、灰色背景以及边框 暂时可以覆盖对应CSS属性

**Comment by chf-gh** [comment]
请问如何去掉边框回答灰色背景，能不能具体说下如何设置css？

**Comment by cat998** [comment]
> 我也有同样的需求
> 现在是可以去掉边框 但是 滚动条和固定高度请问要怎么覆盖呢
> 我想实现无滚动条 内容随着整个 浏览器滚动
> @CHENXCHEN
> 
> ![23](https://user-images.githubusercontent.com/31931646/35426447-1f0537d8-029e-11e8-9575-67250715050b.png)

你好，请问边框是如何去除的。我通过覆盖没有效果，在源文件修改了好几个也没效果

**Comment by chen-i** [comment]
@cat998 
用/deep/覆盖
![1](https://user-images.githubusercontent.com/37339618/59576482-905cd880-90f2-11e9-86a3-24f44052e983.PNG)
![2](https://user-images.githubusercontent.com/37339618/59576483-918e0580-90f2-11e9-9f17-845827b65633.PNG)
