### ISSUE TITLE
编辑的时候敲下enter键浏览器会打印  enter

### ISSUE THREAD

**Issue by JobWebNie** [hinesboy/mavonEditor#163]
keydown-listen.js 文件中

 case KEY_CODE.ENTER: {
                // enter
                 console.log('enter') // 这个没有去掉
                if ($vm.$refs.toolbar_left.s_img_link_open) {
                    e.preventDefault()
                    $vm.$refs.toolbar_left.$imgLinkAdd();
                }
                break;}

**Comment by hinesboy** [comment]
@JobWebNie 抱歉！下个版本会清除所有console
