### ISSUE TITLE
如何局部注册该组件呢？貌似只能use

### ISSUE THREAD

**Issue by shx1545** [hinesboy/mavonEditor#166]
这个组件占用空间还不小，我不想全局引入，影响首屏加载时间。目前只有一个组件内用到该组件，所以想问下局部注册有没有方案。

**Comment by CHENXCHEN** [comment]
你可以在 `.vue` 文件中使用 `components`

**Comment by CHENXCHEN** [comment]
参考 [更多引入方式](https://github.com/hinesboy/mavonEditor/blob/master/doc/cn/use.md)
