### ISSUE TITLE
关于弹窗问题

### ISSUE THREAD

**Issue by coolfishstudio** [hinesboy/mavonEditor#167]
您好 我想问一下 在点击“添加链接”和“添加链接” 的时候
是在编辑器中输入 `![]()` 和`[]()` 这样子形式的文本
请问我应该如何修改？

**Comment by CHENXCHEN** [comment]
参考 [markdown语法](https://guides.github.com/features/mastering-markdown/)

**Comment by coolfishstudio** [comment]
你好 我的意思是 如何自定义按钮功能 或 点击不出现弹窗
目前 我的使用是去掉了这两个按钮 通过输入 markdown语法 进行编辑的

**Comment by CHENXCHEN** [comment]
如何自定义按钮可以参考 [#103](https://github.com/hinesboy/mavonEditor/issues/103)

**Comment by coolfishstudio** [comment]
谢谢
