### ISSUE TITLE
【vue warn】The client-side rendered virtual DOM tree is not matching server-rendered content. 

### ISSUE THREAD

**Issue by JustLikeU** [hinesboy/mavonEditor#169]
配合nuxt.js使用的时候

展示markdown内容的时候报警告，具体如下

> The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

使用方式如下：
`<mavon-editor
                v-model="detail.content"
                :ishljs="true"
                :editable="false"
                :toolbarsFlag="false"
                :subfield="false"
                default_open="preview"/>`

插件版本：2.4.16

**Comment by CHENXCHEN** [comment]
可以给一个 `demo` 吗？

**Comment by JustLikeU** [comment]
这个问题是ssr造成的，不好意思我也是后来才知道mavonEditor不支持SSR的，我现在用了markdown-it。在 2018年2月2日，15:00，CHENXCHEN <notifications@github.com> 写道：可以给一个 demo 吗？—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by CHENXCHEN** [comment]
如果想使用编辑器的话 可以通过 [这种方式](https://github.com/hinesboy/mavonEditor/issues/121) 对 `mavon-editor` 禁用 `ssr`.
