### ISSUE TITLE
按第一种方式引入之后报错

### ISSUE THREAD

**Issue by jasonlbw** [hinesboy/mavonEditor#17]
![image](https://user-images.githubusercontent.com/5746643/27573229-6b406db4-5b43-11e7-9970-d563a8c19089.png)

**Comment by jasonlbw** [comment]
Uncaught (in promise) Error: Loading chunk 145 failed.(…)，对应的是插件主文件的报错

**Comment by CHENXCHEN** [comment]
应该没有引入hljs高亮文件，参照[webpack配置](https://github.com/hinesboy/mavonEditor#webpack)

**Comment by jasonlbw** [comment]
修改打包配置之后，没有报错，但是无法编辑

**Comment by CHENXCHEN** [comment]
能贴下 console 报错信息？

**Comment by CHENXCHEN** [comment]
打开chrome调试，network板块，查看有没有失败的request

**Comment by jasonlbw** [comment]
![image](https://user-images.githubusercontent.com/5746643/27574373-acd172a0-5b48-11e7-9c25-d3ca80b2523b.png)
没有任何报错，我觉得插件分离之后还是太大了，一共加载了6S

**Comment by CHENXCHEN** [comment]
主体仅有400+kb，语法高亮文件是异步加载的，不该同时加载。。你是如何引入hljs语言高亮文件的？

**Comment by jasonlbw** [comment]
![image](https://user-images.githubusercontent.com/5746643/27574475-1c1884aa-5b49-11e7-8da1-41e346f6dcae.png)

**Comment by jasonlbw** [comment]
个人建议，觉得语法高亮没必要支持那么多东西，太大了

**Comment by CHENXCHEN** [comment]
语法高亮不是所有语言都要用到，所以这里是用到的时候异步加载的，不清楚你刚才是怎么回事。

**Comment by CHENXCHEN** [comment]
能贴下完整的webpack配置？

**Comment by CHENXCHEN** [comment]
重新测试了下～～～按文档配置来，hljs文件的确是用到时候异步加载

**Comment by jasonlbw** [comment]
我的webpack配置除了上边贴出来的部分，其余都是vue-cli生成的配置，我都没动。

**Comment by zhuangZhou** [comment]
出现了同样问题
![image](https://user-images.githubusercontent.com/23468350/27579356-d8b069ce-5b59-11e7-8e45-05671fe33b29.png)

**Comment by CHENXCHEN** [comment]
@zhuangZhou 应该没有引入hljs高亮文件，参照[webpack](https://github.com/hinesboy/mavonEditor#webpack)配置

**Comment by CHENXCHEN** [comment]
@jasonlbw `build/webpack.dev.conf.js` 中的 `HtmlWebpackPlugin`插件配置问题，添加参数`chunks`，改为如下：
```javascript
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html',
      inject: true,
      chunks: ['app'] // 需要引入的chunk入口名
    })
```
同理如果需要`build`，修改`build/webpack.prod.conf.js`

**Comment by zhuangZhou** [comment]
我已经配置了webpack还是报错

**Comment by zhuangZhou** [comment]
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')

var lang = require('highlight.js-async-webpack/src/file.lang.hljs.js');
var _entry= {
    back_end: './src/back-end/index.js', // 原始入口
    vue: ['vue']
};
for (var i = 0; i < lang.length; i++) {
    _entry[lang[i]] = ['mavon-editor/dist/js/' + lang[i] + '.js']
}

function resolve(dir) {
    return path.join(__dirname, '..', dir)
}

module.exports = {
    entry: {
        app: './src/main.js'
    },
    output: {
        path: config.build.assetsRoot,
        filename: '[name].js',
        publicPath: process.env.NODE_ENV === 'production'
            ? config.build.assetsPublicPath
            : config.dev.assetsPublicPath
    },
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias: {
            'vue$': 'vue/dist/vue.esm.js',
            '@': resolve('src')
        }
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: vueLoaderConfig
            },
            {
                test: /\.less$/,
                loader: 'style-loader!css-loader!less-loader'
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                include: [resolve('src'), resolve('test')]
            },
            {
                test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: utils.assetsPath('img/[name].[hash:7].[ext]')
                }
            },
            {
                test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
                }
            }
        ]
    }
}

**Comment by CHENXCHEN** [comment]
@zhuangZhou 没有配置对entry，仔细看下文档，大致改为如下所示:
```javascript
var _entry= {
    app: './src/main.js'
};
for (var i = 0; i < lang.length; i++) {
_entry[lang[i]] = ['mavon-editor/dist/js/' + lang[i] + '.js']
}

module.exports = {
entry:  _entry,
output: {
path: config.build.assetsRoot,
filename: 'js/[name].js',
//...
},
//...
}
```

**Comment by zhuangZhou** [comment]
ok，已经解决

**Comment by zhuangZhou** [comment]
谢谢

**Comment by CHENXCHEN** [comment]
@zhuangZhou  如果你使用vue-cli，需要修改`build/webpack.dev.conf.js` 中的 HtmlWebpackPlugin插件配置，添加参数chunks，改为如下：
```javascript
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html',
      inject: true,
      chunks: ['app'] // 需要引入的chunk入口名
    })
```
同理如果需要build，修改build/webpack.prod.conf.js

**Comment by CHENXCHEN** [comment]
如果使用vue-cli出现问题，或许这个[gh-pages分支](https://github.com/hinesboy/mavonEditor/tree/gh-pages)能帮到你。
