### ISSUE TITLE
Unexpected token < 

### ISSUE THREAD

**Issue by haoxl3** [hinesboy/mavonEditor#170]
when I use this plugin in my a nuxt project, I got a error about "Unexpected token <".  I wrote the configuration exactly as you did, but in nuxt.config.js, I wrote the webpack configuration. 
For example，
```javascript
build: {
    extend(){
        new CopyWebpackPlugin([{
           // as you did
        }])
    }
}
```
And my code highlighting doesn't work. I look forward to your prompt reply. Thank you.

**Comment by CHENXCHEN** [comment]
Are you disable ssr for `mavon-editor`? `mavon-editor` can not work in ssr.

**Comment by haoxl3** [comment]
sure, I want to ```mavon-editor``` work in ssr, Looks like I'll have to find another way.Thank you all the same

**Comment by CHENXCHEN** [comment]
Why don't you use `markdown-it` if you want to parsing `markdown`?
And..`mavon-editor` just an `markdown` editor.

**Comment by CHENXCHEN** [comment]
we use `markdown-it` to parse `markdown`, [referer this](https://github.com/hinesboy/mavonEditor/blob/master/src/lib/mixins/markdown.js).
If you want to use `markdown-it`, replace `markdown-it-katex-external`, `markdown-it-highlightjs-external` with that `markdown-it-katex`, `markdown-it-highlightjs`.

**Comment by CHENXCHEN** [comment]
You can disable `mavonEditor` [this way](https://github.com/hinesboy/mavonEditor/issues/121).
