### ISSUE TITLE
有没有自定义渲染的功能，右侧的预览我想自己渲染

### ISSUE THREAD

**Issue by salamander-mh** [hinesboy/mavonEditor#171]
这个应该不难吧，因为我想加一些自己的标记，所以才会有这个需求

**Comment by CHENXCHEN** [comment]
`md` 解析器用的是 `markdown-it`，你可以取 `markdown-it` 实例并添加自己所需的标记渲染插件
参考[这里](https://github.com/hinesboy/mavonEditor/blob/master/doc/cn/markdown.md)

**Comment by salamander-mh** [comment]
[marked](https://github.com/chjj/marked)这个库也挺好的，更新很活跃，自定义也方便

**Comment by CHENXCHEN** [comment]
当前使用的是 `markdown-it`，在第三版中会开放接口可使用第三方解析器解析 `markdown`
