### ISSUE TITLE
在前台调用仅预览模式时出来的是编辑模式

### ISSUE THREAD

**Issue by luomaochen** [hinesboy/mavonEditor#176]
想要在后台用这个做编辑器 

前台用这个插件直接展示markdown语法（不要编辑栏）  跟着文档设置如下
```
<mavon-editor :default_open="preview" :toolbarsFlag="false" :subfield="false"  v-model="datas.content"
                  ></mavon-editor>
```

出来的是编辑栏   内容都是markdown原语法   而不是渲染后带样式的内容

希望可以更新

#

**Comment by luomaochen** [comment]
而且有个点很奇怪   我这样设置后  出来的是单纯干净的  编辑区域

我把 ：:subfield="false"  这个改成 true  出现双栏  再把 :subfield="true"  改为false  此时出来的是干净的预览区域 （我想要的那个） 
我以为好了   结果一刷新  又变回 纯粹的编辑区域

**Comment by luomaochen** [comment]
为了排除自身问题 重新建了个项目只引入 该组件  出来的结果还是纯粹的编辑模式 望改正！！

![11](https://user-images.githubusercontent.com/31931646/35422200-692f5b52-0282-11e8-86e5-5cb1d9dbedba.png)

**Comment by CHENXCHEN** [comment]
`default_open` 的 `prop`，如果是传递的是字符串请不要使用 `v-bind`，参考[文档](https://cn.vuejs.org/v2/guide/components.html#%E5%AD%97%E9%9D%A2%E9%87%8F%E8%AF%AD%E6%B3%95-vs-%E5%8A%A8%E6%80%81%E8%AF%AD%E6%B3%95)
请参考如下代码(注意 `default_open` 处)：
```javascript
<template>
  <mavon-editor default_open="preview" :toolbarsFlag="false" :subfield="false"></mavon-editor>
</template>

<script>

export default {
  name: 'HelloWorld',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
````

**Comment by luomaochen** [comment]
哇  谢谢解答 真心感谢   ！！！

**Comment by linzea** [comment]
我也遇到这个问题了， 我按照你们的写法还是出不来，说是我的内容为字符串  Error: Input data should be a String
我试着把内容转成对象或者数组都不行，求还愿
<mavon-editor v-model="detail.content" default_open="preview" :toolbarsFlag="false" :subfield="false"></mavon-editor>

**Comment by linzea** [comment]
`
  import {getItem} from '@/api/index'
  import {mavonEditor} from 'mavon-editor'
  import 'mavon-editor/dist/css/index.css'

    export default {
      name: 'News',
      components: { mavonEditor },
        data() {
            return {
              id:null,
              detail:{
                id: null,
                title: null,
                content: null,
                description: null,
                keyWords: null,
                createTime:null,
                froms: null,
                url: null,
                viewCount: null,
              }
            }
        },
      created() {
        this.id = this.$route.params.id;
        this.getDetail()
      },
      methods: {
        getDetail() {
          getItem(this.id).then(response => {
            let {status, message, content} = response.data
            if (status == 200) {
              //this.detail = Object.assign({},content)
              this.detail = content
            } else {
              this.$notify({
                message: $t(message),
                type: 'error',
                duration: 2000
              })
            }
          })
        },
        handleChangeLanguage(changeLanguage) {
          this.listQuery.lang = langKeyValue[changeLanguage]
          this.getDetail()
        }
      }
    }
<mavon-editor v-model="detail.content" default_open="preview" :toolbarsFlag="false" :subfield="false"></mavon-editor>
`

**Comment by linzea** [comment]
`
<mavon-editor
          defaultOpen="preview"
          :toolbarsFlag="false"
          :subfield="false"
          :preview="true"
          v-model="detail.content"/>
`
嗯嗯，这样写是可以独到的，少了一个参数，给各位添麻烦了

**Comment by LeeWiHong** [comment]
> `<mavon-editor defaultOpen="preview" :toolbarsFlag="false" :subfield="false" :preview="true" v-model="detail.content"/>`
> 嗯嗯，这样写是可以独到的，少了一个参数，给各位添麻烦了

不错不错还是得按照你这个参数来做才行，特别要注意得是这个defaultOpen，你看看前面例子中得都是default_open,那样设置都是有问题得
