### ISSUE TITLE
怎么实现部分Markdown语法解析 部分不解析

### ISSUE THREAD

**Issue by commoners** [hinesboy/mavonEditor#18]
怎么实现部分Markdown语法解析 部分不解析 比如我想实现代码块解析 其他的语法都不解析 利用markdown-it实现吗？ 那和mavonEditor交互过程是怎么实现的呢

**Comment by purewyh** [comment]
还有一个问题是 在<768px的情况下 我切换成全屏编辑  还是单屏编辑和单屏预览 没有出现同屏预览

**Comment by CHENXCHEN** [comment]
@purewyh 是这样设计的，在<768px，仅有单屏编辑和单屏显示，不会提供双屏预览

**Comment by CHENXCHEN** [comment]
@purewyh 你可以通过ref引用`mavon-editor`的实例，然后通过更改该实例下的`d_value`值(需要解析的md代码)，并监听`mavon-editor`组件的`chang`事件获得解析后的值

**Comment by purewyh** [comment]
@CHENXCHEN  能不能考虑在下个版本增加 tab键监听呢 因为现在写代码的话缩进很不方便

**Comment by CHENXCHEN** [comment]
@purewyh 监听tab按键，然后转为4个空格插入？

**Comment by purewyh** [comment]
@CHENXCHEN  是的 这样在写代码片段的时候就不用一个一个手敲空格了

**Comment by CHENXCHEN** [comment]
@purewyh 好的，下个版本考虑加上这个功能。

**Comment by hinesboy** [comment]
现在已经支持TAB键缩进
