### ISSUE TITLE
How to resize the image

### ISSUE THREAD

**Issue by vosonwang** [hinesboy/mavonEditor#181]
I want to resize the image, preferably in the editor.
I've thought about some ideas, and I'd like to hear the official voice. Thank you for your hard work.😊

**Comment by CHENXCHEN** [comment]
There is one way: write img tag into `markdown` source code directly.
The markdown source code is as follows:
```markdown
<img src="http://pic29.photophoto.cn/20131204/0034034499213463_b.jpg" alt="test" width="200" height="100">
```
There is another way: use [markdown-it-imsize](https://www.npmjs.com/package/markdown-it-imsize) plugins.
Is it necessary to integrate this plugin in the editor?

**Comment by vosonwang** [comment]
Got it.🙏
