### ISSUE TITLE
请问展示的时候如何设置高度自适应？

### ISSUE THREAD

**Issue by lyttonlee** [hinesboy/mavonEditor#182]
覆盖min-height: 300px;的话，是一个固定高度，当高度超出的时候会出现滚动条，不足的视乎会空白一截，请问该如何设置可以再展示的时候高度也自适应？

**Comment by CHENXCHEN** [comment]
设置行内样式，将 `min-height` 设为 `auto`
```css
min-height: auto;
```

**Comment by hnyer** [comment]
请问怎么设置最大高度。 比如设置最大高度600px ，超过这个大小就显示滚动条。

我找了文档 好像没有看到这个属性

**Comment by Lstmxx** [comment]
> 请问怎么设置最大高度。 比如设置最大高度600px ，超过这个大小就显示滚动条。
> 
> 我找了文档 好像没有看到这个属性

在style里面重写
.v-note-wrapper{
max-height: ;
}
