### ISSUE TITLE
为什么放在elementUI的form表单中，直接提交，变成了string类型？不是html结构

### ISSUE THREAD

**Issue by Chen-WeiZhen** [hinesboy/mavonEditor#184]
![image](https://user-images.githubusercontent.com/18025841/35813547-dc032eca-0ace-11e8-9861-0c8b3a00c4aa.png)

**Comment by hinesboy** [comment]
可以通过@change事件获取html源码

**Comment by Chen-WeiZhen** [comment]
怎么去调用呀，能直白点吗？ @change="function"
`
function( value ){
   this.refs.md.  ????
}
`
如果我有十几个编辑器是不是要写十几个change那？
