### ISSUE TITLE
点击图片上传无效

### ISSUE THREAD

**Issue by yeziZ** [hinesboy/mavonEditor#185]
点击这里并不能触发回调函数。现在只能通过复制粘贴图片进去？
![image](https://user-images.githubusercontent.com/26887147/35894627-a38f7a3c-0bee-11e8-9311-b045172013b2.png)
![image](https://user-images.githubusercontent.com/26887147/35894651-c6237468-0bee-11e8-93db-32521d104378.png)
![image](https://user-images.githubusercontent.com/26887147/35894658-cf6d197a-0bee-11e8-9866-9affb5746878.png)

**Comment by CHENXCHEN** [comment]
以下代码在本地测试是成功的
```javascript
<template>
  <mavon-editor v-model="test" @imgAdd="$imgAdd"></mavon-editor>
</template>

<script>

export default {
  name: 'HelloWorld',
  data () {
    return {
        test: '',
    }
  },
  methods: {
      $imgAdd(pos, $file) {
          console.log(pos, $file);
      }
  }
}
</script>
```

**Comment by HenryYong** [comment]
![image](https://user-images.githubusercontent.com/7967105/35963899-2d66be20-0cf1-11e8-82ed-7c3d31761d77.png)

我也遇到类似问题，但是我发现是隐藏的input的样式有点问题，导致上传图片的下面50%区域点击之后没有触发隐藏的input，点上面50%的区域会弹出图片选择

**Comment by Chen-WeiZhen** [comment]
![image](https://user-images.githubusercontent.com/18025841/36018142-9f185654-0db5-11e8-9cb2-d8495f305eb8.png)
点击图片能上传，但是多次点击箭头所指向的文件，不是url覆盖的
