### ISSUE TITLE
vue文件中定义css无法覆盖

### ISSUE THREAD

**Issue by king19860907** [hinesboy/mavonEditor#187]
我在vue指定的css，发现没有办法覆盖原先的css，请问有什么好的方法可以覆盖原来的css吗

![qq20180214-031706 2x](https://user-images.githubusercontent.com/4150742/36169105-3bc221c8-1136-11e8-8b13-1cf2889358bf.jpg)

**Comment by CHENXCHEN** [comment]
若想覆盖 `css` 样式，请参考 `css` 优先级
