### ISSUE TITLE
Please add support for Font Awesome 5

### ISSUE THREAD

**Issue by isg89** [hinesboy/mavonEditor#188]
Toolbar icons do not show, if you're referencing Font Awesome 5. Even if you use the Version 4 Shim from Font Awesome, it won't work.

https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by kutluhann** [comment]
It should be happen

**Comment by taoes** [comment]
hope so🤒

**Comment by yanyongyu** [comment]
引入了fontawesome 5图标就一个显示不出来:cry:

**Comment by taoes** [comment]
> 引入了fontawesome 5图标就一个显示不出来😢

想用FontAwesome5的的图标，又找不到合适的MarkDown组件，请问你是怎么处理的？

**Comment by taoes** [comment]
Is this bug not fixed, or is there another plan? @hinesboy

**Comment by ygj6** [comment]
I have tested it in v2.10.2 and it works with FontAwesome5. The way to use it is as follows:

```javascript
// 1.Importing Style Sheets
import "@fortawesome/fontawesome-free/css/all.css"

// 2.Configuring the whitelist
xssOptions:{
    whiteList: {
        i: ['class']
    }
}

// 3.Using FontAwesome5
<i class="fas fa-ad"></i>
```
Renderings：
![image](https://user-images.githubusercontent.com/7699524/145947951-e15c7924-4e47-4702-97d7-9dbac1ea4802.png)

**Comment by ygj6** [comment]
This issue is too old, I closed it, there are new questions can open a new issue.
