### ISSUE TITLE
有没有考虑到XSS跨站攻击的问题？

### ISSUE THREAD

**Issue by LimyronChin** [hinesboy/mavonEditor#195]
你好，请问一下：
这个框架有没有考虑到XSS跨站攻击的问题？比如将编辑器用在网站上供任何人使用，使用者写入一段js的引入自己的代码，框架渲染时会自动过滤吗？

**Comment by hinesboy** [comment]
目前采用的markdown-it解析器进行转义，会过滤js，可以到演示地址测试下:)
