### ISSUE TITLE
ie 11下的显示问题

### ISSUE THREAD

**Issue by xiepu1212** [hinesboy/mavonEditor#196]
直接引用的情况下，在Chrome下可以正常显示编辑与展示栏
![2018-03-10_151641](https://user-images.githubusercontent.com/34331649/37239403-0187a14e-2433-11e8-8219-027ff9915323.png)
，ie 11下只能显示标题栏
![2018-03-10_151750](https://user-images.githubusercontent.com/34331649/37239409-2c917144-2433-11e8-918a-d4e5da8cb14d.png)
但是在全屏下有显示正常
![2018-03-10_151834](https://user-images.githubusercontent.com/34331649/37239416-4dde6550-2433-11e8-8237-515848e58091.png)
请问是为什么？？怎么解决

**Comment by xiepu1212** [comment]
还有个问题是Chrome下面图片的图标显示有点奇怪，外面多了一个框

**Comment by lin-xin** [comment]
加上个css 即可 @hinesboy 
```
.v-note-wrapper .v-note-panel {
  min-height: 500px;
}
```

**Comment by Cheney925** [comment]
@lin-xin 我也是这么解决的，请问IE10下按钮都不能点击的问题，你碰到过吗？
