### ISSUE TITLE
建议添加自动生产目录导航功能

### ISSUE THREAD

**Issue by callmesoul** [hinesboy/mavonEditor#2]
参考这个的toc http://miaolz123.github.io/vue-markdown/

**Comment by hinesboy** [comment]
嗯, 这个我也是这样想的 所以我在后续的第二点就提到：支持开启标题导航
一定会有，这两天准备重构一次代码，这个功能到时候肯定会上，谢谢提醒:blush:
希望有啥好的建议继续沟通，也方便我更好的完善编辑器

**Comment by callmesoul** [comment]
@hinesboy 还有个问题就是上传图片问题，这是markdown的一个麻烦点

**Comment by hinesboy** [comment]
嗯 确实，现在github上面此类编辑器基本都是不支持上传，也跟markdown语法有关，我是比较倾向于支持上传，比如[wangEditor]( http://www.wangeditor.com/ )的上传图片，所以后面也可能会支持这一功能

**Comment by callmesoul** [comment]
图片上传还是很有必要的，如果我平时写代码类文章可能不需要，但有时写日常生活啊之类需要配图什么的，难都换个编辑器么，明显不是很理想啊。

**Comment by hinesboy** [comment]
是的 已经把这一点写到后续，站在一个用户角度，确实有必要， 不能偷懒，下周开始，多花时间，多多push

**Comment by hinesboy** [comment]
@callmesoul 导航已经添加

**Comment by hys1440248234** [comment]
导航功能在文章页具体怎么使用呢？
