### ISSUE TITLE
cdnjs文件引入失败

### ISSUE THREAD

**Issue by 1072937748** [hinesboy/mavonEditor#209]
GET https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.9.0/github-markdown.min.css net::ERR_CONNECTION_TIMED_OUT
GET https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.9.0/github-markdown.min.css net::ERR_CONNECTION_TIMED_OUT
GET https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.9.0/github-markdown.min.css net::ERR_CONNECTION_TIMED_OUT
GET https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.8.3/katex.min.js net::ERR_CONNECTION_TIMED_OUT
GET https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js net::ERR_CONNECTION_TIMED_OUT

**Comment by jiaxiang8756** [comment]
我也是这样，我配置了使用本地引入CSS，external_link也是object自定义的css,然而浏览器每次都会有这个错误

**Comment by CHENXCHEN** [comment]
网络问题导致无法访问，可以按照[这里](https://github.com/hinesboy/mavonEditor/blob/master/doc/cn/no-cnd.md#%E6%9C%AC%E5%9C%B0%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD)的说明配置`js`和`css`为本地文件或者外链

**Comment by geesmart** [comment]
externalLink 设置为false ，还是会请求

**Comment by errorcode300** [comment]
赞，本地按需引用相关.css,.js后，好使了。
