### ISSUE TITLE
2.1.3版build后，index.html 里面需要这么多hljs?

### ISSUE THREAD

**Issue by wu38607** [hinesboy/mavonEditor#21]
<script type=text/javascript src=/static/js/hljs.yaml.7bc1918165320b621ceb.js></script>
类似这样的 script 有近200个。

**Comment by CHENXCHEN** [comment]
@wu38607 `HtmlWebpackPlugin`插件配置问题，该插件将chunks全部集成到html页面，添加参数chunks，改为如下：
```javascript
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html',
      inject: true,
      chunks: ['app'] // 需要引入的chunk入口名
    })
```
你使用的是`vue-cli`创建的项目吧？如果还有不解，这个[分支gh-pages](https://github.com/hinesboy/mavonEditor/tree/gh-pages)也许能帮到你

**Comment by wu38607** [comment]
谢谢，问题解决了。使用vue-cli创建项目把 ‘webpack.prod.conf.js’ 文件下的 ‘HtmlWebpackPlugin‘ 加入
`chunks: ['manifest', 'vendor','app']`
