### ISSUE TITLE
ie下不显示请求的内容，也不能编辑

### ISSUE THREAD

**Issue by haogjin** [hinesboy/mavonEditor#217]
请求后台接口显示数据：
`
 <mavon-editor   :editable="false" v-model="articleForm.content"
                            defaultOpen="preview" ref=md    :toolbarsFlag="false" :subfield="false" >
</mavon-editor>
`
谷歌上显示正常，ie下不显示内容。

改为可编辑模式:
` 
<mavon-editor   ref=md     v-model="articleForm.content"
                   @imgAdd="handleImgAdd"  @imgDel="$imgDel" >
</mavon-editor>
`
能显示导航栏，但无法编辑。

在ie上查看其网站 https://hinesboy.github.io/mavonEditor/dist/ 是可以显示的，说明应该兼容ie的，请问应该怎么解决呢？

**Comment by pandy1988** [comment]
有人已经做出了解答
https://github.com/hinesboy/mavonEditor/issues/196#issuecomment-382321468

在线编辑器也同样定义了高度
```css
.item .item-editor {
    height: 500px;
}
```

**Comment by haogjin** [comment]
谢谢，之前没注意到 @pandy1988
