### ISSUE TITLE
关于上传图片清空缓存的问题

### ISSUE THREAD

**Issue by sizzlecar** [hinesboy/mavonEditor#218]
在编辑器里面上传过图片后，鼠标再次悬浮在上传图片的按钮上就会显示出上次一选中图片的相关信息，这个信息的缓存如何清空？尝试过$imgDel()之类的方法。

**Comment by CHENXCHEN** [comment]
图片上传相关事件请参考
[图片事件](https://github.com/hinesboy/mavonEditor/blob/master/doc/cn/upload-images.md#%E5%9B%BE%E7%89%87%E4%BA%8B%E4%BB%B6)
