### ISSUE TITLE
Urls of uploaded Pictures won't be replaced in the toolbar.

### ISSUE THREAD

**Issue by ervinewell** [hinesboy/mavonEditor#222]
vue:  2.5.10
mavon-editor: 2.5.9

As the screenshot below, urls will be replaced in the content, but won't in the toolbar.

![image](https://user-images.githubusercontent.com/11768033/39615513-270eb942-4fa9-11e8-84a8-d2887fcaf28c.png)

**Comment by hinesboy** [comment]
v2.6.0

**Comment by ervinewell** [comment]
Solved,thx!
