### ISSUE TITLE
能不能不通过按保存按钮，获取里面的value和render。而是通过按外部的保存按钮触发插件的保存事件

### ISSUE THREAD

**Issue by wjf9492** [hinesboy/mavonEditor#223]

**Comment by tfh93121** [comment]
如添加ref=md之后 

可以通过this.$refs.md获取实例
其中的this.$refs.md.d_value 就是编辑器中的内容

runder的内容可以console.log(this.$refs.md)找一下，因为之前只用了d_value

能够直接访问其value 那自己写保存事件就好了

**Comment by wjf9492** [comment]
@tfh93121 好的，我刚刚试了一下，可以了 ，谢谢啦😊

**Comment by hinesboy** [comment]
可以直接使用v-modal双向绑定的数据
