### ISSUE TITLE
有序列表不能显示数字？？

### ISSUE THREAD

**Issue by wjf9492** [hinesboy/mavonEditor#226]
![image](https://user-images.githubusercontent.com/24648326/39684436-7fd94d5c-51ee-11e8-8e04-df1aec303f2d.png)

**Comment by wjf9492** [comment]
为什么显示不了呢？？？

**Comment by hinesboy** [comment]
请问你使用的是mavon拿个版本，用的什么浏览器，
已经有两个人反应这种情况，我测试还是正常，希望可以反馈下我继续找下原因

**Comment by wjf9492** [comment]
@hinesboy 
![image](https://user-images.githubusercontent.com/24648326/39687357-ad83147e-5200-11e8-9578-0907569995bb.png)
使用的是最新的版本啊，用npm下载下载的，浏览器是chrom

**Comment by wjf9492** [comment]
@hinesboy 
image
使用的是最新的版本啊，用npm下载的，浏览器是chrome

**Comment by wjf9492** [comment]
@hinesboy
![image](https://user-images.githubusercontent.com/24648326/39687420-f52003e6-5200-11e8-98a9-e622cc176011.png)
使用的是最新的版本啊，用npm下载下载的，浏览器是chrom

**Comment by wjf9492** [comment]
@hinesboy 
![image](https://user-images.githubusercontent.com/24648326/39687438-0b7b3cfa-5201-11e8-8235-6e05967fc244.png)
使用的是最新的版本啊，用npm下载下载的，浏览器是chrome

**Comment by hinesboy** [comment]
你可以把你的文本发给我试下，或者直接在[mavon演示网站](https://hinesboy.github.io/mavonEditor/dist/)输入文本试一下看看是不是可以显示？

**Comment by wjf9492** [comment]
@hinesboy 
![image](https://user-images.githubusercontent.com/24648326/39687944-209dd5b4-5203-11e8-889c-e7fed2720a97.png)
更新了最新的版本了，还是不行。。

**Comment by wjf9492** [comment]
@hinesboy 这个显示有序列表的内容，跟什么有关系啊，是不是我应该要设置什么东西？

**Comment by hinesboy** [comment]
@wjf9492 不需要的，演示网站没问题那应该就是可以的，用的同一个版本，你把文本发给我看下，我在本地试试

**Comment by wjf9492** [comment]
@hinesboy 已发邮箱

**Comment by wjf9492** [comment]
@hinesboy 麻烦看看行不行。

**Comment by hinesboy** [comment]
![image](https://user-images.githubusercontent.com/26454305/39688597-0f8d75a6-5206-11e8-99c5-7bf9fa23a8a2.png)


本地也是可以的，是不是与你项目中的一些其他因素有冲突

**Comment by wjf9492** [comment]
好，那我先看看，我这边的有什么问题先

**Comment by wjf9492** [comment]
@hinesboy 问题找到了，是我在我的重置文件里面设置了这个
![image](https://user-images.githubusercontent.com/24648326/39690260-119410f2-520c-11e8-8ddb-578fb88d3f14.png)
所以把插件默认的样式给改了，所以有序列表的数字显示不出来了。

**Comment by hinesboy** [comment]
好的

**Comment by imfiny** [comment]
我碰到的情况是在我的全局css中给li元素设置了overflow: hidden导致的无法显示序号或图标问题

**Comment by zeemood** [comment]
> 我碰到的情况是在我的全局css中给li元素设置了overflow: hidden导致的无法显示序号或图标问题

全局样式被修改了吧。overflow是滚动条的，和这个没关系。
```css
ol,ul{
  list-style: none;//把这个注释掉
}
```
