### ISSUE TITLE
hightligh.js 相關 js 的路徑

### ISSUE THREAD

**Issue by xralphack** [hinesboy/mavonEditor#23]
mavonEditor 會在我設定 :ishljs="true" 去找需要的 js
請問怎麼修改路徑呢
例如說我在的頁面是 /threads/1
會去這邊 /threads/1/js/hljs.cpp.js 要檔案
但我的檔案位置是在 /js/hljs.cpp.js

應該是絕對路徑的問題，但我不清楚問題來源是哪邊，麻煩了

**Comment by CHENXCHEN** [comment]
请求的hljs.cpp.js应该是绝对路径 即/js/hljs.cpp.js，目前没办法实现手动配置它的路径这点。。

**Comment by xralphack** [comment]
@CHENXCHEN 那請問一下這段源碼在哪個檔案呢，我找不到

**Comment by CHENXCHEN** [comment]
引用路径是`src/mavon-editor.vue` > `src/lib/core/highlight.js` > `highlight.js-async-webpack`
实际上高亮代码文件的异步拆分用到了webpack的require.ensure语法，我将这部分写到了这里[highlight.js-async-webpack](https://github.com/CHENXCHEN/highlight.js-async-webpack)

**Comment by xralphack** [comment]
看起來有點複雜，再找個時間讀一下

不過我還是不太懂，如果說 webpack 已經有把 hljs 全部的 js 都複製到我想要的資料夾
那為什麼其他人不需要指定路徑

**Comment by CHENXCHEN** [comment]
不是不需要指定，而是。。无法指定，只能访问绝对的地址。。。目前我还没找到办法解决这个问题。。

**Comment by xralphack** [comment]
對 webpack 也沒很熟

require.ensure(["./file"], function() {
  require("./file2");
});

或許能 pass 絕對路徑給 dependencies

**Comment by CHENXCHEN** [comment]
[require.ensure](https://webpack.js.org/api/module-methods/#require-ensure)是通过第三个参数chunkname来生成文件名，并依据output.chunkname来保存路径的。

**Comment by OckhamRazor** [comment]
@xralphack 通过重新 执行
`npm run dev`
这个问题消息了，不过偶尔还是会出现这个问题

**Comment by OckhamRazor** [comment]
这确实是个问题，我希望它不要沉下去。很奇怪的事，这是一个概率事件，概率比较大接近90%

**Comment by CHENXCHEN** [comment]
概率事件是指？
hljs的语言文件路径是固定路径，而webpack打包引用也使用的固定路径。。所以hljs的语言文件必须是在web目录的js/下

**Comment by OckhamRazor** [comment]
> 例如說我在的頁面是 /threads/1
會去這邊 /threads/1/js/hljs.cpp.js 要檔案 
但我的檔案位置是在 /js/hljs.cpp.js

如上所描述的一样。
在页面 a/b应用了editor,发起请求hljs.cpp.js的路径是 a/js/hljs.cpp.js.
在c/d页面应用了editor,发起请求hljs.cpp.js的路径是c/js/hljs.cpp.js

我的hljs.cpp.js一直放置在js/下，资源索引不到

**Comment by CHENXCHEN** [comment]
明白了。。我需要进一步测试。。

**Comment by CHENXCHEN** [comment]
Version 2.4.0 已发布，代码高亮抛弃本地继承而使用cdnjs外链，mavon-editor将自动按需加载对应的语法高亮文件
