### ISSUE TITLE
工具栏的图片按钮有点问题

### ISSUE THREAD

**Issue by hua03** [hinesboy/mavonEditor#231]
图片的按钮和其他的按钮不一样。我看了一下代码，发现其他的按钮用的都是button标签，只有这个按钮用的是div。如果把标签改为button就好了。或者将div的type属性去掉。

![image](https://user-images.githubusercontent.com/19561959/39849149-8955abea-543d-11e8-95d0-a7bb575ec19b.png)

**Comment by hinesboy** [comment]
v2.6.3版本已修复
