### ISSUE TITLE
该如何获取html的值？

### ISSUE THREAD

**Issue by warriorBrian** [hinesboy/mavonEditor#233]
我想把编辑器作为博客的markdown编辑器，
但是我不知道如何获取html的值，因为我要放到数据库上。
请说明下，谢谢。

**Comment by warriorBrian** [comment]
我想获取写在markdown上的html内容，因为我要渲染到前台，达到写文章的目的，但是在API文档中我并没有发现该如何获取，请在这里说明下，谢谢 @hinesboy

**Comment by hinesboy** [comment]
@change事件可以获取到 @warriorBrian
