### ISSUE TITLE
$vm is not defined

### ISSUE THREAD

**Issue by youngjuning** [hinesboy/mavonEditor#236]
## 错误现场

![image](https://user-images.githubusercontent.com/13204332/40110156-dc3f0042-5931-11e8-8997-54417e0c1b14.png)

## 报错

![image](https://user-images.githubusercontent.com/13204332/40110127-c8d0dd5a-5931-11e8-9f7d-0004f2af7094.png)

## 临时解决

![image](https://user-images.githubusercontent.com/13204332/40110202-f7d05a36-5931-11e8-9757-7d153275dc36.png)

**Comment by hinesboy** [comment]
这里的$vm指的是mavonEditor的实例化对象
![image](https://user-images.githubusercontent.com/26454305/40173324-091b193e-5a04-11e8-9a8a-4fb77668ffea.png)
