### ISSUE TITLE
目前没有自定义功能键的api？

### ISSUE THREAD

**Issue by fonglezen** [hinesboy/mavonEditor#24]
比如自定义添加插入视频、插入自定义标签的一些需要自定义的一些功能键。

**Comment by hinesboy** [comment]
目前尚无

**Comment by fonglezen** [comment]
@hinesboy 如果我要添加自定义的功能键，有什么好办法推荐？

**Comment by hinesboy** [comment]
可以修改src目录下源码，src/components 下为toolbar的template，修改后重新打包自行引入

**Comment by fonglezen** [comment]
@hinesboy  通过 `document.getElementsByClassName('auto-textarea-block').item(0).append(this.form.vdurl.toString());` 添加内容到框中，和直接在框中输入有区别，正确用js填入内容的方式是怎样的？

`<pre class="auto-textarea-block" style="font-size: 15px; line-height: 1.5;"><br># ·



&lt;iframe frameborder="0" width="640" height="498" src="https://v.qq.com/iframe/player.html?vid=b0309ciwook&amp;tiny=0&amp;auto=0" allowfullscreen&gt;&lt;/iframe&gt;

&lt;iframe frameborder="0" width="640" height="498" src="https://v.qq.com/iframe/player.html?vid=b0309ciwook&amp;tiny=0&amp;auto=0" allowfullscreen&gt;&lt;/iframe&gt;</pre>`

第一个iframe是直接粘贴进去的，可以预览到视频。
第二个iframe是js插入的，不能预览到视频，左边编辑框中也美元显示出来

**Comment by hinesboy** [comment]
auto-textarea-input 是输入框的类选择器，auto-textarea-block是用来辅助输入框自适应高度用的。
[auto-textarea](https://github.com/hinesboy/auto-textarea)
