### ISSUE TITLE
通过markdown解析出来的html中代码块没有效果

### ISSUE THREAD

**Issue by warriorBrian** [hinesboy/mavonEditor#243]
我在使用您开发的markdown编辑器，遇到一个问题，我是这么使用的：
![tim 20180522140804](https://user-images.githubusercontent.com/28696399/40344959-b897803c-5dc9-11e8-8fee-453dd1582702.png)

然后我存到数据库，返回给前台，**前台使用vue的v-html去解析html**

![tim 20180522140348](https://user-images.githubusercontent.com/28696399/40344995-e453be20-5dc9-11e8-8844-24a3b4be3302.png)

**发现代码根本没有高亮，而且连代码块都没有，请问该如何正确使用？急！请回复，谢谢！**

**这是原本的html，没被解析前：**

![tim 20180522140456](https://user-images.githubusercontent.com/28696399/40345042-1bead80a-5dca-11e8-8321-61a6bf1f8ab0.png)

**Comment by warriorBrian** [comment]
麻烦您能否说明下，该如何正确使用。 @hinesboy

**Comment by warriorBrian** [comment]
@hinesboy 您好，那我能问下，这个**编辑器外部使用的话，有固定的class样式么，或者您有固定的详细样式表么，我好方便添加描述。谢谢**

**Comment by hinesboy** [comment]
可以自行引入一些开源的md样式文件，或者按照上述方式在外层加上markdown-body类名，使用mavon内部的样式文件，因为内部样式文件对该类名下有效.

或者你的展示直接使用mavon来完成，避免此类问题。
