### ISSUE TITLE
IE10,IE11鼠标移到工具栏标题和工具栏图片没有响应

### ISSUE THREAD

**Issue by TIANTIANKUTAO** [hinesboy/mavonEditor#246]
![image](https://user-images.githubusercontent.com/13642005/40578315-7b2e8e2e-6144-11e8-9c64-1fa52bdc4003.png)

**Comment by TIANTIANKUTAO** [comment]
@hinesboy

**Comment by hinesboy** [comment]
v2.6.5已修复， 最近更新较慢，见谅 @TIANTIANKUTAO

**Comment by Cheney925** [comment]
更新后IE11可以用了，但是IE10下按钮全部点击无效
