### ISSUE TITLE
你好 我用的nuxt 并且禁用了SSR ,能正常工作 ，但有Vue 警告

### ISSUE THREAD

**Issue by chenyeah** [hinesboy/mavonEditor#247]
![image](https://user-images.githubusercontent.com/22478003/40621228-86d4c7ee-62ce-11e8-9fcd-d5100429c1ed.png)
 这个如何解决呢 还是 直接就用 ```markdown-it``` ,我的目的就想禁掉```SSR```来使用 ```mavonEditor``` 
### ```test.vue```
```vue
<template>
  <div >
    <mavon-editor v-model="value" style="height: 100%"></mavon-editor>
  </div>
</template>
<script>
export default {
  data(){
    return {
      value:""
    }
  }
}
</script>
```
### ``` ~plugins/mavon-editor.js```
```js
import Vue from "vue";
import mavonEditor from "mavon-editor";
import "mavon-editor/dist/css/index.css";

Vue.use(mavonEditor);
```
### nuxt.config.js
```js
plugins: [
    //...
    { src: "~plugins/mavon-editor", ssr: false }
  ],
```

**Comment by hinesboy** [comment]
[# 169](https://github.com/hinesboy/mavonEditor/issues/169)
