### ISSUE TITLE
上传图片后使用$img2Url替换掉URL，工具栏删除图片，$imgDelByFilename不生效

### ISSUE THREAD

**Issue by DyncMark** [hinesboy/mavonEditor#248]
![image](https://user-images.githubusercontent.com/15116881/40704640-426012dc-641b-11e8-8851-fdb9aef0ce53.png)
1、$imgAdd：上传图片并替换url
2、通过工具栏删除图片,$imgDel：删除 `md` 图片文本

**Comment by hinesboy** [comment]
v2.6.4修复
