### ISSUE TITLE
建议暴露一个渲染的全局方法

### ISSUE THREAD

**Issue by sujianqingfeng** [hinesboy/mavonEditor#249]
我知道项目的定位是一个编辑器，但是在一些场景有时候需要编辑器，有时候只需要渲染的功能。
这个时候解决方案，一是使用其他的js进行渲染，二是隐藏编辑器的所有选项，保留预览的功能。
我在想，能不能暴露一个方法，来简化这些操作以及减少js的引入。
thx

**Comment by chenyeah** [comment]
项目里的 ```package.json``` 有个```markdown-it```依赖， 你可以直接引进来进行渲染，不会增加js的引入！

**Comment by sujianqingfeng** [comment]
ok thx

**Comment by xaero7** [comment]
能给个稍完整的实例吗？
