### ISSUE TITLE
文件上传问题

### ISSUE THREAD

**Issue by ljc930611** [hinesboy/mavonEditor#25]
我想问一下：
uploadimg($e){
            // upload files in one request.
            console.log(this.img_file);
            var formdata = new FormData();
            for(var _img in this.img_file){
                formdata.append(_img, this.img_file[_img]);
            }
            axios({
                url: 'http://127.0.0.1/index.php',
                method: 'post',
                data: formdata,
                headers: { 'Content-Type': 'multipart/form-data' },
            }).then((res) => {
                console.log(res);
            })
通过触发这个方法上传的文件怎么替换文本中base64字符串，没办法一一对应上base64的路径

**Comment by ljc930611** [comment]
能通过js动态修改编辑的内容吗

**Comment by CHENXCHEN** [comment]
@ljc930611 通过js正则替换其值

**Comment by CHENXCHEN** [comment]
和[issue#19](https://github.com/hinesboy/mavonEditor/issues/19)相同，传图片完成后，由服务器返回图片url，然后替换源md中的相对url，之后会自动渲染成带url的html页面。

**Comment by ljc930611** [comment]
替换源md中的相对url,这句话怎么理解？，![图片](./0)我知道把./0替换成返回的url可以做显示，但是不知道怎么替换，没有找到一个方法来替换路径

**Comment by CHENXCHEN** [comment]
js正则替换

**Comment by ljc930611** [comment]
能在上传时的imgAdd方法里就能获得改变后的文本value吗，我现在在imgAdd方法里获取不到最新上传的那个图片文本值，在传下一张图片才能获取上一次的![图片] (./0)，如果在提交表单的时候去做统一修改的话虽然是可以修改，但是当用户上传gif图片时，gif转成base64字符串后再输入文字会给用户一种很卡的感觉，gif越大越明显

**Comment by CHENXCHEN** [comment]
1. `imgAdd`获得的是图片相对路径如./0 , ./1等，如果你想获得源md文本值的话，可以使用`v-model`绑定value
2. 事实上无论是何图片都会转换为base64，不然在图片没有上传之前无法做到本地预览，至于你说的卡顿的问题，你可以在`imgAdd`相应时就将图片上传至服务器，根据服务器返回的绝对url来替换对应文本

**Comment by ljc930611** [comment]
我现在用的就是v-model绑定value，但是在imgAdd中获取的value只有没上传时的内容，相当于这个时候value还没改变，所以我替换不了最新的那个url

**Comment by ljc930611** [comment]
感觉好像是imgadd方法在chang方法之前触发，value还没改变的原因，不知道有没有办法能在value改变后再出发imgAdd方法

**Comment by CHENXCHEN** [comment]
感谢提供反馈，测试的确是如此，`change`触发于`imgAdd`之前，最新的**v2.1.4**版本修正了该bug.

**Comment by ljc930611** [comment]
上传已经好了，再问个问题.
上传图片后修改了图片的url后，上传图片按钮下面的./0   ./1等等的那些怎么修改，因为再次点击上传图片下面的./0是不走imgAdd方法的，所以展示的也还是base64字符串无法修改url，或者有办法能禁用该功能吗？

**Comment by ljc930611** [comment]
请问这个会和什么东西冲突吗?设置了subfield属性，有时候还是分屏有时候是同屏

**Comment by CHENXCHEN** [comment]
1. 可以通过ref引用该组件实例，然后调用该组件的`$imgDel`方法即可删掉，我打算在下一个版本提供一个方法更新指向(例如./0 指向某 url)
2. 单屏和双屏的问题。。在元素宽度<768px会自动转换为单屏

**Comment by CHENXCHEN** [comment]
最新版本**v2.1.5**添加了[$imgUpdateByUrl](https://github.com/hinesboy/mavonEditor#methods)方法，可以更改指向(如./0 -> url)

**Comment by ljc930611** [comment]
![image](https://user-images.githubusercontent.com/26054566/28194729-cd0eab18-6878-11e7-9baa-d18796184c69.png)
this.$ref.md.$imgDel方法只是删除了图片对应的路径，但是这个地方还是可以再次选择，再次选择的路径为./0

**Comment by ljc930611** [comment]
然后分屏的那个问题，应该是初始化的问题，vue记住了上一次的分屏状态，但是我的subfield已经设置为true了，请问应该设置什么来进行初始化每次固定使用分屏状态

**Comment by ljc930611** [comment]
分屏那个参数找到了，弄好了

**Comment by CHENXCHEN** [comment]
删除那个的确是，应该使用`$vm.$refs.toolbar_left.$imgDel`这个方法，$vm=组件实例，我更新下文档

**Comment by CHENXCHEN** [comment]
那个函数的确是，原本是没有提供这个方法的，我需要添加另一个函数

**Comment by CHENXCHEN** [comment]
@ljc930611 **2.1.6**已发布，添加了三个可以直接操作图片的函数，你可以通过`$vm.$refs.toolbar_left.$imgDelByFilename`来删除对应图片文件，详情看[这里](https://github.com/hinesboy/mavonEditor#methods)

**Comment by ljc930611** [comment]
我这边问题都解决了，谢谢作者的支持，都升级三个版本了
最后反馈个bug
let result = this.$refs.md.$refs.toolbar_left.$imgUpdateByFilename('./test',$file);
这个一直返回false

**Comment by CHENXCHEN** [comment]
感谢反馈，没有发现你说的`$imgUpdateByFilename`BUG, 反而发现该处的代码的另一个bug。
另，这个函数是用于更新已存在该filename的指向文件，若不存在filename会返回false.
如果想添加的话用`$imgAddByFilename`

**Comment by CHENXCHEN** [comment]
**2.1.7**修正了该代码的另一处bug

**Comment by wmui** [comment]
@ljc930611 你好，请问一下 "上传图片按钮下面的./0 ./1"这个你是如何解决的？，能否提供下思路，感谢！

**Comment by leftstick** [comment]
@wmui  我是这么做的，虽然挫了点：[更新上传图片按钮下的相对路径](https://github.com/hinesboy/mavonEditor/issues/130#issuecomment-379681431)
