### ISSUE TITLE
图片拖拽上传的方法支持

### ISSUE THREAD

**Issue by codingdogs** [hinesboy/mavonEditor#253]
希望可以添加图片拖拽上传的功能，谢谢。

**Comment by hinesboy** [comment]
图片拖拽是支持的，需要拖拽到输入框中，输入框没有内容的时候只有一行大小

**Comment by CXYZJ408** [comment]
额，原来是因为只有一行的啊，我就说怎么在官网的样例上面图片可以随便一拖就能进去，而自己写的却不行，我还以为我哪边配置不对的缘故
