### ISSUE TITLE
很严重的bug火狐下hover工具栏H按钮然后选择列表时就自动关闭了列表，无法选择

### ISSUE THREAD

**Issue by yozojo** [hinesboy/mavonEditor#255]
火狐下上传图片hover图片按钮然后想选择上传方式就自动关闭了列表
很严重的bug火狐下hover工具栏H按钮然后选择列表时就自动关闭了列表

**Comment by yozojo** [comment]
不知是图片那个按钮的列表还有多级标签那 hover的时候想选择下面的列表就自动关闭列表了无法选择

**Comment by yozojo** [comment]
而且列表还无法hover选择不知道是不是层级问题

**Comment by yozojo** [comment]
解决方法是把button替换成div

**Comment by hinesboy** [comment]
谢谢指正，v2.6.5已修复
