### ISSUE TITLE
上传图片后依旧无法删除

### ISSUE THREAD

**Issue by sunhailin-Leo** [hinesboy/mavonEditor#257]
```javascript
imgDel(pos){
      let filename = this.img_file[pos]['name'];
      let res = this.$refs.md.$refs.toolbar_left.$imgDelByFilename(filename);
      console.log(res);
      if(res){
        alert("删除成功!")
        // delete this.img_file[pos];
      }else {
        alert("删除失败!")
      }
},
```

**Comment by sunhailin-Leo** [comment]
res 那里一直是false; filename确认没有问题,版本是2.6.4

**Comment by hinesboy** [comment]
v2.6.5 已修复，上个版本测试不完全，抱歉啊

**Comment by csjiabin** [comment]
我也遇到无法上出问题，而且调用这个$imgDelByFilename还出现死循环 内存溢出，vue.esm.js?efeb:591 [Vue warn]: Error in event handler for "imgDel": "TypeError: Cannot read property 'name' of undefined"

found in

**Comment by csjiabin** [comment]
vue.esm.js?efeb:591 [Vue warn]: Error in event handler for "imgDel": "RangeError: Maximum call stack size exceeded"

found in

**Comment by Mnufs** [comment]
> v2.6.5 已修复，上个版本测试不完全，抱歉啊

请问真的解决了吗？
