### ISSUE TITLE
图片删除遇到的问题

### ISSUE THREAD

**Issue by crayymumu** [hinesboy/mavonEditor#258]
后台进行图片删除成功后，图片地址url失效，无法通过地址栏进行访问，但是依然可以在右侧预览到图片！请问这是因为缓存未清除么？调用 $vm.$refs.toolbar_left.$imgDelByFilename也无法删除图片缓存。

**Comment by 91651** [comment]
(this.$refs.mavon as any).$imgUpdateByUrl(pos, img);
