### ISSUE TITLE
imgAdd事件未触发

### ISSUE THREAD

**Issue by twathit** [hinesboy/mavonEditor#259]
我通过<script>方式引入mavon-editor,
<mavon-editor ref=md @imgAdd="$imgAdd"></mavon-editor>
但是添加图片时没有触发imgAdd
在 https://jsfiddle.net/CHENXCHEN/qf7gLw3a/3/ 上试验了一下，也没触发imgAdd

**Comment by caihongzhiyue** [comment]
你进去吧imgAdd的名字改一下，这里组件中的imgAdd的名字重复了

**Comment by orchid-lyy** [comment]
<img width="1391" alt="wx20180701-093701 2x" src="https://user-images.githubusercontent.com/29852541/42130273-5e143fa2-7d12-11e8-989f-7f89f4c31622.png">我这边出现的也是这个问题，修改了 也不行？  能不能给一个修改的案例，谢谢啦！

**Comment by caihongzhiyue** [comment]
你可以尝试将整个项目下载下来，然后可以在src中mavon-editor.vue的代码，将方法传递的名字进行修改；然后npm run build编译出来就可以用了，只能帮你到这了；
![image](https://user-images.githubusercontent.com/22017127/42199925-a437cab4-7ec3-11e8-9df8-2702a8e2f91a.png)
