### ISSUE TITLE
请教下如何html源码编辑呢？

### ISSUE THREAD

**Issue by lpp288** [hinesboy/mavonEditor#26]
这个html源码只能查看，不能编辑的，如果要插入一段html，就展示不了网页了

**Comment by hinesboy** [comment]
允许通过html进行编辑


![0a9 xso0vdzg2qexgn mw](https://user-images.githubusercontent.com/26454305/28194320-1b79e66c-6876-11e7-82cf-ce18dc53a004.png)

查看html源码的地方是不可以进行编辑的 ， 需要在编辑区域直接添加html代码即可

**Comment by lpp288** [comment]
这个是可以，但对于不会写html的客户，从外部复制一份网页内容，粘贴到左边区域，就无法解析成html了~.~

**Comment by CHENXCHEN** [comment]
md的设计之初就是为了不会写html的用户准备的，只需要懂的md语法就行（md的语法也非常简单），直接复制网页内容到编辑器会把样式标签给去除，单留纯文本。
