### ISSUE TITLE
如何让编辑器支持 sequence 的可视化？

### ISSUE THREAD

**Issue by figoxu** [hinesboy/mavonEditor#262]
如下面的代码

\`\`\`sequence
title:测试流程图

participant 世界 as hello
participant 你好 as world

hello->world:请求
world-->hello:返回

\`\`\`

最终会可视化为
<img width="170" alt="default" src="https://user-images.githubusercontent.com/10055828/41197668-03509e8c-6c99-11e8-96e8-4c1f9de67932.png">

**Comment by figoxu** [comment]
为何无人答复此Issue

**Comment by hinesboy** [comment]
抱歉！暂未支持sequence，如有需要，暂可以通过获取markdown-it对象自行拓展其语法插件 :)
