### ISSUE TITLE
急急急,2.6.4中替换文章图片url后,删除图片一直循环调用，直到崩溃，以及各种问题

### ISSUE THREAD

**Issue by jjjachyty** [hinesboy/mavonEditor#263]
![image](https://user-images.githubusercontent.com/7439418/41358185-701568b8-6f5a-11e8-9d10-02843a4c376e.png)
```
            <mavon-editor @imgAdd="$imgAdd" @imgDel="$imgDel" :toolbars="toolbars" placeholder="总结编写" v-model="aritcle.content" ref=md ></mavon-editor>

        $imgDel(pos){
            console.log("delete",pos)
                    this.$refs.md.$refs.toolbar_left.$imgDelByFilename(pos)

        },
```

**Comment by jjjachyty** [comment]
里面不能调用                     this.$refs.md.$refs.toolbar_left.$imgDelByFilename(pos) 该方法会调用$imgDel 死循环了,那问题来了 怎么删除内容中的图片URL？？？

**Comment by jjjachyty** [comment]
顺便问下
```
            $imgFileAdd($file) {
                this.img_file[0][0] = this.num;
                this.img_file[0][1] = $file;
                **this.img_file.unshift([(this.num + 1), null]);** 
                this.num = this.num + 1;
                this.$emit('imgAdd', this.img_file[1][0], $file);
                this.s_img_dropdown_open = false;
            },
```
**this.img_file.unshift([(this.num + 1), null]);**  //为什么要新增一个替换的URL到数组而不是放到
this.img_file[0][2] 里面 导致后面使用删除的时候，
```
            $imgDel(file) {
                this.markdownIt.image_del(file[0]);
                // 删除所有markdown中的图片
                **let fileReg = file[2] ? file[2] : file[0]**
                let reg = new RegExp(`\\!\\[${file[1]._name}\\]\\(${fileReg}\\)`, "g")
                this.d_value = this.d_value.replace(reg, '');
                this.iRender();
                this.$emit('imgDel', fileReg);
            },
```
**let fileReg = file[2] ? file[2] : file[0]**  这里file[2] 根本就没有值 所以没有删除markdown里面的图片，求解？？？

**Comment by jjjachyty** [comment]
还有  $imgDel(pos){
            console.log("pos----",pos)

            //  let reg = new RegExp(`\\!\\[${this.$refs.md.$refs.toolbar_left.img_file[pos+1][1]._name}\\]\\(${this.$refs.md.$refs.toolbar_left.img_file[pos][2]}\\)`, "g")
            //     console.log("reg----",reg)
            //    this.aritcle.content = this.aritcle.content.replace(reg, '');


        },
删除方法的pos 为撒第一次删除的时候传的是数组坐标0  后面就变成了替换的URl了？？？？ 😺

**Comment by jjjachyty** [comment]
自己修改 并提交 pull request

**Comment by hinesboy** [comment]
感谢你的PR，非常抱歉个人时间原因未能及时修改 :)
