### ISSUE TITLE
我又来了~ 使用中碰到一个问题

### ISSUE THREAD

**Issue by commoners** [hinesboy/mavonEditor#27]
我是把用户编辑好的内容以html格式保存, 然后我直接在编辑器里写html代码 包括一些css样式也会直接保存 展示的时候会造成布局混乱 不知道有没有什么办法能解决掉这个问题?

**Comment by purewyh** [comment]
想到一个方案能解决掉 正则匹配 style 如果有就替换或者删除掉 不知道您有没有更好的方法

**Comment by hinesboy** [comment]
正则去掉样式，或者将html代码createElement后通过javascript去除样式吧（ele.style）
