### ISSUE TITLE
上传图片按钮消失

### ISSUE THREAD

**Issue by sizzlecar** [hinesboy/mavonEditor#273]
1.先上传几张图片，然后关闭编辑器
![image](https://user-images.githubusercontent.com/25930791/41972454-879f8316-7a44-11e8-91ca-46ffb1260a34.png)

2.再次打开编辑器
![image](https://user-images.githubusercontent.com/25930791/41972508-b1f1c89a-7a44-11e8-96a1-43c323de0687.png)
**如图上传图片的按钮就消失了，有可能是什么原因造成的？**

**Comment by hinesboy** [comment]
插件中并没有对该dom做任何限制，经过测试尚未发现此问题，是否确认没有插件外的逻辑或者样式冲突、覆盖？

**Comment by sizzlecar** [comment]
@hinesboy 感谢你的回复，由于时间原因，我用每次打开重新渲染组件解决了这个问题，存在冲突和覆盖的可能性，我确认过之后会给你消息。谢谢！
