### ISSUE TITLE
dom标签属性不支持驼峰法，导致非npm项目无法使用imgAdd等驼峰法事件

### ISSUE THREAD

**Issue by Ablegang** [hinesboy/mavonEditor#280]
我的实践场景是这样的：

在一个bootstrap页面中，单独引入了mavonEditor，我将mavonEditor的dist下的代码拷贝到本地，再在本地页面通过script引入vue，使用Vue.use和Vue.component来注册mavon，最后new Vue。

```
<div id="app">
       <mavon-editor v-model="markdown" :ishljs="true" @imgAdd="$imgAdd" ref="md"></mavon-editor>
       <input type="hidden" :value="markdown" name="content">
</div>
```

上面是我的html代码，因为dom标签的属性不区分大小写，导致mavon虽然发起了imgAdd事件，我却无法接收并执行回调。

所以，我建议将事件都改为小写。

**Comment by hinesboy** [comment]
v2.6.15版本暂时对所有事件做了兼容， 可以使用 xxx_xxx替代xxxXxx
