### ISSUE TITLE
No icons showed when using

### ISSUE THREAD

**Issue by theJpay** [hinesboy/mavonEditor#281]
Everything is siad in the title, I can figure out why I don't have any icon on the tool bar of the editor, while when I'm hovering it shows the tips.

Hope you can help, and btw that's an amazing job you've done !

**Comment by hinesboy** [comment]
you should import css file
```
import 'mavon-editor/dist/css/index.css'
```

**Comment by theJpay** [comment]
Wow i'm stupid. Thank you very much for your quick answer !
