### ISSUE TITLE
XSS防护需要更加完善

### ISSUE THREAD

**Issue by seymoe** [hinesboy/mavonEditor#285]
编辑器中输入`<script>alert(/xss/)</script>`的确已经过滤了，但是如果输入
`<img src="#" onerror="alert(/xss/)" />`就会出现问题。

**Comment by medz** [comment]
纯前端过滤没必要！后端不是吃干饭的～

**Comment by NateScarlet** [comment]
@medz 那默认设置就不应该启用html了 得确认后端有过滤再打开

**Comment by itDjango** [comment]
这个问题有解决的吗？ self-xss
