### ISSUE TITLE
Vue-cli打包后出现问题

### ISSUE THREAD

**Issue by zhuangZhou** [hinesboy/mavonEditor#29]
![1](https://user-images.githubusercontent.com/23468350/28300314-5c910cdc-6bb1-11e7-854c-c7b7a02794a9.png)

**Comment by CHENXCHEN** [comment]
你使用的是vue-cli，这个分支[gh-pages](https://github.com/hinesboy/mavonEditor/tree/gh-pages)可以帮到你
另：**极度不建议新手使用vue-cli的创建样例**
