### ISSUE TITLE
求教，能否修改预览栏的背景颜色，想改成半透明，但是覆盖backgroud-color样式不生效

### ISSUE THREAD

**Issue by wl-avalon** [hinesboy/mavonEditor#295]
求教，能否修改预览栏的背景颜色，想改成半透明，但是覆盖backgroud-color样式不生效
    #editor {
          margin: 100px auto;
          width: 80%;
          height: 580px;
          background-color: rgb(0, 0, 0, 0.5)!important;
    }
    `<div id="editor">
    <mavon-editor class='mavon' style="height: 100%" @save="$save" @imgAdd="$imgAdd" ref=md v-bind='props'></mavon-editor>
    </div>`

**Comment by wl-avalon** [comment]
找到一个办法，直接去node_modules/mavon-editor/dist/mavon-editor.js里改样式，搜索.v-note-wrapper .v-note-panel .v-note-show .v-show-content,\n.v-note-wrapper .v-note-panel .v-note-show .v-show-content-html，改background就行

**Comment by hongfs** [comment]
```vue
<mavon-editor id="editor" />

<style lang="scss">
    #editor {
        .v-show-content {
            background-color: #000;
        }
    }
</style>
```
