### ISSUE TITLE
admin.js:1153 [Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by gouchangxing** [hinesboy/mavonEditor#3]
### 按照正常的引入1.5.4
//方法一
    // import with ES6
    import Vue from 'vue'
    import mavonEditor from 'mavon-editor'
    import 'mavon-editor/dist/css/index.css'
    // use
    Vue.use(mavonEditor)

### 并在页面中注册了组件
components: {
            mavonEditor
       }
### 在html中引入:
mavonEditor v-model="value"
但是还是报了标题这个错误，请作者帮助解答一下，万分感谢。

**Comment by CHENXCHEN** [comment]
@gouchangxing 
请加上大括号
`import {mavonEditor} from 'mavon-editor'`

**Comment by CHENXCHEN** [comment]
1. Vue.use是全局注册，在此处注册了之后局部无需再注册
2. 如果想局部注册的话，请按照方法二引入

**Comment by gouchangxing** [comment]
非常感谢，还是对vue不够熟悉。问题已经解决啦！再一次，谢谢

**Comment by SingleMY** [comment]
非常感谢，还是对vue不够熟悉。问题已经解决啦！谢谢

**Comment by Reeed7514** [comment]
想问下使用setup的情况下应该怎么局部注册呢？

**Comment by yukaige** [comment]
在使用 <script setup> 的单文件组件中，导入的组件可以直接在模板中使用，无需注册.--来自[vue官网](https://cn.vuejs.org/guide/components/registration.html#local-registration)
