### ISSUE TITLE
图片上传后，v-model绑定的的图片点位替换不了

### ISSUE THREAD

**Issue by QinFeiFei** [hinesboy/mavonEditor#30]
![tim 20170718184147](https://user-images.githubusercontent.com/19926579/28313333-1a7e6b4a-6be9-11e7-97a8-c3a944bbe5d1.png)
![tim 20170718184207](https://user-images.githubusercontent.com/19926579/28313360-2cfac49e-6be9-11e7-88a5-f2ee5949542a.png)

**Comment by CHENXCHEN** [comment]
不清楚你提的问题，你指的是`$imgUpdateByUrl`这个函数没有替换对应图片么？

**Comment by shijunti19** [comment]
@CHENXCHEN 应该是md的代码不替换图片
![图片](./0)
然后如果内容保存了，我要重新编辑，你是怎么设计图片这部分代码的，我原始数据是传md代码呢（传这个图片就没了），还是html渲染后的代码呢

**Comment by QinFeiFei** [comment]
markdown 中的 ./0 图片点位符没替换

**Comment by CHENXCHEN** [comment]
这个方法仅是将 `./0` 解析为 对应`url`

**Comment by CHENXCHEN** [comment]
@QinFeiFei  **2.1.11**版本已发布，新增了`$vm.$img2Url`和`$vm.$imglst2Url`可以做替换操作

**Comment by shijunti19** [comment]
好支持

**Comment by CHENXCHEN** [comment]
@shijunti19 **2.1.11**中input处有个拖动的bug，在**2.1.12**中修复了
