### ISSUE TITLE
关于Tab代码缩进

### ISSUE THREAD

**Issue by jinkun2014** [hinesboy/mavonEditor#307]
您好
关于Tab代码缩进的长度是不是太大了
目前效果：

![qq 20180820152222](https://user-images.githubusercontent.com/11567175/44325984-e0e0b680-a48c-11e8-9ef8-f5b1ef92b893.png)

目前一个Tab有8个字符的长度，代码看起来怪怪的

期望效果：
![qq 20180820152415](https://user-images.githubusercontent.com/11567175/44326113-37e68b80-a48d-11e8-90e0-6cf3a2fa9592.png)

不知道是不是我的使用方式有问题。

**Comment by tangniyuqi** [comment]
我也遇到这个问题，一般4个字符长度比较好

**Comment by Apigflying** [comment]
我也遇到这个问题,有源码改进方案吗

**Comment by yiwuxing** [comment]
请问你们解决这个问题了吗？我也遇到了这个问题
