### ISSUE TITLE
想了解整个保存流程

### ISSUE THREAD

**Issue by shijunti19** [hinesboy/mavonEditor#31]
编辑前：
主要是图片替换和获取内容
1.我上传图片
然后用$vm.$imgUpdateByUrl替换网址
然后我要立即保存内容
你会发现因为上传图片是异步的，change获取的渲染内容里是没替换图片的（就是说这个内容毫无用处，除非你在编辑下内容）
2.必须点文字，点空白地方根本不能编辑（要光标默认到文末）
3.我展示这个内容的话，我得保存图片列表this.img_file，然后用php去替换md源代码里的图片部分是吧，好麻烦
4.上传图片file的name是./0，服务器接受会变成_/0，用./0作为键名总归不合适，有点
 建议：增加一个提交是获取编辑器内容的方法，chang有图片异步问题，还要替换md里图片代码

重新编辑，就是我要编辑我保存的文档
1.md源代码我保存了，但是图片因为机制没替换，这时候图片没了
按你的逻辑我推测应该要增加一个this.img_file，把保存的图片列表页赋值进去。然后关键是，还得把this.img_file插入的到编辑器里，你只有$vm.$refs.toolbar_left.$imgAddByFilename（这个是文件吧）
总之，重新编辑逻辑根本没有，你没法重新编辑内容

$vm.$refs.toolbar_left.$imgAddByFilename
这个怎么获取的
console.log(this.$refs.toolbar_left)=》undefined
 console.log(this.$refs.mavonEditor.toolbar_left)=》undefined
得this.$refs.mavonEditor.$refs.toolbar_left.这个说明最好改改

建议：1.图片就直接把md源代码里的替换了（最好有可选项，因为我也可以不替换）
`例如github的：![2](https://user-images.githubusercontent.com/5392211/28344083-fc72f416-6c53-11e7-89da-f88ca1cdb94a.jpg)`
2.增加$vm.$refs.toolbar_left.$imgAddByFilename这个类似的url方法，可以插入URL、图片列表

我可能推测的不对，那应该说下这个编辑器是如何保存和重新编辑器的，目前我无法使用

**Comment by CHENXCHEN** [comment]
编辑前：
1. 上传图片后，接收由服务器返回的图片路径，使用`$imgUpdateByUrl`替换网址，上传图片这个过程虽然是异步，但是在请求过后接收信息有个回调函数，在回调函数内执行。
2. 如果编辑器没有获得焦点，是不会响应输入内容的，就如同你打开了多个窗口，在某个窗口输入不会在另一个窗口响应一样，另，按键监控的是编辑器的响应事件而不是全局，如果监听全局，将会导致有多个编辑器时都会响应。
3. 同1一样，由服务端返回url，在js端通过正则表达式替换
4. 虽然服务器接收会变成_/0，但是这个名字你完全可以在服务端自定义

**Comment by shijunti19** [comment]
@CHENXCHEN 
1.是回调里啊
` <mavon-editor ref="mavonEditor" v-model="data.content.content" @change="editorValue" style="height: 100%" @imgAdd="imgAdd" @imgDel="imgDel"></mavon-editor>`
![image](https://user-images.githubusercontent.com/5392211/28402926-f2bcb3ce-6d54-11e7-8f0c-78b877dc68f4.png)
![image](https://user-images.githubusercontent.com/5392211/28402954-1194ffa4-6d55-11e7-97ff-fd2bb93e2f88.png)
你看图片上传了，回调里处理的，然后editorValue输出的就是没替换的，你必须重新去编辑下内容才行。
如果遇到只传图片的内容，我是不会去编辑的，这时候是不替换的！
2.
![image](https://user-images.githubusercontent.com/5392211/28402800-507a5a08-6d54-11e7-982a-844498d88b42.png)红色框这部分点击是没反应，这个影响不大，只是操作的时候难受点而已，必须点所在行
3.这些操作不是应该你集成在里面吗？我觉得不应该由我们操作啊，

> ![图片](./0)，我们自己去替换成图片是吗例如换成![0](https://user-images.githubusercontent.com/5392211/28344083-fc72f416-6c53-11e7-89da-f88ca1cdb94a.jpg)

**Comment by CHENXCHEN** [comment]
1. 你使用newKey来替换对应的url？你的newKey并不是原始的key，如（./0），而`$imgUpdateByUrl`该方法替换的是已存在的key指向对应url，若对应key(一般是默认生成的key如./0或通过`$imgAddByFilename`添加的key)不存在则不会进行操作
2. 这里。。下个版本优化下
3. 这里并没有直接替换，而是将 ./0 解析为 指定url

**Comment by shijunti19** [comment]
@CHENXCHEN 不是，newKey你看呢，是为了解决说的第4点啊，./传到服务器会解析成_/我要解析回来替换啊
我自己弄个思路去设计保存吧！就是比较麻烦！按理应该是插件一步完成的

**Comment by CHENXCHEN** [comment]
@shijunti19 服务器应该返回的是图片的绝对路径吧？

比如我有一张图片 在本地是 (./0) 上传到服务器之后，我将该文件命名为 `xxx.png` 并将其保存在了某个目录之下，之后我构造一个可以访问到这个图片的链接如`http://path/to/png/xxx.png`，将该内容返回之后，通过`$imgUpdateByUrl`方法将`./0` 所解析的内容渲染为 `http://path/to/png/xxx.png`

**Comment by CHENXCHEN** [comment]
这么使用：`$imgUpdateByUrl('./0', 'http://path/to/png/xxx.png')`，而你服务器为什么会返回一个带`_/xxx`的内容你又将它改为`./xxx`?

**Comment by shijunti19** [comment]
@CHENXCHEN 对的，所以我只是想问问你，可不可以自己定义./0的格式，例如我换成pic_0,pic_1就不存在这个问题了

**Comment by CHENXCHEN** [comment]
自定义`./0`的格式？你的意思是说自定义在md文档中显示的图片文件名吗？
我提供了一个函数`$imgAddByFilename`就是用于这个地方的，在接收到`imgAdd`事件响应之时，你会获得编辑器内部自定义的图片文件名如(./0)和一个File，你可以使用`$imgDelByFilename`删除这个文件，然后通过`$imgAddByFilename`添加一个文件，这里你可以自定义文件名(./xxx -> File)
另：建议在服务端保存md内容之前，将图片正则替换为相应的url，嗯。。。未来版本可能会加入这个操作吧---虽然这个操作很简单。

**Comment by shijunti19** [comment]
@CHENXCHEN 恩好的。` formdata.append(_img, this.img_file[_img]);`你看的代码，_img不就是`./0`
![image](https://user-images.githubusercontent.com/5392211/28408289-9100c9d0-6d69-11e7-8457-3f5c2a97a8f6.png)
![image](https://user-images.githubusercontent.com/5392211/28408305-9c8eccf2-6d69-11e7-8657-b40b167a3aaa.png)
其他坏境没测试，反正我本地是这样的，点号我记得在一些php服务器里确实有特殊意义吧！不建议作为键名

**Comment by CHENXCHEN** [comment]
@shijunti19 是的，我也使用PHP，这个图片文件名其实是由客户端生成的，对服务端没有任何意义

**Comment by CHENXCHEN** [comment]
你在1楼提出的建议
1. 添加一个可以将文件名替换为对应url的操作，这个操作可能未来版本会提供，需要讨论
2. 添加一个可以添加url(可能未来版本会提供)，文件列表的操作（这个没有必要，因为已经有了`$imgAddByFilename`操作，虽然这个操作是添加一个文件，但可以多次执行）

**Comment by shijunti19** [comment]
@CHENXCHEN 但是回调里替换必须用到他，因为用点号多了一步替换而已，其他没什么了！所以只是建议支持自定义格式！把./这部分弄成字符或者自定义。
有种情况用得到，就是md的源代码我直接保存到数据库里，我不替换图片，我前台展示的时候才替换，就需要用到这个./格式了，（这种的话，我服务器删除图片，我就可以直接把内容里的图片都匹配删除了）

**Comment by shijunti19** [comment]
@CHENXCHEN 恩好的，第二点的前提是md源代码里替换掉了图片，如果不替换，就需要你添加这种方法了！你这个是添加物理文件的，我需要的是添加http的url图片，主要就是为了我重新编辑的时候，上图图片下面有个下拉，加载的时候就有了。类似微信什么的有些内容里可以提取图片就可以使用这种方法，类似表情！

**Comment by CHENXCHEN** [comment]
@shijunti19 不替换图片直接保存在源代码里这种行为不是很推荐。。因为处理起来太麻烦，因为对于每一个md文档都要维护一个映射表----文件名->url的映射，费神。。

设计的时候仅考虑到了上传图片前的预览行为，所以只考虑到了添加物理文件这个操作。
而用户如果需要添加图片的话，完全可以通过语法`[]()`来添加，所以没有考虑到需要这个操作，但你所提到这个操作有可能是被开发者所需要的。。未来版本会加上它

**Comment by CHENXCHEN** [comment]
@shijunti19 非常感谢提供建议~我们会不断改进~~

**Comment by CHENXCHEN** [comment]
未来版本添加了操作之后再关闭该issue

**Comment by shijunti19** [comment]
好的

**Comment by shijunti19** [comment]
增加一个：![图片](./0 '123')可以正常识别
后期升级的时候要识别下格式，! [图片](http://127.0.0.14/public/uploads/231.jpg "图片标题")
如果是http也应该正常识别才行，编辑的时候图片已经替换，所以需要这样弄

**Comment by CHENXCHEN** [comment]
“图片标题”是放到中括号里面的啊

**Comment by shijunti19** [comment]
@CHENXCHEN 哦不是，`./0`换成具体的http图片网址也可以正常显示！现在还不行，就是图片上传后，路径替换，我上面的格式是md的，不过他支持图片标题（多了点而已，无关的）。

**Comment by CHENXCHEN** [comment]
@shijunti19 **2.1.11**版本发布: [LOG](https://github.com/hinesboy/mavonEditor/blob/master/LOG.md)
