### ISSUE TITLE
暴露方法 使得同样md 格式文本，解析出和编辑器同样的 html 结构，同时根据参数支持和编辑器一样的代码高亮的html结构，另外发现 markdown-it-highlightjs-external 和 markdown-it-highlightjs 两个插件渲染不一样

### ISSUE THREAD

**Issue by hipi** [hinesboy/mavonEditor#313]
## 需求：暴露方法 使得同样md 格式文本，解析出和编辑器同样的 html 结构，同时根据参数支持和编辑器一样的代码高亮的html结构

我的需求很简单 ，编辑一个md 后，我数据库 保存的是 `md`格式的文本，想 把md 解析成 和编辑器一样的html结构 ，使用文档给出的 导出 markdown-it 对象后 无法 高亮 ，查看issues 发现有建议使用`markdown-it-highlightjs` 插件替换，但发现解析出来的 html 结构不一样。鉴于`markdown-it-highlightjs-external`的作者 @CHENXCHEN 是仓库的贡献者之一，编辑器也使用了`markdown-it-highlightjs-external`这个插件 ，所以把issues 发在这了。
## template
同样 js 渲染 ```var a = 1```
- markdown-it-highlightjs-external 
```html
<pre>
    <div class="hljs">
        <code class="lang-js">
            <span class="hljs-keyword">var</span> a = <span class="hljs-number">1</span>;
        </code>
     </div>
</pre>
```
- markdown-it-highlightjs 
```html
<pre>
    <code class="hljs lang-js">
        <span class="hljs-keyword">var</span> a= <span class="hljs-number">1</span>;
    </code>
</pre>
```

***发现 `markdown-it-highlightjs-external ` 插件多了一个 `div`***

**Comment by chenyeah** [comment]
@CHENXCHEN 希望能给出解决办法 ，不胜感激
