### ISSUE TITLE
关于md与html的反向解析的诉求

### ISSUE THREAD

**Issue by nbutmickey** [hinesboy/mavonEditor#314]
您好，我有一需求就是：我数据库里面存储的是利用你的mavonEditor生成的html代码，现在希望修改里面的内容，能否实现html到md文档格式的解析呢？

**Comment by tfh93121** [comment]
数据库应该存markdown，然后在前端获取到数据库数据后渲染成html。
你这个逻辑就错了，而且md存在数据库中更加精简。

**Comment by nbutmickey** [comment]
那用什么渲染？我有一个展示端需要展示，直接用markdown有些东西无法解析出来吧。

**Comment by tfh93121** [comment]
参考 #249

**Comment by nbutmickey** [comment]
谢谢。
