### ISSUE TITLE
希望支持Markdown语法高亮

### ISSUE THREAD

**Issue by seekcx** [hinesboy/mavonEditor#32]
左边MD语法没有高亮，用户体验不好，希望能支持语法高亮。

**Comment by CHENXCHEN** [comment]
支持语法高亮，请仔细看文档。

**Comment by DullSky** [comment]
![image](https://user-images.githubusercontent.com/15259698/28805691-6c5a3452-769e-11e7-9d04-6e8dffad0a00.png)
他所指的语法高亮是指markdown语法高亮，而非代码高亮，截图是editor.md的，就扩展性而言，不如editor.md，留给用户自定义的地方不是很多，比如我更喜欢Google Code Prettify，原生支持代码行号，但是就性能而言楼主的确是性能更好。本来打算换成你的编辑器，但是使用过程中感觉还不是很完善，楼主加油，看好你

**Comment by CHENXCHEN** [comment]
@DullSky 明白了。。大概指的是类似`stackEdit`那种即时渲染的吧。这个`TODO`放到未来版本加入。

**Comment by panio123** [comment]
我个人觉得吧，这个功能可有可无不如无，谁会用它来写代码么？顶多就手写那么几句，一般都是复制过来吧。

**Comment by seekcx** [comment]
@panio123 也不能让每个用户都去下载一个编辑器吧，主要是目标用户不是像github这类开发者，普通用户你问他markdown是什么，可能根本不知道。

**Comment by hzjswlgbsj** [comment]
先在使用的2.4.9，很希望能够有代码高亮，不打算做的话可否加上行号，或者吧代码的背景颜色加深一点点，现在的版本几乎看不清

**Comment by guolihuaGitHub** [comment]
按照官方文档的步骤添加配色跟代码高亮为何一点用都没？

**Comment by daixujie666** [comment]
@guolihuaGitHub 你解决了没，我用的时候也是没反应。

**Comment by daixujie666** [comment]
已经解决，😄
