### ISSUE TITLE
mavonEditor默认选中

### ISSUE THREAD

**Issue by 86driver** [hinesboy/mavonEditor#328]
我在使用vue过程的过程中，嵌入mavonEditor的时候，是默认输入状态并且鼠标直接跳转到mavonEditor文本中，有没有大佬赐教一下的

**Comment by wujidong** [comment]
选取元素，focus

**Comment by tobradex** [comment]
I have the same problem. My Editor is position at the bottom of the page, and when the content of the page is too long, the focus event of the text area scrolls whole page to the markdown editor.

`this.getTextareaDom().focus();`

**Comment by wujidong** [comment]
> I have the same problem. My Editor is position at the bottom of the page, and when the content of the page is too long, the focus event of the text area scrolls whole page to the markdown editor.
> 
> `this.getTextareaDom().focus();`

你的是Vue项目吗？是的话可以加上以下代码试试
    mounted() {
      this.$nextTick(()=> {
        document.getElementsByClassName('auto-textarea-input')[0].blur(); // 获取textarea 不一定是auto-textarea-input
        window.scrollTo(0, 0)
      })
    }
至于为什么会自动滚动到底部，我也不太清楚。 @86driver 
是否也能解决你的问题呢？
还有，我提的问题到现在还没解决，[https://github.com/hinesboy/mavonEditor/issues/329]($符号个数问题)，加入你写8个“$”，预览只会显示4个...

**Comment by 86driver** [comment]
> > I have the same problem. My Editor is position at the bottom of the page, and when the content of the page is too long, the focus event of the text area scrolls whole page to the markdown editor.
> > `this.getTextareaDom().focus();`
> 
> 你的是Vue项目吗？是的话可以加上以下代码试试
> mounted() {
> this.$nextTick(()=> {
> document.getElementsByClassName('auto-textarea-input')[0].blur(); // 获取textarea 不一定是auto-textarea-input
> window.scrollTo(0, 0)
> })
> }
> 至于为什么会自动滚动到底部，我也不太清楚。 @86driver
> 是否也能解决你的问题呢？
> 还有，我提的问题到现在还没解决，[$符号个数问题](https://github.com/hinesboy/mavonEditor/issues/329)，假如你写8个“$”，预览只会显示4个...
> 不知道你们是否也有这样的问题。

谢谢，这个应该是作者有意的用途把，  我查了一下vue文档，今天回去用scrollBehavior 试一下看可行不~

**Comment by hinesboy** [comment]
prop：autofocus 可控制焦点是否自动聚焦

**Comment by zsl1549** [comment]
@86driver   请问怎么解决的？

**Comment by zsl1549** [comment]
@hinesboy   autofocus 可控制焦点是否自动聚焦 不起作用啊

**Comment by 86driver** [comment]
> @86driver 请问怎么解决的？

时间有点久了 我也不记得当时怎么弄的了

**Comment by chaselss02** [comment]
> prop：autofocus 可控制焦点是否自动聚焦

成功了谢谢大佬
