### ISSUE TITLE
将value传到数据库后，其他地方引用value不能解析Markdown语法的问题

### ISSUE THREAD

**Issue by Shallownight** [hinesboy/mavonEditor#33]
我在Markdown编辑之后，存储value，在别的地方引用，任然是编辑时候自己写的那一串文字，没有加入Markdown的样式：
![0up7 d u vvy6 fn_9sq3z7](https://user-images.githubusercontent.com/18738913/28406400-0901fd7a-6d63-11e7-8e8b-d0f378f594f9.png)
找了一下发现似乎没有解析Markdown语法的API。使我没有找到吗，还是需要引入其他包来进行语法转换呢？

**Comment by CHENXCHEN** [comment]
如果你想获得渲染后的html的话，可以通过ref引用组件实例获取其内的值`d_render`，另：我们提供了`change`事件来获取md源内容以及渲染解析后的html内容.

**Comment by Shallownight** [comment]
@CHENXCHEN 
抱歉没有仔细看到change事件……
引用change事件获得render之后，再把它输出到别的界面，有部分CSS没有渲染出来：
![Uploading 1.png…]()

![2](https://user-images.githubusercontent.com/18738913/28410581-ac7be31e-6d70-11e7-87ea-8456c182b892.png)

这个是import 'mavon-editor/dist/css/index.css'的问题吗？我已经在入口文件引入了~

**Comment by CHENXCHEN** [comment]
请帖出md源码。。

**Comment by Shallownight** [comment]
@CHENXCHEN 
main.js入口文件：
![main](https://user-images.githubusercontent.com/18738913/28413994-3a3bac42-6d7c-11e7-9866-c77a826e47e8.png)

Markdown引入：
![default](https://user-images.githubusercontent.com/18738913/28414030-593f4f40-6d7c-11e7-845d-dfb10c509191.png)

获取解析后后的HTML：
![default](https://user-images.githubusercontent.com/18738913/28414056-7d93c4f2-6d7c-11e7-8cc1-781e377eabe1.png)

上传到数据库后，从数据库取出解析后的HTML，赋给变量content，然后：
![default](https://user-images.githubusercontent.com/18738913/28414098-a3a13878-6d7c-11e7-8305-ff2f391fb65d.png)

**Comment by CHENXCHEN** [comment]
额。。我的意思是 未解析前的md内容。。。
不过。。我看到你这代码大概明白了，应该是你的div没有引用md的css样式吧。。

**Comment by Shallownight** [comment]
@CHENXCHEN 
恩恩，是的，在div中要添加class="markdown-body"。
不过不知道这是常识，还是read.me文档里面没写……第一次用用的很懵逼……

**Comment by Shallownight** [comment]
@CHENXCHEN 
恩恩，是的，在div中要添加class="markdown-body"。
不过不知道这是常识，还是read.me文档里面没写……第一次用用的很懵逼……

**Comment by CHENXCHEN** [comment]
额。。我们会更新README文档的，感谢提供反馈。。

**Comment by CHENXCHEN** [comment]
如果想要代码高亮的话还要引入另外css类`code-hybrid`

**Comment by Shallownight** [comment]
@CHENXCHEN 
好哒，谢谢帮助！！
