### ISSUE TITLE
总是自动获取输入焦点，很烦

### ISSUE THREAD

**Issue by guygubaby** [hinesboy/mavonEditor#338]
总是自动获取输入焦点，很烦，是我配置错误还是有一个属性来控制啊

**Comment by wujidong** [comment]
[#328](https://github.com/hinesboy/mavonEditor/issues/328)

**Comment by tangniyuqi** [comment]
我也遇到这个问题

**Comment by guygubaby** [comment]
> 我也遇到这个问题
> 多个富文本使用 我的是自动获取焦点。你有好办法取消？

mounted() {
    this.$nextTick(() => {
      const mdEl = document.getElementsByClassName('auto-textarea-input');
      if (mdEl[0]) {
        mdEl[0].blur();
      }
      // window.scroll(0,0);
    });
  },

**Comment by guygubaby** [comment]
不知道这样对不对🤣

**Comment by guygubaby** [comment]
这个用不了的话我也就不晓得怎么办了

**Comment by sannai** [comment]
你的搞了了？我使用for循环每次都跑中间去获得焦点

**Comment by guygubaby** [comment]
贴一波代码看看

**Comment by sannai** [comment]
> 贴一波代码看看
大佬就是一个循环，没啥好贴代码
![image](https://user-images.githubusercontent.com/30621891/48062644-98b87100-e1fd-11e8-9e23-c3dab32c1691.png)

**Comment by guygubaby** [comment]
有多个那就都取消了试试呢

**Comment by sannai** [comment]
> 有多个那就都取消了试试呢

不循环毛问题，一循环就有问题。

**Comment by sannai** [comment]
> > 有多个那就都取消了试试呢
> 
> 不循环毛问题，一循环就有问题。

老板看到这功能吓一跳，哈哈。

**Comment by guygubaby** [comment]
啊哈哈哈，我也不晓得该咋办了，抱歉啊
