### ISSUE TITLE
建议希望控件能直接读取rander

### ISSUE THREAD

**Issue by shinseed** [hinesboy/mavonEditor#34]
case: 我把render 存进数据库，然后第二次读取的 时候 重新把 数据库里的render 给控件 的v-model 会显示不出来
我必须 自己在下面 写一个 dev v-html来做 此控件的显示控件如图 希望 能不用自己在v-html
![image](https://user-images.githubusercontent.com/13995240/28664746-ffa547d2-72f3-11e7-8fba-6b6979b590be.png)

**Comment by CHENXCHEN** [comment]
。。必须要v-html指定html代码，否则的话会被转义不被执行，仅显示这些代码。
