### ISSUE TITLE
请问有没有解析函数？

### ISSUE THREAD

**Issue by liuzhushaonian** [hinesboy/mavonEditor#35]
抱歉我是第一次使用，虽知道markdown的存在但平常并没有时间研究它，现在使用Vue做项目看到这个挺不错的，只是翻看了很久也没找到想要的解析函数，能够把md格式转为html格式，所以想问问直接方便的解析函数是什么？如果我不小心看漏了请见谅，对了还有内容的获取与上传，抱歉真的是新手，新到不行的那种。谢谢

**Comment by CHENXCHEN** [comment]
md渲染我们用的是`markdown-it`解析引擎，代码高亮用的`highlight.js`，解析函数位于[这里](https://github.com/hinesboy/mavonEditor/blob/master/src/mavon-editor.vue#L105)

**Comment by liuzhushaonian** [comment]
那么获取内容呢？该如何获取已经编辑在markdown里面的内容，感谢回答

**Comment by CHENXCHEN** [comment]
我们提供了一个`change`事件可以获取md源文件以及解析后的html
或者你可以通过组件的引用，组件里的`d_value`和`d_render`分别是md源内容和html解析内容

**Comment by liuzhushaonian** [comment]
你好，可否提供直接的获取内容方法，组建里的以及渲染过后的内容都能随时提取，因为一旦没触发这个change事件，也就拿不到那些数据了，这还是有点麻烦的

**Comment by CHENXCHEN** [comment]
@liuzhushaonian 在楼上已经提到过。
> 或者你可以通过refs获得组件引用实例，组件里的d_value和d_render分别是md源内容和html解析内容
