### ISSUE TITLE
预防xss攻击时候,库里面存在重大问题,

### ISSUE THREAD

**Issue by xianzhiyun** [hinesboy/mavonEditor#368]
this.$refs.markdownEdit.markdownIt.set({html: false}),可以预防部分xss 攻击但是:
<a$
<img src=x onerror=prompt(/test_really/);>#">
<a$

这条的命令不能过滤掉,
如果在
![image](https://user-images.githubusercontent.com/23547626/49278572-2f581500-f4c0-11e8-86bd-0743d3aba0fc.png)
把帮助文档注释就可以了,目前还不明白,希望看到后,回复一下原因,谢谢Oliver_web@163.com

**Comment by OliverWeb** [comment]
这个文件是在你的src目录下,目前技达不到,希望你有空帮忙看一下
`<a$
<img src=x onerror=prompt(/test_really/);>#">
<a$`

**Comment by OliverWeb** [comment]
![image](https://user-images.githubusercontent.com/23547626/49278739-a2618b80-f4c0-11e8-84db-d192e4ca821a.png)
中间不能放在一行,格式一定要的换行才会出现这种情况

**Comment by OliverWeb** [comment]
前端技术还没有深入了解,希望能得到大神指点,

**Comment by xiaotiandada** [comment]
😑

**Comment by ygj6** [comment]
v2.10.0版本已经发布，新版本只在渲染时过滤xss，问题解决关闭
