### ISSUE TITLE
外部事件获取 编辑器里的 html内容

### ISSUE THREAD

**Issue by z253573760** [hinesboy/mavonEditor#374]
我想在编辑器外 写一个保存按钮 点击保存按钮的时候 拿到html 部分的代码 请问怎么做呢 是否有对外的 API 或者有实现方法吗  谢谢

**Comment by z253573760** [comment]
比如我再移动端做展示的时候我想默认只显示右边Markdown的 部分 隐藏掉左侧 这块有API吗

**Comment by 8MarkOut** [comment]
我刚刚想到一个方法，绑定change函数，就能得到value , render

**Comment by ZhangWeifang2015210405064** [comment]
value好像不是html格式的代码

**Comment by hinesboy** [comment]
v-model 可以实时获取md内容， @change事件 可以获得 value(md内容), render（html内容）
