### ISSUE TITLE
Nodejs 引入的时候 报错了

### ISSUE THREAD

**Issue by atyy** [hinesboy/mavonEditor#38]
ReferenceError: window is not defined  怎么解

**Comment by CHENXCHEN** [comment]
问题能贴详细点吗。。

**Comment by atyy** [comment]
我可以加你微信吗，我跟你细聊，这个框架我特别喜欢   ， 或者你加我  zzj625206557  ，我也特别喜欢你

**Comment by atyy** [comment]
大兄弟还在吗，真有好几个问题 0.0

**Comment by CHENXCHEN** [comment]
@atyy 有问题的话贴在这吧，让更多人有参考。

**Comment by atyy** [comment]
@CHENXCHEN 我有两个问题：
  1. 能不能通过<script>直接引入
  2. 如果我用nodejs require引入  会 报错   ，window is not define  你可以试试

**Comment by CHENXCHEN** [comment]
1. 可以通过script引入
2. 可以给个样例代码吗？

**Comment by atyy** [comment]
1.  怎么通过  script 引入，你把html js 贴下，我觉得直接引入的用的人还是比较普遍，你还是贴出来好
2.  这边  很难说明，因为 内容比较多，所有你不嫌麻烦  可以加个qq也可以，我给你截图 之类的，还可以给你提意见，不要怕麻烦，有时间还可以多交流。
