### ISSUE TITLE
编辑器图标不显示的问题

### ISSUE THREAD

**Issue by 1980744819** [hinesboy/mavonEditor#382]
chrome 浏览器
加载的时候是这样的
![image](https://user-images.githubusercontent.com/20081659/50960031-611cbc80-14ff-11e9-9188-cd200738ec76.png)

**Comment by 1980744819** [comment]
CSS文件已经加了
![image](https://user-images.githubusercontent.com/20081659/50960218-d12b4280-14ff-11e9-9a0c-e7023151b21d.png)

**Comment by ibubbo** [comment]
检查是否有图标冲突
