### ISSUE TITLE
可以直接读取readme.md文件吗？

### ISSUE THREAD

**Issue by wangyibinwangyi** [hinesboy/mavonEditor#383]
希望可以像git一样，可以直接使用组件读取一份readme.md文件，显示在页面中。。不知道目前的功能可否实现？谢谢。

**Comment by hinesboy** [comment]
我觉得这个功能应当归属于业务功能，不应当封装在组件中，您可以在您的业务系统中使用md解析文件，当作初始值传入，这样是不是好点？
