### ISSUE TITLE
工具栏在Chrome浏览器下显示异常

### ISSUE THREAD

**Issue by yang131323** [hinesboy/mavonEditor#385]
### 详细描述
工具栏在chrome浏览器显示异常，效果如下图：
![dc _ 1m6o_cpxg3 ytd62p](https://user-images.githubusercontent.com/32360827/51719236-9c80c480-2083-11e9-8d38-2e3743c798e8.png)
环境如下：
Google Chrome 已是最新版本
版本 71.0.3578.98（正式版本） （64 位）
同时在微软自带的浏览器（edge）测试一样显示异常

**Comment by hinesboy** [comment]
是否没有引入 css 样式， 详情参考readme.md
