### ISSUE TITLE
Add option for disable some keyboard shortcuts

### ISSUE THREAD

**Issue by notiv-nt** [hinesboy/mavonEditor#389]
## Problems:

1) [**Tab** trapping.](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html)
2) Browser hotkeys (**cmd+1**, **cmd+2**)...

---

I can make a PR, if this plugin is still maintainable.

**Comment by hinesboy** [comment]
v2.7.3 add a prop shortCut ( switch for all shortcuts )
 If you have a better idea, welcome your PR！
