### ISSUE TITLE
上传图片能否支持ie9？

### ISSUE THREAD

**Issue by vcxiaohan** [hinesboy/mavonEditor#39]
我看你们给出的例子：
```
var formdata = new FormData();
for(var _img in this.img_file){
    formdata.append('file', this.img_file[_img]);
}
axios({
    url: '/material/add',
    method: 'post',
    data: formdata,
    headers: { 'Content-Type': 'multipart/form-data' },
}).then((res) => {
	this.$refs.mavonEditor.$imglst2Url([['./0', res.data.url]])
    console.log(res);
})
```
但是FormData ie9是不生效的，有没有其他的上传办法，或者能否支持嵌入webuploader上传插件：
```
import WebUploader from 'webuploader';
import 'webuploader/dist/webuploader.css';
```

**Comment by CHENXCHEN** [comment]
根据[mdn文档](https://developer.mozilla.org/zh-CN/docs/Web/API/FormData)指出
formdata不支持ie9
![image](https://user-images.githubusercontent.com/7724525/28750631-464445e0-7523-11e7-8196-d1f483becad4.png)
也许你可以使用其它插件来实现上传

**Comment by vcxiaohan** [comment]
我使用webuploader集成到里面，但是具体逻辑有点紊乱，如果能把上传图片的那个图标给webuploader使用，就好了
```
this.uploader = WebUploader.create({   
    server: '/article/add',      
    // 选择文件按钮      
    pick: '.fa-picture-o',// 这里不好传给webuploader
})
```
或者能自定义图标的话，也行，我就直接自定义一个上传图片替代你们给出的默认图标

**Comment by CHENXCHEN** [comment]
@vcxiaohan 图片上传时会响应event，传递一个File给用户，用户可以使用File来上传文件，没想到ie9也不支持File。。
![image](https://user-images.githubusercontent.com/7724525/28812295-a37314e0-76c6-11e7-81c0-6a0e04bd4ce6.png)

一个临时的解决方案是：你可以通过ref获得组件实例，并通过实例下的`toolbar_left`里的`img`元素来做事件绑定操作。
