### ISSUE TITLE
代码高亮样式不正常

### ISSUE THREAD

**Issue by ALNY-AC** [hinesboy/mavonEditor#391]
![image](https://user-images.githubusercontent.com/20777182/52412606-3895db80-2b1a-11e9-8a87-1078d6eea242.png)

**Comment by notiv-nt** [comment]
https://github.com/hinesboy/mavonEditor/blob/master/README-EN.md#props

```
  codeStyle: ...
```

https://github.com/hinesboy/mavonEditor/blob/master/src/lib/core/hljs/lang.hljs.css.js

?

**Comment by ALNY-AC** [comment]
````html
 <mavon-editor :box-shadow="false" code-style="vs2015" :toolbars="toolbars" style="height: 100%" :value="value" @change="(v)=>$emit('input',v)">-editor>
````
这是我的代码

**Comment by hinesboy** [comment]
vs2015展示的样式即如此，与实际编译器有出入，非常抱歉
