### ISSUE TITLE
分数线显示不正常

### ISSUE THREAD

**Issue by goofy-he** [hinesboy/mavonEditor#392]
连续输入多个
$${2 \over 3}$$
$${2 \over 3}$$
$${2 \over 3}$$
$${2 \over 3}$$
$${2 \over 3}$$

会有一些分数线不显示的问题

**Comment by hinesboy** [comment]
![image](https://user-images.githubusercontent.com/26454305/55123107-50620700-513c-11e9-9f40-6b854d853548.png)
您可以截图我看下吗，感谢

**Comment by goofy-he** [comment]
> ![image](https://user-images.githubusercontent.com/26454305/55123107-50620700-513c-11e9-9f40-6b854d853548.png)
> 您可以截图我看下吗，感谢
![1](https://user-images.githubusercontent.com/30360434/55167948-de75d600-51ac-11e9-8395-7a5c515cb0d4.png)

**Comment by goofy-he** [comment]
> ![image](https://user-images.githubusercontent.com/26454305/55123107-50620700-513c-11e9-9f40-6b854d853548.png)
> 您可以截图我看下吗，感谢

大佬能解决下吗
