### ISSUE TITLE
$img2Url中$changeUrl报未定义错误

### ISSUE THREAD

**Issue by YCL686** [hinesboy/mavonEditor#393]
大家好，我在使用mavon-editor的时候，我想统一上传多张图片，参考了readme的实例，后端返回url后，使用$img2Url报错，求教！

个人代码
uploadimg(value) {
      const $vm = this.$refs.mdEditor
      var formdata = new FormData();
      for (var _img in this.img_file) {
        formdata.append("pic", this.img_file[_img]);
      }
      formdata.append("mongoId", value);
      this.$api.post("/imageUpload", formdata).then(res => {
        if (res.data !== []) {
          for (var img in res.data) {
           $vm.**$img2Url**(img, res.data[img]);#这句话报错
          }
        }
      });
    },

mavon源码
$img2Url(fileIndex, url) {
            var reg_str = "/(!\\[\[^\\[\]*?\\]\(?=\\(\)\)\\(\\s*\(" + fileIndex + "\)\\s*\\)/g"
            var reg = eval(reg_str);
            this.d_value = this.d_value.replace(reg, "$1(" + url + ")")
            this.$refs.toolbar_left.**$changeUrl**(fileIndex, url) #这句报错
            this.iRender()
        },

错误原因如下：mavon-editor.js?392d:1 Uncaught (in promise) TypeError: #Cannot read property **'$changeUrl'** of undefined.
@hinesboy

**Comment by wangcanfeng01** [comment]
这个原因在于img_file默认是有一个元素在里面的，index需要进行偏移一位，就可以正常使用，如下所示
 $changeUrl(index, url) {
        index = index + 1
        console.log('修改url' + index)
        console.log(this.img_file[index])
        this.img_file[index][1] = url
        console.log(this.img_file[index])
      },

**Comment by YCL686** [comment]
> 这个原因在于img_file默认是有一个元素在里面的，index需要进行偏移一位，就可以正常使用，如下所示
> $changeUrl(index, url) {
> index = index + 1
> console.log('修改url' + index)
> console.log(this.img_file[index])
> this.img_file[index][1] = url
> console.log(this.img_file[index])
> },

**Comment by ZhangWeifang2015210405064** [comment]
> 这个原因在于img_file默认是有一个元素在里面的，index需要进行偏移一位，就可以正常使用，如下所示
> $changeUrl(index, url) {
> index = index + 1
> console.log('修改url' + index)
> console.log(this.img_file[index])
> this.img_file[index][1] = url
> console.log(this.img_file[index])
> },

**Comment by ZhangWeifang2015210405064** [comment]
> 这个原因在于img_file默认是有一个元素在里面的，index需要进行偏移一位，就可以正常使用，如下所示
> $changeUrl(index, url) {
> index = index + 1
> console.log('修改url' + index)
> console.log(this.img_file[index])
> this.img_file[index][1] = url
> console.log(this.img_file[index])
> },



> 这个原因在于img_file默认是有一个元素在里面的，index需要进行偏移一位，就可以正常使用，如下所示
> $changeUrl(index, url) {
> index = index + 1
> console.log('修改url' + index)
> console.log(this.img_file[index])
> this.img_file[index][1] = url
> console.log(this.img_file[index])
> },
您好，是修改源码，还是修改传入的参数

**Comment by wangcanfeng01** [comment]
最好是修改源码，只需要修改一处就行

**Comment by YCL686** [comment]
> 这个原因在于img_file默认是有一个元素在里面的，index需要进行偏移一位，就可以正常使用，如下所示
> $changeUrl(index, url) {
> index = index + 1
> console.log('修改url' + index)
> console.log(this.img_file[index])
> this.img_file[index][1] = url
> console.log(this.img_file[index])
> },

谢了

**Comment by hinesboy** [comment]
已修复，感谢

**Comment by Sphrexil** [comment]
![image](https://user-images.githubusercontent.com/99394915/185863278-cfe0e481-c989-47a8-a096-91cef490761a.png)
这里我代码也改了，但是还是报错未定义
![image](https://user-images.githubusercontent.com/99394915/185864251-11bc9fee-2819-4095-bbf2-bd56bc613255.png)
这里我上传的代码是这样
![image](https://user-images.githubusercontent.com/99394915/185863703-492e47ae-608d-4bfc-95d7-4e7686c9a22e.png)
我跟踪是发现跑到dist目录下的mavon-editor.js里面取在里面报的错，大佬们求助
