### ISSUE TITLE
就想问下你们是怎么渲染保存好的markdown文本的？

### ISSUE THREAD

**Issue by laolunsi** [hinesboy/mavonEditor#396]
就想问下你们是怎么渲染保存好的markdown文本的？
mavon-editor默认的代码高亮坏了。
然后我打算用marked来解析，结果解析出来的HTML也太丑了。。。
你们是怎么显示的？

**Comment by qingfengming** [comment]
同问，，我要再去找其他的插件吗？？？

**Comment by Vinsea** [comment]
要想直接保存md格式，就存v-model对应的变量值就行。
要是想保存html，可以通过ref获取：`this.$refs.mEditor.d_render`。
代码高亮可以去网上找主题的css，然后写到自己项目里。
解析出来的HTML都有对应的class，可能你只是没有css

**Comment by laolunsi** [comment]
> 要想直接保存md格式，就存v-model对应的变量值就行。
> 要是想保存html，可以通过ref获取：`this.$refs.mEditor.d_render`。
> 代码高亮可以去网上找主题的css，然后写到自己项目里。
> 解析出来的HTML都有对应的class，可能你只是没有css

是的，我后面加了hightlight，稍微好看不少了。
