### ISSUE TITLE
V-model write html

### ISSUE THREAD

**Issue by willtecti** [hinesboy/mavonEditor#4]
Hello.
How to print html in v-model?

`<mavonEditor  id="v-note-wrapper" placehold="Conteudo" v-model="var"  class="full-width editor-html" />
...
this.var === 'HTML'
...`

**Comment by CHENXCHEN** [comment]
v-model can get origin md content, if you want to get the html, you must using events `@change="change"`, reference [events](https://github.com/hinesboy/mavonEditor#events)

**Comment by willtecti** [comment]
Thanks, I got you with your help.


_**Brazil.**_
