### ISSUE TITLE
上传图片下面的文件标识如何隐藏？

### ISSUE THREAD

**Issue by vcxiaohan** [hinesboy/mavonEditor#40]
没有找到唯一的class，所以不好操作
![图片](http://oeaqy69vv.bkt.clouddn.com/%5D%29~$KU%5DFXBE1%5D$3U%7B%60%25%25GYA.png)

**Comment by CHENXCHEN** [comment]
未提供隐藏这里的方法。。

**Comment by Iamie6** [comment]
我也觉得  这个功能没有必要

**Comment by ryanfeng** [comment]
$imgAdd(pos, $file) {
this.$refs.md.$img2Url(pos, 'https://www.baidu.com/img/bd_logo1.png');
this.$refs.md.$refs.toolbar_left.$imgDelByFilename(pos);
},

**Comment by Chen-WeiZhen** [comment]
我也觉得这个功能没有必要，有需要应该变成上传后的服务器图片路径。
