### ISSUE TITLE
change自动触发

### ISSUE THREAD

**Issue by sannai** [hinesboy/mavonEditor#403]
打开编辑器 自动触发三遍？是我配置有问题吗？ 2.7.1版本
![image](https://user-images.githubusercontent.com/30621891/54343933-dc732980-467a-11e9-8d21-ff7adfce2074.png)
![image](https://user-images.githubusercontent.com/30621891/54344296-7d61e480-467b-11e9-9a50-a8a5473af877.png)
![image](https://user-images.githubusercontent.com/30621891/54344076-2cea8700-467b-11e9-8d01-58d8e2c82555.png)

**Comment by hinesboy** [comment]
有些内部调用触发公共回调方法，v2.7.3已经排除
