### ISSUE TITLE
placehoder不能换行

### ISSUE THREAD

**Issue by GitHubForQiuKai** [hinesboy/mavonEditor#405]

**Comment by hinesboy** [comment]
可以通过换行符`\n`进行换行
![image](https://user-images.githubusercontent.com/26454305/55121678-8f8d5980-5136-11e9-8108-e8efa17dc3dc.png)
![image](https://user-images.githubusercontent.com/26454305/55121702-a59b1a00-5136-11e9-8183-6a8c8999c5a3.png)
