### ISSUE TITLE
vue-cli怎么用啊

### ISSUE THREAD

**Issue by DullSky** [hinesboy/mavonEditor#41]
这个readme写的很模糊啊，vue-cli是既需要配置上面的webpack.config.base.js还是只配置下面的chunks

**Comment by CHENXCHEN** [comment]
参考分支[gh-pages](https://github.com/hinesboy/mavonEditor/tree/gh-pages)

**Comment by DullSky** [comment]
![image](https://user-images.githubusercontent.com/15259698/28761090-b6118732-75de-11e7-8a96-75fd2c4dea80.png)
按照gh-pages的配置了，报了上面的错
http://git.oschina.net/dullsky/edaoeadmin
这个是我的git仓库，请帮忙看一下

**Comment by DullSky** [comment]
已发现问题所在，已解决

**Comment by RoseEnd** [comment]
我也报同样的错你是怎么解决的
