### ISSUE TITLE
qiu优化build的js打包

### ISSUE THREAD

**Issue by DullSky** [hinesboy/mavonEditor#42]
看了gh-pages的demo，webpack.prod.conf.js这个文件是这样打包的，结果就是js文件独立于static文件夹，这样子实在是不美观，demo是吧所有资源文件都放到根目录了，我想这个资源文件仍然保持vue-cli的目录结构应该怎么做
![image](https://user-images.githubusercontent.com/15259698/28763500-375e5e02-75f1-11e7-9ac0-f0a17c0044a1.png)

发现不修改这个output会报下面的错

GET http://192.168.50.234/js/hljs.cpp.js 
Error: Loading chunk 145 failed.

**Comment by CHENXCHEN** [comment]
这个问题跟(#23)[https://github.com/hinesboy/mavonEditor/issues/23]有些类似，目前hljs路径是固定的，我还未找到解决方法。

**Comment by CHENXCHEN** [comment]
**Version 2.4.7**
