### ISSUE TITLE
缺少响应式的获取render的方法

### ISSUE THREAD

**Issue by DullSky** [hinesboy/mavonEditor#44]
很多时候不只是有编辑器的save方法来保存，用户可能还有其他表单来填写，最后通过一个按钮来进行提交，这就需要实时获取markdown内容和html内容，v-model只提供了markdown，其实可以v-model返回一个对象，包含markdown和html代码

**Comment by CHENXCHEN** [comment]
`change`事件

**Comment by CHENXCHEN** [comment]
请仔细看看readme

**Comment by OckhamRazor** [comment]
他的意思应该是希望有一个方法主动获取markdown的value 和render。不必设置一个变量去存储（根据change一直变化）。
简要描述就是methods, not events

**Comment by CHENXCHEN** [comment]
可以通过ref获取组件实例，然后通过组件实例获取其值`d_value`和`d_render`

**Comment by DullSky** [comment]
我的意思是想要一个主动获取html的途径，确实可以通过ref的方式获取d_render，但是作为一个单独的作品这样是不太好的，而应该主动暴露html的获取方法，文档中应该添加这个；另外，麻烦关注下#42问题

**Comment by CHENXCHEN** [comment]
我觉得没有必要提供函数来获取这两个值，添加这两函数也不过是把值返回，不过更新文档是有必要的。。
