### ISSUE TITLE
css样式与font-awesome冲突

### ISSUE THREAD

**Issue by OckhamRazor** [hinesboy/mavonEditor#45]
观察到css文件中使用了font-awesome,可能导致font-awsome.css无法正常显示

**Comment by CHENXCHEN** [comment]
可以给个demo吗?

**Comment by OckhamRazor** [comment]
抱歉，我尝试在jsfildde和runkit上都没能正确地引入npm资源，所以没有一个可视化的demo.不过我通过看源码，我觉得是这个方法引起的.
[class*=" fa-"]:before,[class^=fa-]:before{
font-family:fontello;
font-style:normal;
....
}

这个地方覆盖了所有的fa字体，导致部分icon是无法显示的

**Comment by CHENXCHEN** [comment]
的确有这样的情况，下个版本修正。
