### ISSUE TITLE
编辑区域的滚动条无效

### ISSUE THREAD

**Issue by iPenManShip** [hinesboy/mavonEditor#454]
文档图示：
![滚动条无效](https://user-images.githubusercontent.com/36189354/61095429-11a35300-a486-11e9-8bb5-55a1a2fdd75d.png)

本地代码：
![代码](https://user-images.githubusercontent.com/36189354/61095625-cc335580-a486-11e9-8c33-e0581fc47c2c.png)

实际效果：

![效果](https://user-images.githubusercontent.com/36189354/61095594-ac9c2d00-a486-11e9-9a59-6aed33e4d596.png)

**Comment by iPenManShip** [comment]
已解决，必须给编辑器指定一个高度，不然不会出现滚动条

**Comment by JabinPeng** [comment]
已经给编辑器添加样式了，样式需要加权重吗
![image](https://user-images.githubusercontent.com/37999218/71867440-05523700-3145-11ea-8a22-0f27e7db3ead.png)
