### ISSUE TITLE
always add a row automatically after my typing

### ISSUE THREAD

**Issue by lemos1235** [hinesboy/mavonEditor#46]
How to cancel it?

**Comment by lemos1235** [comment]
like this ![show](https://user-images.githubusercontent.com/23135552/28805586-c29ec126-769d-11e7-9608-984955c69e83.gif)

**Comment by CHENXCHEN** [comment]
sorry, this is a bug, mabey @hinesboy can fix it.

**Comment by lemos1235** [comment]
Maybe add "row='1' " to the textarea element could resolve this,  I`m not sure, but u can try.

**Comment by CHENXCHEN** [comment]
**2.1.13)**
