### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by DullSky** [hinesboy/mavonEditor#47]
1.推荐是代码高亮采用GoogleCodePrettify，这个是主流的代码高亮，包括wordpress等很多网站都用的GoogleCodePrettify，而且或许可以解决作者js和webpack打包的问题#42
2.获取的render并不推荐就是预览的代码，我看到`<pre>`代码已经被hljs被处理过了，正确的应该是只生成`<pre>`保留原生的样子，处理应该是交给前端展示的时候进行处理
3.应该把前端部分的样式抽出来，比如一个博客分为后端编辑和前端展示，前端展示其实只是右侧预览的那部分样式，这样可以减小前端加载样式的体积

**Comment by CHENXCHEN** [comment]
1. 当初选择`highlight.js`的时候，考虑到了这点： `highlight.js`支持176种语言语法高亮，而`GoogleCodePrettify`仅支持55种语法高亮。而就算替换了`GoogleCodePrettify`，打包的问题依然存在，雷同`highlight.js`
2. 在预览区的render是渲染解析后的html代码，若不渲染则无法高亮
3. `前端的部分样式`是指的将与`markdown`相关的css单独抽取出来吗？

**Comment by DullSky** [comment]
3.是的

**Comment by CHENXCHEN** [comment]
明白～未来版本提取

**Comment by CHENXCHEN** [comment]
**Version 2.4.7**
