### ISSUE TITLE
怎么解决插件中self-xss问题？？ 这么严重的问题大家都忽略了吗

### ISSUE THREAD

**Issue by itDjango** [hinesboy/mavonEditor#472]
![image](https://user-images.githubusercontent.com/20026376/62694894-cdb15880-ba07-11e9-8269-e32e520600a4.png)
<img onerror=alert(1) src=1>

**Comment by itDjango** [comment]
<img onerror=alert(1) src=1>

**Comment by YangGuangSuccess** [comment]
吓得我

**Comment by YangGuangSuccess** [comment]
得去看看

**Comment by itDjango** [comment]
> 得去看看



> 得去看看

**Comment by itDjango** [comment]
> 得去看看

所以你的项目有这个问题吗？ 或者你怎么解决的？

**Comment by YangGuangSuccess** [comment]
我暂时还没又发现耶,可能是因为我对这个不是特别吧。

**Comment by itDjango** [comment]
> 我暂时还没又发现耶,可能是因为我对这个不是特别熟悉吧。

你在编辑器里面 输入 
<img src=1 onerror=alert(1)>  
不会弹吗

**Comment by itDjango** [comment]
> > 我暂时还没又发现耶,可能是因为我对这个不是特别熟悉吧。
> 
> 你在编辑器里面 输入
> 
![image](https://user-images.githubusercontent.com/20026376/62927063-5bb28800-bde8-11e9-84bf-0826e4405d52.png)

> 不会弹吗

**Comment by YangGuangSuccess** [comment]
![image](https://user-images.githubusercontent.com/41150022/62927162-8d2b5380-bde8-11e9-8b24-285a2d2e638c.png)
tan'le弹了

**Comment by YangGuangSuccess** [comment]
可是我不知道咋整呀

**Comment by itDjango** [comment]
> 可是我不知道咋整呀

这是比较严重的安全问题，如果你项目对安全性要求很高的话！
我也没有找到解决办法，所以问问其他人有没有好的解决方案

**Comment by YangGuangSuccess** [comment]
嗯嗯,感谢

**Comment by chenghuan10081** [comment]
<a onclick="alert(1);">555</a>
试试

**Comment by qifengwangye** [comment]
@hinesboy 大哥，这个怎么解决啊

**Comment by pengqiangsheng** [comment]
这个用转义
export const unHtml = (str) => {
  return str ? str.replace(/[<">']/g, (a) => {
    return {
      '<': '&lt;',
      '"': '&quot;',
      '>': '&gt;',
      "'": '&#39;'
    }[a]
  }) : ''
}
-------------例子-----------------
const str = "<p></p>"
newStr = unHtml(str)
console.log(newStr)
// &lt;p&gt;&lt;/p&gt;

**Comment by iamKyun** [comment]
刚npm安装完这插件就提示有安全漏洞了，貌似全部版本都有影响，只能自己先解决了

**Comment by PuZhiweizuishuai** [comment]
前端不太熟，不知道怎么办，但我在写后端时我是直接用spring的HtmlUtils做转义的。

**Comment by itDjango** [comment]
> 这个用转义
> export const unHtml =（str）=> {
> return str？str.replace（/ [<“>'] / g，（a）=> {
> return {
> '<'：'<'，
> '”'：'“'，
> '>'：'>'，
> ”'“： '''
> } [a]
> }）：''
> }
> -------------例子-----------------
> const str =“
> 
> “
> newStr = unHtml（str）
> console.log（newStr）
> // <p> </ p>

你这个方法可以解决他一边输入一边预览时xss吗？ 俗称XSS自己。

**Comment by itDjango** [comment]
> 前端不太熟，不知道怎么办，但我在写初步时我是直接用spring的HtmlUtils做转义的。

这个问题后台转义没用的，因为他是在输入的时候即时XSS，在输入完成后前端把数据传给后台时前端可以进行转义，后台也可以转义。
但是就是他在一边输入一边预览时，不知道怎么禁止XSS。

**Comment by itDjango** [comment]
反正我后来是放了了这个编辑器，换了别的。因为我们对安全要求很高，XSS自己也不行。

**Comment by WRCoding** [comment]
> 反正我后来是放了了这个编辑器，换了别的。因为我们对安全要求很高，XSS自己也不行。

大哥，最后你换成了那个编辑器，能推荐下吗

**Comment by NateScarlet** [comment]
Duplicate of #285

我暂时是选择的禁用 html
不过看 #368 好像禁用了还是有问题 不知道什么情况

**Comment by jonathanpmartins** [comment]
I just intalled this editor, soon after...
- When I run "npm audit" i get this message:
![Screenshot from 2020-04-03 20-54-13](https://user-images.githubusercontent.com/6137992/78413343-501d0700-75ed-11ea-8e99-2e09390cf9dd.png)

Visiting the [npm advisory](https://www.npmjs.com/advisories/1169) website I get this:
![Screenshot from 2020-04-03 20-57-35](https://user-images.githubusercontent.com/6137992/78413445-c588d780-75ed-11ea-9300-ca1b0e652999.png)

Any updates? This is bad security practice...

**Comment by itDjango** [comment]
> > 反正我后来是放了了这个编辑器，换了别的。因为我们对安全要求很高，XSS自己也不行。
> 
> 大哥，最后你换成了那个编辑器，能推荐下吗

https://www.npmjs.com/package/wangeditor

**Comment by itDjango** [comment]
> I just intalled this editor, soon after...
> 
> * When I run "npm audit" i get this message:
> 
> ![Screenshot from 2020-04-03 20-54-13](https://user-images.githubusercontent.com/6137992/78413343-501d0700-75ed-11ea-8e99-2e09390cf9dd.png)
> 
> Visiting the [npm advisory](https://www.npmjs.com/advisories/1169) website I get this:
> ![Screenshot from 2020-04-03 20-57-35](https://user-images.githubusercontent.com/6137992/78413445-c588d780-75ed-11ea-9300-ca1b0e652999.png)
> 
> Any updates? This is bad security practice...



So I gave up and recommend you my new one
https://www.npmjs.com/package/wangeditor

**Comment by maltegrosse** [comment]
any updates?

                                                                              
  High            Cross-Site Scripting                                          
                                                                                
  Package         mavon-editor                                                  
                                                                                
  Patched in      No patch available                                            
                                                                                
  Dependency of   mavon-editor                                                  
                                                                                
  Path            mavon-editor                                                  
                                                                                
  More info       https://npmjs.com/advisories/1169

**Comment by Kylelkh** [comment]
可以考虑用xss插件进行转移

**Comment by giladnavot** [comment]
Any news regarding this variability?

**Comment by pnutmath** [comment]
`<img onerror="alert(1)" src="a">` I tried pasting this in mavon-editor, seems its not accepting it. Not even allow to type it

**Comment by jonathanpmartins** [comment]
would be nice to have NPM stop showing this issue!

**Comment by pnutmath** [comment]
Already mailed to npm security advisories. @jonathanpmartins you can mail them again

**Comment by ygj6** [comment]
This issue has been fixed, see [Snyk Report](https://snyk.io/vuln/SNYK-JS-MAVONEDITOR-459108)
To eliminate the npm audit warning, close this issue.

If you have any questions, you can comment.

**Comment by itDjango** [comment]
> This issue has been fixed, see [Snyk Report](https://snyk.io/vuln/SNYK-JS-MAVONEDITOR-459108)
> To eliminate the npm audit warning, close this issue.
> 
> If you have any questions, you can comment.

![image](https://user-images.githubusercontent.com/20026376/104281003-ba9d9480-54e7-11eb-89c0-b8c7a4846fc6.png)

好像并没有解决...
Doesn't seem to be resolved...

**Comment by ygj6** [comment]
xss过滤默认不开启，如需开启，你可以在data中声明`xssOptions`选项，配置xss规则，并设置props；

例子仅供参考：
```vue
<template>
  <div id="editor">
    <mavon-editor v-model="aaa" style="height: 100%" :xssOptions="xssOptions"></mavon-editor>
  </div>
</template>
<script>
module.exports = {
  name: "editor",
  data() {
    return {
      aaa:"",
      xssOptions: {
        whiteList: {
          img: ["src", "alt", "width", "height"],
        },
        stripIgnoreTagBody: true
      }
    };
  },
  computed: {},
  methods: {}
};
</script>
<style>
#editor {
  margin: auto;
  width: 80%;
  height: 580px;
}
</style>
```

**Comment by itDjango** [comment]
> xss过滤默认不开启，如需开启，你可以在data中声明`xssOptions`选项，配置xss规则，并设置props；
> 
> 例子仅供参考：
> 
> ```
> <template>
>   <div id="editor">
>     <mavon-editor v-model="aaa" style="height: 100%" :xssOptions="xssOptions"></mavon-editor>
>   </div>
> </template>
> <script>
> module.exports = {
>   name: "editor",
>   data() {
>     return {
>       aaa:"",
>       xssOptions: {
>         whiteList: {
>           img: ["src", "alt", "width", "height"],
>         },
>         stripIgnoreTagBody: true
>       }
>     };
>   },
>   computed: {},
>   methods: {}
> };
> </script>
> <style>
> #editor {
>   margin: auto;
>   width: 80%;
>   height: 580px;
> }
> </style>
> ```

谢谢解答
但是这样在编辑时看到的是转义后的字符，如果我想编辑时和预览时看到的是一样的怎么处理呢？
![image](https://user-images.githubusercontent.com/20026376/104310788-42e36000-550f-11eb-96ad-6cfc4b7554e3.png)

**Comment by ygj6** [comment]
你可以试试用代码块包起来，应该可以到达这种效果

**Comment by itDjango** [comment]
> 你可以试试用代码块包起来，应该可以到达这种效果

您可能误会我的意思了，我的意思是像github编辑器这样 输入 < > 时，看到的就是< >。 
而不是
![image](https://user-images.githubusercontent.com/20026376/104316241-24816280-5517-11eb-81e1-cc9d5f27b7ec.png)

**Comment by ygj6** [comment]
这看上去是xss开启带来的副作用，后面需要优化，当然我们也欢迎PR。
