### ISSUE TITLE
subfield在最新版本2.1.12无效

### ISSUE THREAD

**Issue by ljc930611** [hinesboy/mavonEditor#48]
刚看到有新版本，所以将2.1.6升级为2.1.12，发现初始化subfield分屏参数无效，不能实现编辑和预览同屏，只能实现编辑预览分屏，当全屏输入点击沉浸式阅读后再次点击预览又可以变成编辑预览分屏显示，是最新版本的分屏参数改了但是文档没有改变吗？

**Comment by CHENXCHEN** [comment]
subfield分屏参数是有效的，在**2.0.9**版本过后都没有更改过该处的代码。
不过若设置subfiled为false的话，编辑和预览同屏将会被替换为编辑单屏和预览单屏。
以下这点没有测试出来:
> 当全屏输入点击沉浸式阅读后再次点击预览又可以变成编辑预览分屏显示

**Comment by CHENXCHEN** [comment]
@hinesboy
