### ISSUE TITLE
Unknown custom element: <mavonEditor> 

### ISSUE THREAD

**Issue by wzdxy** [hinesboy/mavonEditor#5]
Demo is very nice but I can't setup it.

![](http://odovakhft.bkt.clouddn.com/mavonEditor%E6%8A%A5%E9%94%99.png)
```
vue.esm.js?65d7:558 [Vue warn]: Unknown custom element: <mavonEditor> 
- did you register the component correctly? 
For recursive components, make sure to provide the "name" option. 
(found in <App> at D:\DEV\Git\vue2-in-yii2\vue2\src\pages\PersonalCenter.vue)
```

3 pictures, 1 is `main.js`, 2 is `PersonalCenter.vue` ,3 is the console of browser.
version is `^1.5.7`
Is my setup right ?

**Comment by wzdxy** [comment]
Oh, I just tried changing the tag name to lowercase, and it worked.
`<mavon-editor v-model="value"/>`

**Comment by CHENXCHEN** [comment]
@wzdxy sorry about that, we will fix the document.
