### ISSUE TITLE
delete img

### ISSUE THREAD

**Issue by Iamie6** [hinesboy/mavonEditor#51]
工具栏中，图片上传按钮点击之后，下拉菜单打开，点击下拉菜单中的 删除图片 按钮，编辑区的内容没有更新 （例： 工具栏中删除  ./0  这张图片， 但是编辑区中    ! [图片] (./0)   没有消失）

**Comment by CHENXCHEN** [comment]
编辑区中的![图片](./0)的确没有被删除，故意这么做的。。
在写这个功能的时候考虑到这点没必要实现，因为用户可以通过事件响应来自己处理将之删掉。

**Comment by CHENXCHEN** [comment]
你觉得有必要在原始代码中删除吗？

**Comment by Iamie6** [comment]
如果能发到底层做好， 这个功能不属于业务代码， 没必要留给用户自己处理

**Comment by CHENXCHEN** [comment]
下拉菜单提供了的是一种图片列表的记忆方式给用户，不需要的删掉也是处于这种情况-----因为，图片是存在内存里的，如果不提供删除的方式。。有可能一直添加图片会撑爆内存。
