### ISSUE TITLE
怎么获取html文本

### ISSUE THREAD

**Issue by Xiaoshizaizi** [hinesboy/mavonEditor#510]
如题。目前可以直接获取md文本。看到demo里有选项展示html 文本。请教下怎么获取这个html文本呢。

**Comment by Xiaoshizaizi** [comment]
目前是通过change事件来实时获取html文本，希望知道有一次性获取的方式。感谢

**Comment by wencaizhang** [comment]
可以通过 mavonEditor 实例的 `d_render` 属性来获取 html 文本

例如：

```html
<mavon-editor ref="editor" />
```

此时 `this.$refs.editor.d_render` 是渲染后的 html，而 `this.$refs.editor.d_value` 是 markdown 文本。

更多信息可以打印 `this.$refs.editor` 查看。
