### ISSUE TITLE
帮助页面点击任何位置窗口都关闭

### ISSUE THREAD

**Issue by hqzh** [hinesboy/mavonEditor#526]
帮助页面点击任何位置窗口都关闭，点击链接也是窗口关闭

**Comment by chf-gh** [comment]
我也遇到了。使用nuxt 框架。也是点哪里都关闭

**Comment by wanderbaby** [comment]
我要遇到了

**Comment by hqzh** [comment]
@hinesboy 请问有处理吗

**Comment by hqzh** [comment]
看来是不更新了。我把帮助关闭了。

**Comment by hqzh** [comment]
看来是不更新了。我把帮助关闭了。
 this.$refs.md.toolbars.help = undefined
