### ISSUE TITLE
工具栏图标无法显示

### ISSUE THREAD

**Issue by Haiwar** [hinesboy/mavonEditor#528]
![image](https://user-images.githubusercontent.com/35055270/71566965-a9f5c880-2af6-11ea-8395-70df83159a71.png)

**Comment by LiuLiuniuniu** [comment]
@hinesboy  boss，help me🤞😂

**Comment by hubery1996** [comment]
my vue-cli version is 4.1.1,I have this problem too.

**Comment by mmmrvector** [comment]
me too...

**Comment by Haiwar** [comment]
@mmmrvector 😂😂😂🤷‍♀️🤷‍♀️🤷‍♂️🤷‍♂️

**Comment by hubery1996** [comment]
//main.js
import mavonEditor from 'mavon-editor'
import 'mavon-editor/dist/css/index.css'
Vue.use(mavonEditor)

**Comment by mmmrvector** [comment]
> //main.js
> import mavonEditor from 'mavon-editor'
> import 'mavon-editor/dist/css/index.css'
> Vue.use(mavonEditor)

It works! thx!
