### ISSUE TITLE
是否考虑在 工具栏中加入 emoji 表情的选项？

### ISSUE THREAD

**Issue by SuperPony** [hinesboy/mavonEditor#534]
作者是否考虑 能在工具栏中加入 emoji 标签的功能，这个东西感觉会非常有用。:-)

**Comment by code-farmer-i** [comment]
> 作者是否考虑 能在工具栏中加入 emoji 标签的功能，这个东西感觉会非常有用。:-)

试试这个 [v-md-editor](https://code-farmer-i.github.io/vue-markdown-editor/plugins/emoji.html)

**Comment by SuperPony** [comment]
> > 作者是否考虑能在工具上加入emoji标签的功能，这个东西感觉会非常有用。
> 
> 试试这个[v-md-editor](https://code-farmer-i.github.io/vue-markdown-editor/plugins/emoji.html)

谢谢
