### ISSUE TITLE
想用mavonEditor的编辑器，然后对于数据库中读出的md格式的数据，用他来渲染成html

### ISSUE THREAD

**Issue by xaero7** [hinesboy/mavonEditor#546]
似乎有markdownIt对象可以渲染，
https://github.com/hinesboy/mavonEditor/blob/master/doc/cn/markdown.md
能给个例子吗？
@CHENXCHEN 如何用这个编辑器暴露的markdown-it来渲染Katex数学公式？

**Comment by Mulander-J** [comment]
我是这样用的
`Vue.prototype.$markDown = mavonEditor.markdownIt`
`this.$markDown.render(this.dataSource.content||'> 文章暂未上传')`

**Comment by xaero7** [comment]
对，我也是这样：
```
Vue.prototype.$markDown = mavonEditor.markdownIt
this.$markDown.render("### 相对论 $E=MC^2$")
```
标题能渲染，但是$KaTex$公式不行

**Comment by CHENXCHEN** [comment]
Hello, 我开始关注这个问题了
初步定位到有同学对 `markdown-it` 的版本进行升级了，导致引入外部资源高亮解析逻辑已经失效，我需要时间进行解决

**Comment by CHENXCHEN** [comment]
如图，以下 `c++` 代码没有高亮
![image](https://user-images.githubusercontent.com/7724525/79985732-a343f480-84dd-11ea-932f-72fccaa390f9.png)

**Comment by xaero7** [comment]
期待

**Comment by CHENXCHEN** [comment]
Hello, 上面提及的是我本地开发环境的问题，并非bug
因为一些 `hljs` 需要引入一些高亮脚本和样式作渲染，`mavenEditor` 不支持在未实例化的情况下直接使用其内部的 `markdown-it`

**Comment by CHENXCHEN** [comment]
若是 `mavenEditor` 已经实例化，那么其内容放置于外部也可以渲染出来
![image](https://user-images.githubusercontent.com/7724525/80390088-8bee7800-88de-11ea-9eb6-1406d477dddd.png)

**Comment by xaero7** [comment]
如何修改，使得不用出现编辑器也能用来渲染hljs高亮代码、Katex公式？能否给点思路

**Comment by CHENXCHEN** [comment]
从结果上有两种方法
1. 直接使用 `markdown-it` 配合插件进行渲染，具体需要插件代码参考 [这里](https://github.com/hinesboy/mavonEditor/blob/master/src/lib/mixins/markdown.js)
     + 需要替换两个插件, `markdown-it-katex-external` => `markdown-it-katex`, `markdown-it-highlightjs-external` => `markdown-it-highlightjs`
2. 保存 html 渲染结果，需要的时候取出来展示，这种方式需要引入一些统一的 css 渲染样式

**Comment by xaero7** [comment]
用方法1的话，是不是又要import一遍markdown-it.js，然后再用插件渲染？能不能直接用mavonEditor里面的markdown-it？

**Comment by leoluu** [comment]
> 从结果上有两种方法
> 
> 1. 直接使用 `markdown-it` 配合插件进行渲染，具体需要插件代码参考 [这里](https://github.com/hinesboy/mavonEditor/blob/master/src/lib/mixins/markdown.js)
>    
>    * 需要替换两个插件, `markdown-it-katex-external` => `markdown-it-katex`, `markdown-it-highlightjs-external` => `markdown-it-highlightjs`
> 2. 保存 html 渲染结果，需要的时候取出来展示，这种方式需要引入一些统一的 css 渲染样式

@CHENXCHEN 有具体实现例子吗？
