### ISSUE TITLE
如何拿到html代码啊

### ISSUE THREAD

**Issue by wanonder** [hinesboy/mavonEditor#55]
我看API 上写的是 可以通过 htmlcode事件 得到html代码，但是我发现最后拿到的 val 还是 纯文本--  请问下怎样才能拿到html 格式的 文本呢？

**Comment by hinesboy** [comment]
@change 事件可以实时获取html代码 详见REAMDE,md

**Comment by CHENXCHEN** [comment]
另一种方式是通过refs获得组件引用实例，通过实例获取其下的`d_render`值，这个值是渲染过后的`html`，其实例下的值`d_value`是原始`markdown`值

**Comment by wanonder** [comment]
超级感谢  已经解决问题了，还是得仔细看看API啊 哈哈
