### ISSUE TITLE
粘贴html代码时，“<”和“>”要被转义

### ISSUE THREAD

**Issue by HarrisonLee1998** [hinesboy/mavonEditor#563]
# 正常：
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  async defer></script>

# 转义后：
&lt;script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  async defer&gt;&lt;/script&gt;
&lt;/html&gt;

**Comment by hinesboy** [comment]
v2.8.1已修复，谢指出！
