### ISSUE TITLE
添加html标签会被转义掉

### ISSUE THREAD

**Issue by HarrisonLee1998** [hinesboy/mavonEditor#567]
在编辑器中输入html标签，所有的“<” or ">"都会被转义， 导致我无法写行内样式，比如
```html
<div style="background:deeppink;width:200px;height:200px;"></div>
```
 会被转义为
```html
<div></div>
```
而编辑器的查看代码里面是这样的：
```html
&lt;div&gt;&lt;/div&gt;
```

这个问题和我上次反映的不一样 😂 ，我上次反应的问题是在html <strong>代码块</strong> 里面，标签会被转义，但是还是没能全部修复，虽然标签没有转义，但是内部的样式都消失了

**Comment by HarrisonLee1998** [comment]
试了一下以前的版本，2.7.5，就没有上述问题，后面两次分别使用2.8.0和2.8.3，就有问题

**Comment by code-farmer-i** [comment]
试试这个 [v-md-editor](http://localhost:8081/vue-markdown-editor/examples/codemirror-editor.html)

**Comment by code-farmer-i** [comment]
> 试了一下以前的版本，2.7.5，就没有上述问题，后面两次分别使用2.8.0和2.8.3，就有问题

试试这个 [v-md-editor](http://localhost:8081/vue-markdown-editor/examples/codemirror-editor.html)

**Comment by yzyeengang** [comment]
这个问题应该是最近XSS修复引起的 ，详见#548 #538
添加的 'xss' module 会使 
`<div style="background:deeppink;width:200px;height:200px;"></div>`
 变成 
`<div></div>` 
而 ‘markdown-it-sanitizer’ 会使 
`<div></div>` 
变成
`&lt;div&gt;&lt;/div&gt;`
现在的task-list功能也已经失效了

我试着把它处理掉看看

**Comment by hinesboy** [comment]
已发布v2.9.0版本，为xss设置prop: xssOptions, 默认为null，表示不启用xss，若启用，课根据需要传入xssOptions， 具体参考Readme prop部分。
<img width="761" alt="截屏2020-04-20下午8 23 26" src="https://user-images.githubusercontent.com/26454305/79751267-e9b21b80-8344-11ea-9123-41d6e7307056.png">
@HarrisonLee1998 @code-farmer-i @yzyeengang
