### ISSUE TITLE
标题导航栏工作不正常

### ISSUE THREAD

**Issue by sunproud** [hinesboy/mavonEditor#57]
你好，在你的演示网站上试用时发现一个小bug：双栏模式下，标题导航栏工作正常；而单栏模式下，在标题导航栏上的所有点击，都没有任何效果，当做一个纯粹的markdown展示器使用的话，可能有些不方便吧。

**Comment by hinesboy** [comment]
确实如此，下个版本会修复，感谢你的反馈！
