### ISSUE TITLE
“- [ ] ” 任务Checkbox  输入以后出现标签无法被渲染？ 是否考虑未来重新支持渲染？ 

### ISSUE THREAD

**Issue by yaoqiwood** [hinesboy/mavonEditor#571]
![image](https://user-images.githubusercontent.com/28638478/79711811-894abc00-82fb-11ea-961f-0d7a8dff9fe5.png)

**Comment by yzyeengang** [comment]
这个我提交了pr，你可以等待作者@hinesboy合并，也可以先使用我的版本

**Comment by yaoqiwood** [comment]
> 这个我提交了pr，你可以等待作者@hinesboy合并，也可以先使用我的版本

好的 谢谢~
