### ISSUE TITLE
有序列表，无序列表，正文样式，移动端样式问题

### ISSUE THREAD

**Issue by wangxiangyao** [hinesboy/mavonEditor#58]
- 有序列表，无需列表无法正常显示
- 正文，总是居中显示，能不能自己设置啊？
![image](https://user-images.githubusercontent.com/23569474/29598062-22b2b40c-87f9-11e7-9a02-2400680d2179.png)
- 移动端样式问题，有没有办法开个口子统一设置下？
![image](https://user-images.githubusercontent.com/23569474/29598193-e994df3c-87f9-11e7-81a4-4a056e37e39a.png)

**Comment by wangxiangyao** [comment]
在安卓 uc浏览器上 没法使用

**Comment by hinesboy** [comment]
- 有序无序正常，可能是居中导致的无法正常显示
![image](https://user-images.githubusercontent.com/26454305/29644973-0c574434-88ad-11e7-9359-a3e6b83125fc.png)
- 编辑器默认不会居中 ， 你可以先看下是否你在外层设置了 text-align: center
- 浏览器兼容性确实会有问题，有待解决

**Comment by hinesboy** [comment]
另外检查下你的md是否写在了 ::: hljs-center ::: 中

**Comment by wangxiangyao** [comment]
因为我设置了全局样式text-align:center、list-style:none。问题已经解决了O(∩_∩)O，是我的一些全局样式影响到组件样式。

另外，移动端有两个小建议：
- 样式可以配置，比如调整为标准大小的n倍（目前是手动重写，虽然不多，但是不优雅嘛）
- 工具栏，有一个more项，可以把想要的功能放进去，点击出现下拉菜单。

希望组件越做越nice，加油O(∩_∩)O~

**Comment by hinesboy** [comment]
感谢你的建议！:)
