### ISSUE TITLE
可否在后期版本中加入视频播放，图片和视频都支持最好

### ISSUE THREAD

**Issue by 1015770492** [hinesboy/mavonEditor#580]
希望能在图片的基础上 在加个上传视频功能，并且可以通过视频的url播放视频。
暴露一个上传视频服务器的方法，然后获得回调的视频url

**Comment by XLCYun** [comment]
图片本来就支持的。
mavonEditor 是用 markdown-it 渲染的 MD。所以如果要支持视频播放的话，应该得 markdown-it 或者有 markdown-it 的插件支持，markdown-it 关于支持视频URL播放的 ISSUE 15年就有了：https://github.com/markdown-it/markdown-it/issues/122
这是他们的讨论：https://talk.commonmark.org/t/embedded-audio-and-video/441/86
你可以在 https://www.npmjs.com/search?q=keywords%3Amarkdown-it-plugin%20video 找到相关的插件。

**Comment by lizehua-cn** [comment]
<iframe frameborder="0" src="https://v.qq.com/txp/iframe/player.html?vid=l0035e3vymt" allowFullScreen="true"></iframe>
