### ISSUE TITLE
可以提供方法将markdown文本换成html吗？

### ISSUE THREAD

**Issue by LiuYuLu** [hinesboy/mavonEditor#59]
数据库中存储的是markdown的文本，得到后想通过和编辑器一样的渲染方式换成HTML，但是只是想要获得HTML文本，有没有方式呢？

**Comment by hinesboy** [comment]
提供@change方法实时获取html，下个版本会开放markdown对象，允许自行初始化markdown-it对象以及调用其方法，如：
```mavonEditor.markdown.render(md)```
参考[markdown-it](https://github.com/markdown-it/markdown-it)用法
