### ISSUE TITLE
使用vue-cli搭建的项目，现在需要使用hightlight.js

### ISSUE THREAD

**Issue by MickeyMouse623** [hinesboy/mavonEditor#60]
使用vue-cli搭建的项目，现在需要使用hightlight.js，但是根据你的描述信息，无法成功引入
描述不清

**Comment by CHENXCHEN** [comment]
使用`vue-cli`搭建的项目可以参考[gh-pages](https://github.com/hinesboy/mavonEditor/tree/gh-pages)分支

**Comment by jencia** [comment]
这样改的话路径就限定死了，也不能加hash了

**Comment by CHENXCHEN** [comment]
暂时不知如何解决highlight.js的动态路径问题，如果通过webpack打包的话就会被定死，预估未来版本会将这快剔除出来，然后作为插件引入

**Comment by CHENXCHEN** [comment]
Version **2.4.0** 已发布，代码高亮抛弃本地集成而使用`cdnjs`外链，`mavon-editor`将自动按需加载对应的语法高亮文件
