### ISSUE TITLE
cdn挂了！

### ISSUE THREAD

**Issue by kaipingdalao** [hinesboy/mavonEditor#602]

**Comment by geesmart** [comment]
t同问

**Comment by serfend** [comment]
建议不要用cdn，而是存在本地

**Comment by kaipingdalao** [comment]
> 建议不要用cdn，而是存在本地
已经存了，每次打开都不行 心态崩了

**Comment by syf814986678** [comment]
> > 建议不要用cdn，而是存在本地
> > 已经存了，每次打开都不行 心态崩了

怎么存的的 我保存了之后代码块就不显示样式了

**Comment by kaipingdalao** [comment]
> > > 建议不要用cdn，而是存在本地
> > > 已经存了，每次打开都不行心态崩了
> 
> 怎么存的的我保存了之后代码块就不显示样式了

我是这样的，控制台找他每次请求的文件，保存本地，在main.js中引入

**Comment by liangtengyu** [comment]
同样的情况...打开一直转..然后...
![image](https://user-images.githubusercontent.com/29878636/100039445-36f8ed00-2e40-11eb-93c1-f23ff2316975.png)

**Comment by kaipingdalao** [comment]
> 同样的情况...打开一直转..然后...
> ![图片](https://user-images.githubusercontent.com/29878636/100039445-36f8ed00-2e40-11eb-93c1-f23ff2316975.png)

等好了本地存一份吧

**Comment by ygj6** [comment]
当前CDN已经稳定，请确认下是否已经正常

**Comment by ygj6** [comment]
关闭该issue，如有问题可以重新打开讨论
