### ISSUE TITLE
如何自定义导航栏样式

### ISSUE THREAD

**Issue by linxiafenhuo** [hinesboy/mavonEditor#607]
大大，请问如何自定义导航栏样式

**Comment by XLCYun** [comment]
你可以在CSS中试试直接用 /deep/ 或者 ::v-deep 深度选择

**Comment by iCodek** [comment]
this.$refs.md.$refs.navigationContent.parentNode.style.backgroundColor = 'rgba(255,255,255,0.6)'
    this.$refs.md.$refs.navigationContent.parentNode.style.bottom = 'auto'
    this.$refs.md.$refs.navigationContent.parentNode.style.height = 'auto'
给mavon-editor组件加个ref="md"

**Comment by ygj6** [comment]
@linxiafenhuo 
你可以覆盖`v-note-navigation-wrapper`元素里的样式来自定义样式

**Comment by ygj6** [comment]
关闭该issue，如有问题可以重新打开
