### ISSUE TITLE
[建议] command+s 建议下个版本添加为保存快捷键

### ISSUE THREAD

**Issue by a20070322** [hinesboy/mavonEditor#61]
使用mac 开发时习惯用command作为保存文件

**Comment by CHENXCHEN** [comment]
@a20070322 **v2.2.5**添加了该功能，不过没有mac进行测试，能否测试下看是否可行？

**Comment by pyzworld** [comment]
@CHENXCHEN command + s 会和Chrome 的保存网页冲突吧。mac测试
