### ISSUE TITLE
老哥你这npm 包不安全， high severity vulnerability，赶紧修复吧

### ISSUE THREAD

**Issue by gaoxuerong** [hinesboy/mavonEditor#610]

**Comment by ygj6** [comment]
此问题已得到解决，请参阅[Snyk报告](https://snyk.io/vuln/SNYK-JS-MAVONEDITOR-459108)。
目前就告警问题消除已邮件咨询npm安全团队。

**Comment by ygj6** [comment]
关闭issue，有问题可以重新打开
