### ISSUE TITLE
字体大小该怎么切换啊，没看到有对应的功能

### ISSUE THREAD

**Issue by night-Magicl** [hinesboy/mavonEditor#614]
字体大小这么普遍使用的功能，我觉得大佬给加上就更好了，本来项目都引用都差不多了，昨天自己玩了下编辑器，结果愣是没找到字体大小选择都功能，香菇

**Comment by ygj6** [comment]
字体大小当前默认是14px，不过可以设置props :fontSize="24px"来改变字体大小，你可以在工具栏自定义一个下拉框选择fontSize来实现字体大小切换功能。
参考：https://github.com/hinesboy/mavonEditor#api-%E6%96%87%E6%A1%A3

**Comment by ygj6** [comment]
抱歉，你是说的富文本那种对字体大小调整么？如下图：
![image](https://user-images.githubusercontent.com/7699524/101232267-af3a9a80-36eb-11eb-9023-c63a635347b6.png)

如果是，那确实没有，因为当前我们只身一款markdown编辑器，你的需求我想了一下，你可以通过如下方式实现：
![image](https://user-images.githubusercontent.com/7699524/101232508-f07f7a00-36ec-11eb-9adc-f13614a9845e.png)

**Comment by ygj6** [comment]
关闭该issue，如有问题可以重新打开
