### ISSUE TITLE
大神，点击上传图片的回调事件是什么？

### ISSUE THREAD

**Issue by superliyy** [hinesboy/mavonEditor#62]

**Comment by CHENXCHEN** [comment]
`imgAdd`事件，查看[events](https://github.com/hinesboy/mavonEditor#events)

**Comment by liangbizhi** [comment]
估计楼主想判断上传的文件是否为图片文件。

查看源码发现，mavon-editor会判断文件是否为图片类型，如果是，则会$emit    imgAdd事件，否则不会触发该事件。

这里就有个坑了，很难判断上传的文件是否为图片：

但也是有方法的：

```html
<mavon-editor ref="editor" v-model="value"/>
````
添加一个ref
```javascript

function shitImgAdd(pos, file) {
    var type = file.type
    if (!type || !/^image\//i.test(type)) {
        console.log('你上传的不是图片')
        if (this.$refs.editor.$refs.toolbar_left.$imgDelByFilename(pos)) {
            console.log('删除成功')
        } else {
            console.log('删除文件 ' + pos + ' 失败')
        }
    } else {
        console.log('是图片')    
    }
}

module.exports = new Vue({
    el: '#app',
    data: {
        value: '',
    },
    mounted: function() {
        this.$refs.editor.$refs.toolbar_left.$on('imgAdd', shitImgAdd.bind(this))
    },
    beforeDestroy: function() {
        this.$refs.editor.$refs.toolbar_left.$off('imgAdd', shitImgAdd)
    }
})
```
这个方法文档没介绍，比较粗暴。。。
@CHENXCHEN 作者可以看看有没有好的实现方法，或者改进方法~

**Comment by CHENXCHEN** [comment]
同楼上所说，`mavon-editor`的确是已判断了文件类型，在处理完文件添加到本地之后，会有一个`imgAdd`事件相应，此时会返回一个`pos`和`file`，通过file可以进行二次判断，如果判定不通过可以通过`$imgDelByFilename`删除对应`pos`

**Comment by superliyy** [comment]
我可以对上传的图片进行大小，还有类型判断，如果不符合的话，则删去，请问有什么办法可以提供呀

**Comment by CHENXCHEN** [comment]
楼上的楼上已经提及到了`$imgDelByFilename`可以删除，详情查阅文档

**Comment by zgj233** [comment]
@CHENXCHEN  尊敬的作者，我发现了一个问题。 `mavon-editor` 在上传图片的时候， 虽然会自动判断文件类型，只有当上传的文件是图片时才会触发`imgAdd`。 但是如果上传的文件不是图片，也会在

> 点击 图片按钮 的 下拉列表 中出现。
要如何阻止无用文件被添加进 这个下拉列表？ 此时没有触发`imgAdd`，应该不把无用文件名加入“图片下拉列表”才对。**：)**

**Comment by CHENXCHEN** [comment]
@zgj233 这是一个bug，这里处理逻辑没有写对，在下个版本修正，能否新开个issue以作备忘？

**Comment by zgj233** [comment]
好的
