### ISSUE TITLE
在编辑器中设置的某些样式在前端没有显示出来

### ISSUE THREAD

**Issue by k1195453766** [hinesboy/mavonEditor#622]
我使用居中，斜体等样式在前端不能正常显示，在编辑器中是没问题的
编辑器中的样式：
![111 (2)](https://user-images.githubusercontent.com/45040711/93751662-04f4c000-fc30-11ea-9d35-cac3dec257aa.png)

前端样式：

![222](https://user-images.githubusercontent.com/45040711/93751671-08884700-fc30-11ea-9aef-88b041901926.png)

**Comment by k1195453766** [comment]
解决了，前端不能斜体是因为被其他样式给代替掉了，而居左 居中 居右的样式确实没看到有，也没有被其他样式替换掉，看到博主给其他人的建议，加了个单独的css文件，把对应的class样式重写即可，然后全局引用！

**Comment by k1195453766** [comment]
![Uploading 2233.png…]()

**Comment by k1195453766** [comment]
![2233](https://user-images.githubusercontent.com/45040711/93753780-45a20880-fc33-11ea-934f-5180ef420a3e.png)

**Comment by CaptainZZY** [comment]
请问大佬居左 居中 居右的样式是要单独加哪个文件啊，求告知

**Comment by k1195453766** [comment]
> 

自定义css文件，然后修改对应的样式，然后把样式全局引入就可以了
试试我这个文件可以不：
[md.css](http://download.sidama.work/md.css)
在main.js中全局引入即可：import "./md.css";

**Comment by CaptainZZY** [comment]
> > 
> 
> 自定义css文件，然后修改对应的样式，然后把样式全局引入就可以了 试试我这个文件可以不： [md.css](http://download.sidama.work/md.css) 在main.js中全局引入即可：import "./md.css";

大佬，我试了一下您的文件还是不行，居中和斜体还是出不来
