### ISSUE TITLE
斜体 和 有序标签用不了

### ISSUE THREAD

**Issue by jawash5** [hinesboy/mavonEditor#624]
发现斜体和有序标签点击了没有渲染诶

**Comment by itDjango** [comment]
我的也是斜体 不好用 为什么

**Comment by jawash5** [comment]
> 我的也是斜体 不好用 为什么

我是css预处理那儿把斜体样式改过了，我删掉后就好了。

**Comment by itDjango** [comment]
> > 我的也是斜体 不好用 为什么
> 
> 我是css预处理那儿把斜体样式改过了，我删掉后就好了。

是的，确实是这个问题，谢谢
