### ISSUE TITLE
怎么使用TOC啊 (+_+)?

### ISSUE THREAD

**Issue by 520MianXiangDuiXiang520** [hinesboy/mavonEditor#625]
我想在不开启导航栏地状态下使用导航目录功能，应该怎么做啊，并且在 markdown 中直接写 `[TOC]` 并没有生效，是我使用的方法有问题吗？

**Comment by ygj6** [comment]
目录的使用语法是：`@[TOC](目录)`
示例：
![image](https://user-images.githubusercontent.com/7699524/101231785-7c42d780-36e8-11eb-9d96-6e33233bd07f.png)

语法介绍文档：[help_zh-CN.md]( https://github.com/hinesboy/mavonEditor/edit/master/src/lib/lang/zh-CN/help_zh-CN.md)

**Comment by ygj6** [comment]
关闭issue，有问题可以重新打开
