### ISSUE TITLE
添加图片链接的dialog杂乱

### ISSUE THREAD

**Issue by joooooooojo** [hinesboy/mavonEditor#627]
如图:
![屏幕截图 2020-10-24 215653](https://user-images.githubusercontent.com/73393114/97083662-2b998280-1644-11eb-89e5-7214539c9a4c.png)

vue版本是2.6.12

**Comment by ygj6** [comment]
很抱歉，你的问题还存在吗？我试了好几个浏览器都没有出现这个问题，你能详细描述问题复现步骤或者方式吗？

**Comment by ygj6** [comment]
关闭issue，有问题可以重新打开
