### ISSUE TITLE
代码块不能左右滚动

### ISSUE THREAD

**Issue by wangxiangyao** [hinesboy/mavonEditor#63]
![image](https://user-images.githubusercontent.com/23569474/29999888-013eda68-908b-11e7-8eff-ba623db7c4bb.png)
要给代码块加上overflow

**Comment by CHENXCHEN** [comment]
好的，下一版改进

**Comment by CHENXCHEN** [comment]
我在本地测试的代码块是可以拖动的
![image](https://user-images.githubusercontent.com/7724525/30250186-9a2d4ca4-967c-11e7-9760-cd4f537a891e.png)
