### ISSUE TITLE
有没有大佬教教小白xss是怎么配置的呀

### ISSUE THREAD

**Issue by Mnufs** [hinesboy/mavonEditor#631]
一脸懵逼

**Comment by frocelu** [comment]
就像這樣把選項傳進去就好啦。
https://jsxss.com/zh/examples/allow_attr_prefix.html
這邊有進階的例子。
```
xssOptions: {
        whiteList: {
            a: ["href", "title", "target", "download"],
            img: ["src", "alt", "width", "height"],
            video: ["src", "type", "controls", "width", "height", "poster"],
            source: ["src", "type"],
            br: [],
            div: ["class"]
        },
        stripIgnoreTagBody: true
      }
```

**Comment by Mnufs** [comment]
> 就像這樣把選項傳進去就好啦。
> 
> ```
> xssOptions: {
>         whiteList: {
>             a: ["href", "title", "target", "download"],
>             img: ["src", "alt", "width", "height"],
>             video: ["src", "type", "controls", "width", "height", "poster"],
>             source: ["src", "type"],
>             br: [],
>             div: ["class"]
>         },
>         stripIgnoreTagBody: true
>       }
> ```
> 
> https://jsxss.com/zh/examples/allow_attr_prefix.html
> 這邊有進階的例子。

感谢大佬，回头试试！

**Comment by ygj6** [comment]
关闭issue，有问题可以重新打开
