### ISSUE TITLE
(c)被解析成了©

### ISSUE THREAD

**Issue by YiXunOc** [hinesboy/mavonEditor#633]
在使用“(c)”，被解析成了©。

**Comment by ygj6** [comment]
默认是开启印刷体的自动识别，你可以通过设置`{ typographer: false }`关闭它，或者转义。 
 
方式一：属性设置示例如下,更多获取`Markdown-It`示例方式可以参考[markdown.md](https://github.com/hinesboy/mavonEditor/blob/0eb53812a71a0a978f27a2e3e7c7cfd197b4c31c/doc/cn/markdown.md)
```html
<mavon-editor ref="md"></mavon-editor>
```
```javascript
mounted (){
        let markdownIt = this.$ref.md.markdownIt;
        markdownIt.set({ typographer: false }); 
}
```
方式二：转义示例：
![image](https://user-images.githubusercontent.com/7699524/101231573-29b4eb80-36e7-11eb-885b-6176480b59a9.png)

**Comment by ygj6** [comment]
关闭该issue，如有问题可以重新打开
