### ISSUE TITLE
IE9、10和移动端都会报错

### ISSUE THREAD

**Issue by jencia** [hinesboy/mavonEditor#64]

**Comment by CHENXCHEN** [comment]
有没有报错信息？如果是文件上传的话，由于使用的`File` Object，不支持`ie10`以下的版本

**Comment by jencia** [comment]
那可能就是因为使用了`File` Object吧，移动端的错误原因应该也一样，能不能在下一个版本做下兼容？

**Comment by CHENXCHEN** [comment]
ie的话处理比较麻烦，可能要推迟到下下个版本来做兼容了，目前主要在规划插件分离，以及解决hljs的一些问题。

**Comment by CHENXCHEN** [comment]
**Version 2.6.7 Release** 已修复

**Comment by ouyangzhouGIT** [comment]
我ie11也有兼容问题，怎么办
