### ISSUE TITLE
[Bug] md文档的语法分析有问题

### ISSUE THREAD

**Issue by KanKanTAD** [hinesboy/mavonEditor#655]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/22536290/103261642-27d80280-49dd-11eb-99aa-68d81bc89599.png)
![image](https://user-images.githubusercontent.com/22536290/103261674-48a05800-49dd-11eb-8943-1c14f0467502.png)

**Steps To Reproduce**

**Screenshots**

**The expected behaviour**

**Possible solution (optional, but very helpful)**

**Comment by ygj6** [comment]
表格的语法：
```md
|column1|column2|column3|column4|
|-|-|-|-|
|content1|content2|content3|content4|
```
请检查你的markdown语法。

**Comment by ygj6** [comment]
关闭该issue，如有问题可以重新打开
