### ISSUE TITLE
我要把图片预加载到这里

### ISSUE THREAD

**Issue by shijunti19** [hinesboy/mavonEditor#66]
![20170905222451](https://user-images.githubusercontent.com/5392211/30065961-19710e1c-9289-11e7-9aa1-beb51a41307b.png)
编辑文档的时候，我要把图片预加载这里，例如./0 对应http://www.baidu.com/1.jpg
./1对应http://www.baidu.com/2.jpg
有下来选择，和第一次添加效果一样
然后用户自己选择新图片上传的话，就是./2，按顺序增加下去
为了提前给用户加载一些官方图片在这个下啦列表里
怎么实现？
$vm.$imgAddByUrl(>=2.1.11)
我测试了怎么不对啊，图片加载了，但是这个下拉里没加载进去，没变。
我新增的图片还是./0

**Comment by CHENXCHEN** [comment]
实在抱歉，目前功能是没有实现那块的，添加了之后，没有加入到下拉表中，这个功能在未来版本添加

**Comment by CHENXCHEN** [comment]
@shijunti19 **v2.2.5**添加了该功能
