### ISSUE TITLE
是不是做的不对

### ISSUE THREAD

**Issue by shijunti19** [hinesboy/mavonEditor#68]
"mavon-editor": "^2.2.5",
![image](https://user-images.githubusercontent.com/5392211/30255467-b163486a-96d6-11e7-9e53-587c5dc10a1b.png)
![image](https://user-images.githubusercontent.com/5392211/30255474-bad75f76-96d6-11e7-92b6-552a1f61ad05.png)
下拉里应该有./0和./1两张图片啊
现在只有一张，不太对

**Comment by CHENXCHEN** [comment]
能贴一个实例代码吗？这里我看不出来有问题。

**Comment by shijunti19** [comment]
@CHENXCHEN 
```js
info () {
      var that = this
      that.$a031.get(1, '?d=a031&c=yun&m=goods_add', { id: that.data.id }, response => {
        if (response.code === 1) {
          that.cid_options = response.data.cid_options
          for (var key in response.data.good) {
            that.data[key] = response.data.good[key]
          }
          if (that.data.imgs.length > 0) {
            for (var kk in that.data.imgs) {
              console.log(that.data.imgs[kk].id + '+' + that.data.imgs[kk].url)
              that.$refs.mavonEditor.$imgAddByUrl(that.data.imgs[kk].id, that.data.imgs[kk].url)
              //  console.log(that.$refs.mavonEditor.$refs.toolbar_left.$imgAddByFilename(that.data.imgs[kk].id, that.data.imgs[kk].url))
            }
          }
        } else {
          if (typeof response.data.url !== 'undefined') {
            that.$alert(response.message, '系统提示', {
              confirmButtonText: '确定',
              callback: action => {
                that.$router.replace({ path: response.data.url })
              }
            })
          }
        }
      })
    },
就是一个数组，循环添加图片，难道我用错了？
```

**Comment by CHENXCHEN** [comment]
@shijunti19 我明白问题所在了，尽量别用纯数字，自定义添加的加个字母前缀或后缀，因为在mavonEditor内部，上传的图片列表是从0开始递增的，而0显示的是上传图片那个按钮

**Comment by shijunti19** [comment]
@CHENXCHEN 如果我刚开始上传，你默认就是这个啊
![image](https://user-images.githubusercontent.com/5392211/30255859-133f9b9a-96d9-11e7-8482-beef4d64ca54.png)
我的想法就是编辑和添加的页面是一样的，
我的想法是这样的，如果下拉里的图片用户删除了，我在删除触发里写个事件，把内容里的对应图片也删除，这样方便很多，所以这个id必须和原来的也对应!

**Comment by CHENXCHEN** [comment]
无需id对应，删除的时候触发的id就是自定义的，比如你自定义一个./m_0，那么删除会触发的也是./m_0，至于另一个问题我再查一下

**Comment by CHENXCHEN** [comment]
内部有一个count是自增的，若为0则代表有0张图片，通过点击那个按钮上传了两张图片，内部的count此时为2，所以可以显示

**Comment by shijunti19** [comment]
@CHENXCHEN 就是说你默认就是内部不一致，有点头疼，![图片](./0)，我保存的id就是你的id，这里的./0
如果我自定义的话，好像内容里都得替换，还是麻烦事情

**Comment by CHENXCHEN** [comment]
有个临时的解决方法，就是更改内部的`count`，这个`count`被定义为`sum`，位置在`$vm.$refs.toolbar_left.num`(`$vm` => mavonEditor的实例)

**Comment by CHENXCHEN** [comment]
@shijunti19 代码在`src/components/s-md-toolbar-left.vue`，实现逻辑比较简单，如果有更好的通用方法可以提出下建议，或者新建个`pull requests`

**Comment by shijunti19** [comment]
好我看下，
