### ISSUE TITLE
"Error: Input data should be a String"'s problem

### ISSUE THREAD

**Issue by hieunh161** [hinesboy/mavonEditor#70]
In recently, when I run the code I got below issue. 
_Error in callback for watcher "d_value": "Error: Input data should be a String"_
And even if I try the demo on GitHub page, the error is the same.
![123](https://user-images.githubusercontent.com/5295196/30334924-f9181a00-981b-11e7-9c42-7af7063d6858.png)
Please confirm if this is a bug or what can cause this problem. Thanks!

**Comment by CHENXCHEN** [comment]
What's Operation you did do?
I can't no repeat this issue.
Thanks

**Comment by CHENXCHEN** [comment]
I don't understand why you have this icon, cause `mavon-editor` don't have this.
![image](https://user-images.githubusercontent.com/7724525/30357370-dc88e914-9870-11e7-8d2a-4403ea9e97bc.png)

**Comment by CHENXCHEN** [comment]
Maybe it should be `chrome-third-plugins` cause this issue, can you disable this plugin and retry?
![image](https://user-images.githubusercontent.com/7724525/30357468-55c0943a-9871-11e7-893a-4286ea78dfe4.png)

**Comment by hieunh161** [comment]
@CHENXCHEN  Yeah. You are correct, this plugin caused this problem. After disabling and retry, I can run editor normally. The plugin is named ["Grammarly"](https://app.grammarly.com/).

**Comment by hieunh161** [comment]
Basically, I just turn on the grammar plugin which helps me check grammar as well as typo's problems when writing and select any item on the menu bar then above problem occur. I don't know the reason behind. If you can detect and fix it, please let me know because I think this is a very helpful plugin. 
Many thanks.

**Comment by CHENXCHEN** [comment]
Alright, I download this and found it is a helpful plugin, this plugin is awesome, I will detect and fix it, maybe next version.

**Comment by CHENXCHEN** [comment]
Alright, I found it work normally with `mavon-editor` on my pc. 
![image](https://user-images.githubusercontent.com/7724525/30486739-062b8f52-9a64-11e7-890e-752ec8e3e1ea.png)
Maybe you upgrade this plugin version can solve this issue.

**Comment by hieunh161** [comment]
@CHENXCHEN  Thank you for hardworking. I have checked latest version and it seems to work smoothly.
