### ISSUE TITLE
关于图片上传回调的问题

### ISSUE THREAD

**Issue by Red-Asuka** [hinesboy/mavonEditor#701]
我想要上传图片直接为img标签，并且为img标签添加一些默认的行内样式。
查阅了文档没找到实现方法，有什么好的解决办法么？

**Comment by jiawulin001** [comment]
mavonEditor是一种markdown文本格式的编辑器，可以识别html标签，所以你可以考虑直接写html标签。
参考如下：
![image](https://user-images.githubusercontent.com/14244944/128654732-50cd3f46-cd29-458e-a613-3cac7dde154a.png)

**Comment by Red-Asuka** [comment]
> mavonEditor是一种markdown文本格式的编辑器，可以识别html标签，所以你可以考虑直接写html标签。
> 参考如下：
> ![image](https://user-images.githubusercontent.com/14244944/128654732-50cd3f46-cd29-458e-a613-3cac7dde154a.png)

我知道可以直接写HTML，但对于需要为所有图片添加通用的行内样式的情况，这么做效率很低。正如我所提问的，能否支持直接在上传图片时就添加为img标签，比如增加图片文件添加回调事件参数，提供自定义图片插入模板功能。

**Comment by jiawulin001** [comment]
这个是回调没办法解决的，图片在markdown的语法（`![image name](/ur)`）并不支持增加class或者id，除非上传图片的功能不是生成markdown的图片语法，而是直接生成`<img>`标签,当前的mavonEditor无法支持。
