### ISSUE TITLE
vue3版本

### ISSUE THREAD

**Issue by Forest-211** [hinesboy/mavonEditor#703]
## 💬 Questions and Help

后面会适配vue3吗？

**Comment by ygj6** [comment]
会的，我们已经有人在投入适配vue3了

**Comment by HuRuilin** [comment]
> 会的，我们已经有人在投入适配vue3了
预计什么时候能发布呢？

**Comment by hyahm** [comment]
能支持typescript吗

**Comment by ygj6** [comment]
适配vue3的beta版本已经发布到npm了，欢迎试用！
https://github.com/hinesboy/mavonEditor/tree/next
```
npm install mavon-editor@next --save
```

**Comment by JOJO-CPU** [comment]
请问下beta版本稳定吗,可以用于项目中了吗

**Comment by ygj6** [comment]
可以试用，有问题可以提issue或PR，这里有个[demo](https://codepen.io/wangsongc/pen/RwZBEvp)
