### ISSUE TITLE
vue-cli项目对hightlight.js的个人解决方案，分享以供同样喜欢mavonEditor各位参考

### ISSUE THREAD

**Issue by panio123** [hinesboy/mavonEditor#71]
这个问题想必大家都有些头痛，于是自己写了个脚本用于处理这个问题，分享出来以供同样喜欢mavonEditor各位参考，详见：[http://liu-pan.cc/post/59bbc055369ef879867e035f](http://liu-pan.cc/post/59bbc055369ef879867e035f)

**Comment by RoseEnd** [comment]
一直有打包问题，采用你这个方法ok，蟹蟹

**Comment by wenghaoping** [comment]
先不管打包,为什么我直接用:ishljs="true",他就报错,这个找不到哇,
http://localhost:8060/js/hljs.cpp.js net::ERR_ABORTED

**Comment by CHENXCHEN** [comment]
Version 2.4.0 已发布，代码高亮抛弃本地继承而使用cdnjs外链，mavon-editor将自动按需加载对应的语法高亮文件
