### ISSUE TITLE
ul and ol show error

### ISSUE THREAD

**Issue by zqsdongcidaci** [hinesboy/mavonEditor#72]
![image](https://user-images.githubusercontent.com/21104474/30510943-2d058d5a-9a94-11e7-9e3f-cd02111f6a97.png)

**Comment by CHENXCHEN** [comment]
It works normally on my pc.
![image](https://user-images.githubusercontent.com/7724525/30512663-fa71ee9a-9b26-11e7-89bc-8a506e2ede5d.png)

**Comment by LryBackinblack** [comment]
![image](https://user-images.githubusercontent.com/12715042/30522493-54449ada-9c03-11e7-8a84-e0df51d4e9be.png)

Me too……

**Comment by CHENXCHEN** [comment]
what's your version?
version **2.2.6** work normally on my pc.
![image](https://user-images.githubusercontent.com/7724525/30527079-196fb184-9c57-11e7-8428-e9bb0113cca6.png)
maybe rm `node_module ` and `npm install` can solve this issue

**Comment by LryBackinblack** [comment]
先是用  "mavon-editor": "^2.2.4"，
看到你的回答后试着升级到2.2.6，
不过还是没有解决问题。

**Comment by CHENXCHEN** [comment]
引入css了吗？

**Comment by LryBackinblack** [comment]
好了问题解决了……原因是我使用了cssreset 把列表的样式去掉了，谢谢！
