### ISSUE TITLE
[工具栏] 图片按钮是不可点击状态

### ISSUE THREAD

**Issue by 19231224lhr** [hinesboy/mavonEditor#727]
## 💬 Questions and Help
![image](https://user-images.githubusercontent.com/70199004/143159180-70448210-5c09-410c-b22a-e653ca26cfb4.png)

配置如上
显示图片按钮为不可点击状态，但是可以点
![image](https://user-images.githubusercontent.com/70199004/143159286-2bbb83c4-9582-4d9a-816c-0c612bd24530.png)

**Comment by ygj6** [comment]
你提供的代码没有任何设置与禁用工具栏或者图片按钮相关
工具栏只有在不可编辑状态下才能禁用，设置方式：`:editable="false"`
或者可以设置不使用图片按钮，设置`toolbars`属性:` imagelink: false`

---

The code you provided does not have any settings related to disabling the toolbar or the image button.
Toolbars can only be disabled in a non-editable state by setting: `:editable="false"`.
Or you can set it to not use the image button by setting the `toolbars` property: ` imagelink: false`


Api Related:

```js
 /*
    默认工具栏按钮全部开启, 传入自定义对象
    例如: {
         bold: true, // 粗体
         italic: true,// 斜体
         header: true,// 标题
    }
    此时, 仅仅显示此三个功能键
 */
toolbars: {
      bold: true, // 粗体
      italic: true, // 斜体
      header: true, // 标题
      underline: true, // 下划线
      strikethrough: true, // 中划线
      mark: true, // 标记
      superscript: true, // 上角标
      subscript: true, // 下角标
      quote: true, // 引用
      ol: true, // 有序列表
      ul: true, // 无序列表
      link: true, // 链接
      imagelink: true, // 图片链接
      code: true, // code
      table: true, // 表格
      fullscreen: true, // 全屏编辑
      readmodel: true, // 沉浸式阅读
      htmlcode: true, // 展示html源码
      help: true, // 帮助
      /* 1.3.5 */
      undo: true, // 上一步
      redo: true, // 下一步
      trash: true, // 清空
      save: true, // 保存（触发events中的save事件）
      /* 1.4.2 */
      navigation: true, // 导航目录
      /* 2.1.8 */
      alignleft: true, // 左对齐
      aligncenter: true, // 居中
      alignright: true, // 右对齐
      /* 2.2.1 */
      subfield: true, // 单双栏模式
      preview: true, // 预览
  }

```

**Comment by 19231224lhr** [comment]
> 你提供的代码没有任何设置与禁用工具栏或者图片按钮相关 工具栏只有在不可编辑状态下才能禁用，设置方式：`:editable="false"` 或者可以设置不使用图片按钮，设置`toolbars`属性:` imagelink: false`
> 
> The code you provided does not have any settings related to disabling the toolbar or the image button. Toolbars can only be disabled in a non-editable state by setting: `:editable="false"`. Or you can set it to not use the image button by setting the `toolbars` property: ` imagelink: false`
> 
> Api Related:
> 
> ```js
>  /*
>     默认工具栏按钮全部开启, 传入自定义对象
>     例如: {
>          bold: true, // 粗体
>          italic: true,// 斜体
>          header: true,// 标题
>     }
>     此时, 仅仅显示此三个功能键
>  */
> toolbars: {
>       bold: true, // 粗体
>       italic: true, // 斜体
>       header: true, // 标题
>       underline: true, // 下划线
>       strikethrough: true, // 中划线
>       mark: true, // 标记
>       superscript: true, // 上角标
>       subscript: true, // 下角标
>       quote: true, // 引用
>       ol: true, // 有序列表
>       ul: true, // 无序列表
>       link: true, // 链接
>       imagelink: true, // 图片链接
>       code: true, // code
>       table: true, // 表格
>       fullscreen: true, // 全屏编辑
>       readmodel: true, // 沉浸式阅读
>       htmlcode: true, // 展示html源码
>       help: true, // 帮助
>       /* 1.3.5 */
>       undo: true, // 上一步
>       redo: true, // 下一步
>       trash: true, // 清空
>       save: true, // 保存（触发events中的save事件）
>       /* 1.4.2 */
>       navigation: true, // 导航目录
>       /* 2.1.8 */
>       alignleft: true, // 左对齐
>       aligncenter: true, // 居中
>       alignright: true, // 右对齐
>       /* 2.2.1 */
>       subfield: true, // 单双栏模式
>       preview: true, // 预览
>   }
> ```

谢谢您~

**Comment by pieterzeilstraparantion** [comment]
I have the same issue, i have specified no where that the header and image-link options should be disabled but still they are the only options that are unclickable!
