### ISSUE TITLE
ES5有使用的例子么？

### ISSUE THREAD

**Issue by evilbinary** [hinesboy/mavonEditor#73]
mavonEditor+amd写法。

**Comment by hinesboy** [comment]
没有理解你的意思，如果需要使用ES5，在你的项目中支持应该就可以了

**Comment by evilbinary** [comment]
这样的，我是用scheme-lib 写的一个官方网站，环境都是全新的，需要搞个md编辑器来使用。没有那种集成的环境。

**Comment by evilbinary** [comment]
生产工具很简陋的。没有那么多集成环境。就像着用一用。import 啥的写法都不支持。
