### ISSUE TITLE
[Bug] 与Vuetify中的Dialog同时使用时，Editor会自动置于顶层，遮挡dialog

### ISSUE THREAD

**Issue by JackuXL** [hinesboy/mavonEditor#733]
## 🐛 Bug Report

![Snipaste_2021-11-26_20-28-01](https://user-images.githubusercontent.com/58510349/143581073-624e063b-07ef-4697-ae1b-3655ef4ee540.png)

**Comment by wangsongc** [comment]
你可以覆盖`.v-note-wrapper`样式，对于单个mavonEditor组件的使用是可以的
```
.v-note-wrapper{
	z-index: 0 !important
}
```
![image](https://user-images.githubusercontent.com/40830929/144022270-33a72d60-03e2-47bd-a250-c2bd51207a2d.png)

**Comment by JackuXL** [comment]
解决了，谢谢
