### ISSUE TITLE
[Question] Electron环境下无法渲染本地图片

### ISSUE THREAD

**Issue by AioliaRegulus** [hinesboy/mavonEditor#737]
# 依赖版本
* **vue**：2.6.11
* **mavon-editor**：2.10.0
* **electron**：16.0.2
# 问题描述
您好，我在一个 Electron 项目中引入了 Mavon-editor ，但是在上传图片的功能中遇到了一些问题。
在线的图片链接能够被成功解析：
![image](https://user-images.githubusercontent.com/57794772/144613737-90738278-daa1-414c-ba9e-af587a799203.png)
但是使用本地图片上传时，`d_render` 无法正确渲染图片：
![image](https://user-images.githubusercontent.com/57794772/144614058-d74f0cba-5a0d-4c03-af00-b67614074bd9.png)
此处通过 `imgAdd` 回调得到的 `imgfile` 是正确的：
![image](https://user-images.githubusercontent.com/57794772/144613982-01123bf8-e92e-447d-abf2-444aef2a5a8e.png)
直接在 Markdown 文本里写上本地文件的路径和 Base64 也没有效果
也尝试过**直接书写 html 标签**，但是也无法解析：
![image](https://user-images.githubusercontent.com/57794772/144614818-318a289e-6ecf-4e87-a131-c2cce5bb4f62.png)
***
请问有什么解决方案吗？
因为这个项目是自己想练练手，做一个本地的 Markdown 编辑器看看的，因此如果有可能的话，尽量不想使用将本地图片上传至服务器的解决方案。

**Comment by AioliaRegulus** [comment]
# 补充
该项目为 **electron** 的 **BrowserWindow** 配置了 `webSecurity: false`，因此并非由同源机制导致无法访问本地文件。
在 **electron** 的开发者工具中直接修改渲染的 `<img />` 标签的 `src` 可以使图片展示出来：
![image](https://user-images.githubusercontent.com/57794772/144618071-090becf4-dc89-4ca0-99d9-05c0ae2f52b5.png)

**Comment by jiawulin001** [comment]
这个问题是因为XSS防御过滤掉了高危属性，在新版本发布前，你可以通过 `:xssOptions="false"`关闭XSS来解决这个问题。
```vue
<mavon-editor :xssOptions="false"></mavon-editor>
```

---

This issue is due to the XSS filtering out high-risk attributes.
You can use `:xssOptions="false"` to turn off XSS until a new version is released to solve this issue.

**Comment by AioliaRegulus** [comment]
非常感谢各位开发者，我的问题已经解决
***
Thanks very much to all the developers.
My problem has been solved.
