### ISSUE TITLE
关于编辑器Tab与Shift Tab功能

### ISSUE THREAD

**Issue by lianghuiyong** [hinesboy/mavonEditor#746]
1、请问可以默认支持Shift + Tab功能吗，这样在编辑代码区的时候会方便很多，代码一般都是拷贝过来的，前面会带一些比较多的空格
2、Tab快捷键会加两个Tab距离，希望默认两个空格或者四个空格

**Comment by ygj6** [comment]
1、Shift + Tab功能是有的，但目前只能单行使用，多行还没有很好的支持。
2、Tab宽度可以通过` :tabSize="4"`属性来修改

---

1, Shift + Tab function is available, but currently only a single line can be used, multi-line is not yet well supported.
2, Tab width can be modified by ` :tabSize="4"` property .
