### ISSUE TITLE
上传图片报错啦

### ISSUE THREAD

**Issue by lianghuiyong** [hinesboy/mavonEditor#747]
版本：v2.10.2

![image](https://user-images.githubusercontent.com/10268228/146038148-4b86e2ba-9aaf-4c91-92de-1fcef34b1970.png)

**Comment by linxianshen** [comment]
同样的问题, 在2.9.0中出现的, 是混入的markdown不生效嘛? 这个markdownIt没拿到
https://github.com/hinesboy/mavonEditor/blob/b9489a331baf65e856629814f68c6b74f495c863/src/mavon-editor.vue#L455

**Comment by ygj6** [comment]
已经在版本：v2.10.3修复了，可以更新版本验证一下

-------

This issue has been fixed in v2.10.3. You can update the version to verify this issue.

**Comment by lianghuiyong** [comment]
可以了，谢谢啦！！！ @ygj6
