### ISSUE TITLE
[Bug] 一个tab 会显示8个空格，可以默认显示4个空格吗

### ISSUE THREAD

**Issue by lianghuiyong** [hinesboy/mavonEditor#752]
一个tab 会显示8个空格，可以默认显示4个空格吗

**Comment by ygj6** [comment]
增加` :tabSize="4"`属性可以修改。

---
Add ` :tabSize="4"` property can be modified.

ref:https://github.com/hinesboy/mavonEditor/tree/b9489a331baf65e856629814f68c6b74f495c863#props
