### ISSUE TITLE
你好，请问markdown的<summary></summary>不生效？？

### ISSUE THREAD

**Issue by ZC520331** [hinesboy/mavonEditor#754]
![image](https://user-images.githubusercontent.com/18605178/147544708-b580b4c0-212d-45ff-a25e-99588328dbdb.png)
版本2.10.4，全局引用的方式

**Comment by ygj6** [comment]
需要配置一下`xssOptions`属性，两种方式：
1. **推荐**，按需配置
```js
xssOptions:{
    whiteList: {
        summary:[],
        details:['open'],
        pre:[],
        code:[]                    
    }              
}
```
2. **有XSS风险**，关闭XSS防御
`xssOptions: false`


更多配置可以查看：https://jsxss.com/zh/options.html

**Comment by ZC520331** [comment]
get
