### ISSUE TITLE
[Question] 加入了xssOptions，英文符号（例如<>）被转义如何解决

### ISSUE THREAD

**Issue by xs0910** [hinesboy/mavonEditor#755]

**Comment by ygj6** [comment]
具体的例子提供一下,还有使用版本等信息，默认是可以展示的
![image](https://user-images.githubusercontent.com/7699524/147719177-03951410-64fa-4c44-8f83-c15566cf6daf.png)

对于html代码解析也可以自定义解析规则，参考https://jsxss.com/zh/options.html

**Comment by xs0910** [comment]
xss这个我看过了，是可以配置一些html标签进白名单，但是ctrl+Q 这个引用会失效，> 会被转义成 &gt;
![image](https://user-images.githubusercontent.com/45985615/147719468-5625bfe9-f821-4f6b-be18-a109837de2cc.png)
![image](https://user-images.githubusercontent.com/45985615/147719497-dd79514f-e120-4e53-a317-1a8d950b042a.png)

**Comment by ygj6** [comment]
你是哪个版本呢？试试v2.10.4版本

**Comment by xs0910** [comment]
用的是2.9.1，我试试新的版本，thx

**Comment by xs0910** [comment]
2.10.4 版本OK，nice
