### ISSUE TITLE
关于图片名修改和图片删除的问题

### ISSUE THREAD

**Issue by xun1224** [hinesboy/mavonEditor#76]
1.看到文档中methods中有了图片名修改的方法，但是不知道怎么调用呢？ 也就是修改“![图片](./0)”的名字
2.添加图片后 然后删除  保存后其实图片还是会被上传  是不是还要调用删除的methods
请大神指教

**Comment by CHENXCHEN** [comment]
1. 通过调用这个方法:`$vm.$imgUpdateByUrl`，这里的`$vm`指的是`mavon-editor`组件的refs引用实例，`refs`参照[vue的文档](https://vuefe.cn/v2/guide/components.html#子组件索引)
2. 这个问题我没有理解，能解释下吗？`mavon-editor`的删除仅仅是删除本地的图片预览
