### ISSUE TITLE
[Bug]  v 2.10.4 的 release版本中存在绝对路径，导致removeChild失败

### ISSUE THREAD

**Issue by ZhangGaozhen** [hinesboy/mavonEditor#760]
## 🐛 Bug Report

"mavon-editor": "^2.10.4",

编译版本里有 windows 绝对路径？

[Vue warn]: Error in beforeDestroy hook: "NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."
found in
<MavonEditor> at D:\work\songwang\yuangongji\mavonEditor\src\mavon-editor.vue
       <Index> at src/pages/home/activity-report/new-report/index.vue
         <Index> at src/pages/home/index.vue
           <Index> at src/pages/index.vue
             <App> at src/App.vue
               <Root>

![image](https://user-images.githubusercontent.com/39978558/149438842-b0af9fcd-7e1e-4548-bcd9-595854af90a3.png)
![image](https://user-images.githubusercontent.com/39978558/149439085-42299581-634f-4c45-86d2-45c19be11459.png)
![image](https://user-images.githubusercontent.com/39978558/149439196-ef3f6180-467b-4d61-8c04-9384cc0e5206.png)

这个有什么解决方案吗 ？

**Comment by ZhangGaozhen** [comment]
新版本中这个 BUG 解决了吗？

**Comment by wangsongc** [comment]
发布的版本中存在本地路径这个问题是一个历史问题，可能跟打包有关，但正常使用是没有问题的，也没有类似报错反馈，
关于你这个报错的问题，可否提供一个完整点的demo，方便在修复的时候用来验证。
https://codepen.io/wangsongc/pen/abLPaeo
