### ISSUE TITLE
不合规范的文件，还是会被加入 图片下拉列表

### ISSUE THREAD

**Issue by zgj233** [hinesboy/mavonEditor#79]
@CHENXCHEN  尊敬的作者，我发现了一个问题。 `mavon-editor` 在上传图片的时候， 虽然会自动判断文件类型，只有当上传的文件是图片时才会触发`imgAdd`。 但是如果上传的文件不是图片，也会在

> 点击 图片按钮 的 下拉列表 中出现。

要如何阻止无用文件被添加进 这个下拉列表？ 此时没有触发 `imgAdd`，应该阻止无用文件名加入“图片下拉列表”才对。**：)**

**Comment by CHENXCHEN** [comment]
非常抱歉, 最近比较忙 更新的时候漏掉了这个bug
