### ISSUE TITLE
编辑器层级太高了，把另外不可设置层级的组件遮掉了。

### ISSUE THREAD

**Issue by ubbcou** [hinesboy/mavonEditor#81]
如图
![image](https://user-images.githubusercontent.com/25863414/30735404-7f559e2a-9fb1-11e7-9c8a-41f051469a5e.png)

编辑器层级（z-index: 1500;）太高了，把其他不可设置层级的组件遮掉了。

**Comment by vaemc** [comment]
style="z-index:0"

**Comment by vaemc** [comment]
<mavon-editor style="z-index:0"  v-model="article.content" />

**Comment by vaemc** [comment]
` <mavon-editor style="z-index:0"  v-model="article.content" />`
