### ISSUE TITLE
上传图片成功后，我想替换图片的url地址？

### ISSUE THREAD

**Issue by milktea555** [hinesboy/mavonEditor#82]
$imgAdd(pos, $file){
        this.img_file[pos] = $file;
        this.uploadimg(pos, this.img_file[pos]);
      },
      uploadimg(pos, $file){
        let file = new FormData();
        file.append('img', $file)
        $.ajax({
          url: "http://www.jay.com/api/upload/image",
          type: "post",
          data: file,
          contentType: false,
          processData: false,
          dataType: 'json',
          success: function(ret){
            if(ret.status === true){
              mavonEditor.$imgUpdateByUrl(pos, ret.data)
            }
          }
        })
      }

控制台提示我 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_2_mavon_editor__.mavonEditor.$imgUpdateByUrl is not a function

**Comment by CHENXCHEN** [comment]
`$vm.$imgUpdateByUrl`, `$vm` => `mavon-editor`的引用实例，你需要在代码中通过ref获取这个实例，
若`mavon-editor`的`ref`设置为`md`，那么在代码里应该这么调用
```javascript
$imgAdd(pos, $file) {
    var $vm = this;
    var md = $vm.$refs.md;
    // ...
    md.$imgUpdateByUrl(pos, url);
}
```
参考[vuejs的ref文档](https://vuefe.cn/v2/guide/components.html#子组件索引)

**Comment by milktea555** [comment]
不行的。我尝试过按照你的方法
<mavon-editor @imgAdd="$imgAdd" v-model="about.content" ref="md"></mavon-editor>

 var $vm = this;
              var md = $vm.$refs.md;
              md.$imgAddByUrl(pos, ret.data)
组件已经被我实例化。这样报错是 Uncaught TypeError: Cannot read property 'md' of undefined

**Comment by CHENXCHEN** [comment]
贴完整的代码

**Comment by CHENXCHEN** [comment]
以下代码经我测试是可行的，且md是mavon-editor的实例。
```javascript
<template>
    <div>
                    <mavon-editor  ref=md></mavon-editor>
    </div>
</template>
<script type="text/ecmascript-6">
export default {
        mounted() {
            var $vm = this;
            console.log($vm.$refs.md)
        },
}
</script>
```

**Comment by milktea555** [comment]
<template>
  <div>
    
    <mavon-editor @imgAdd="$imgAdd" v-model="about.content" ref="md"></mavon-editor>
    <div style="text-align: center;margin-top: 30px;">
      <Button type="primary" @click="submit">提交</Button>
    </div>
  </div>
</template>
<script type="text/ecmascript-6">
  import {
    mavonEditor
  } from 'mavon-editor'
  import $ from 'jquery/dist/jquery.min'
  import 'mavon-editor/dist/css/index.css';
</script>
闭标签一直是有的

**Comment by milktea555** [comment]
请忽略掉注释符号，这是我的demo

**Comment by milktea555** [comment]
我不知道是不是我的引入方式有误？或者你加我QQ847050412

**Comment by CHENXCHEN** [comment]
@milktea555 目前的问题是你没法获得组件实例的引用，这不是`mavon-editor`的问题。

**Comment by CHENXCHEN** [comment]
你可以在mounted()函数中输出`this`,然后查看`md`是否在`$refs`中，有可能是你代码中某些细节没有处理到，我是可以直接获取到实例的

**Comment by milktea555** [comment]
在mounted()函数里可以获取md的

**Comment by milktea555** [comment]
但是不知道为什么调取不了那个method

**Comment by CHENXCHEN** [comment]
@milktea555 能不能把代码贴出来，包括`template`和`methods`

**Comment by milktea555** [comment]
<script type="text/ecmascript-6">
  import {
    mavonEditor
  } from 'mavon-editor'
  import $ from 'jquery/dist/jquery.min'
  import 'mavon-editor/dist/css/index.css';

  export default {
    components: {
      mavonEditor
    },
    async mounted(){
       this.$vm = this.$refs.md;
      //判断是否传参，存在即是修改
      this.axios.post('/about/get').then(res =>{
        if(res.data.code == 200){
          this.about = res.data.data
          this.about.content = res.data.data.content
        }
        this.$nextTick(() =>{
          this.loadingClose()
        })
      })
    },
    methods: {
      $imgAdd(pos, $file){
        this.img_file[pos] = $file;
        this.uploadimg(pos, this.img_file[pos]);
      },
      uploadimg(pos, $file){
        let file = new FormData();
        file.append('img', $file)
        $.ajax({
          url: "http://www.jay.com/api/upload/image",
          type: "post",
          data: file,
          contentType: false,
          processData: false,
          dataType: 'json',
          success: function(ret){
            if(ret.status === true){
              console.log(this.$vm.$imgAddByUrl)
            }
          }
        })
      },
      submit(){
        if(this.about.initContent == ''){
          this.$Message.error('请填写内容!')
          return
        }
        if(this.about.id){
          this.axios.post('/about/edit', {
            content: this.about.content,
            id: this.about.id
          }).then((res) =>{
            if(res.data.code == 200){
              this.$Message.success('保存成功');
            }
          })
        }else{
          this.axios.post('/about/add', {
            content: this.simplemde.markdown(this.about.initContent)
          }).then((res) =>{
            if(res.data.code == 200){
              this.$Message.success('保存成功');
            }
          })
        }
      },
    },
    data(){
      return {
        about: {
          content: '',
        },
        img_file: [['./0', null]]
      }
    }
  }
</script>
<style>
  .editor-content{
  }
  .intro-head{
    text-align:center;
    margin:10px;
  }
</style>

**Comment by milktea555** [comment]
你把这串代码拿到你编辑器去运行一下

**Comment by CHENXCHEN** [comment]
@milktea555 代码太乱，以后你可以用md语法把代码块框起来，这样就不会乱了

**Comment by CHENXCHEN** [comment]
我明白你的错误在哪里了，你在`axios`中使用了`this.$vm`,函数中的`this`指的是其调用函数的`父函数`(`axios`)，这个用法是错误的，你必须在`axios`之外定义本地变量，如
```javascript
var $vm = this;
var md = $vm.$refs.md;
```
然后，再在`then`的回调函数中使用`md.$imgAddByUrl`

**Comment by CHENXCHEN** [comment]
不要在回调函数中使用`this`，回调函数中的`this`不是`vue`实例，需要在函数顶层定义局部变量，然后再在回调函数中调用

**Comment by milktea555** [comment]
谢谢 我把this注册了一个变量 成功了谢谢你的 提醒 这个错误给忽略了
