### ISSUE TITLE
求助：关于预览区高亮样式被覆盖为highlight.js的default.css

### ISSUE THREAD

**Issue by yasinshaw** [hinesboy/mavonEditor#83]
如题，按照作者的readme中配置后，打包后vendor.js有500多kb。主要是因为这段代码：
```js
for (var i = 0; i < lang.length; i++) {
  _entry[lang[i]] = ['mavon-editor/dist/js/' + lang[i] + '.js']
}
```
想问问大大有什么好的办法能够优化vendor.js的打包体积吗？让我到需要用编辑器的时候再加载这些高亮js。
我试过把这段代码注释掉，vendor.js体积只有3.5kb。但这样编辑器就用不了了。

**Comment by yasinshaw** [comment]
最后自己单独使用了highlight.js，没有使用作者自带的mavonEditor的高亮功能。具体方法：
1. 在index.html中引入highlight.js的必要的cdn文件：
```html
<link href="http://cdn.bootcss.com/highlight.js/8.0/styles/monokai_sublime.min.css" rel="stylesheet">
<script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
```
2. 在需要高亮代码的组件自定义指令：
```js
directives :{
      highlight(el){
        let blocks = el.querySelectorAll('pre code');
        blocks.forEach((block)=>{
          hljs.highlightBlock(block)
        })
      }
    },
```
3. 在需要高亮的地方添加自定义指令:
```html
<div v-html="article.render" v-highlight></div>
```
这样可以实现高亮。
但是有个问题：我在`mavon-editor`添加这个指令，编辑器预览区没有高亮效果。 想请教一下原因以及解决方案。
（也就是说我现在可以在其它页面实现高亮效果了，但是在编辑器预览区域不行）
谢谢！

**Comment by CHENXCHEN** [comment]
@yasinshaw  一楼的问题，highlight.js的语言文件没有集中打包，而是分开打包的，可能是`webpack.output.filename`配置的问题。
二楼的问题，覆盖默认`css`，只需要引入一个新的`css`，`css`的样式层级应该是 `.code-github > xxx`，然后在编辑器引入了`css`之后引入，后者可以覆盖前者

**Comment by yasinshaw** [comment]
感谢回复！
样式可以了。
二楼问题中还有一个小问题：就是在编辑器刚加载数据时或发生了change事件时，预览区代码块是白板（就是说没有经过高亮转换）。但save事件发生后可以成功转换为高亮之后的代码。
监听save事件代码如下：
```js
//编辑器发生save事件
contentSave(value, render){
    this.article.render = render;
},
```
PS：同样的代码放在change事件监听里不生效。
看了下源码，好像并不是编辑器的问题，但还是想请教下为什么会这样的原理。谢谢！

**Comment by CHENXCHEN** [comment]
@yasinshaw `save`事件只有一个操作，就是返回`md`源代码和`html`代码，不是很理解你描述的内容。

**Comment by yasinshaw** [comment]
@CHENXCHEN  嗯，我看了源码，知道`save`事件只是防护`md`源代码和`html`代码，但`change`事件也是一样的。而两个事件居然会造成不一样的结果。可能我描述得不是很清楚，您有时间可以自己操作change和save看看。
[线上demo](https://yasinshaw.com/#/admin/article/detail/2)

> Tips：用户名为adminViewer, 密码为123

[代码](https://github.com/yasinshaw/yasinshaw_frontend/blob/master/src/admin/article/Edit.vue)

另外想请问一下是否有幸参与mavonEditor的开发。
谢谢！

**Comment by CHENXCHEN** [comment]
@yasinshaw 
1. 也许在`mounted`阶段，给`mavonEditor`传递`md`值可解决这个问题, `change`事件和`save`事件触发的条件不同
2. 欢迎欢迎。。项目还有很多不足的地方需要加入讨论

**Comment by CHENXCHEN** [comment]
@yasinshaw 加群`529458036`
