### ISSUE TITLE
[Bug] 这个编辑器的文档写错了

### ISSUE THREAD

**Issue by ZhangYang0204** [hinesboy/mavonEditor#835]
imgDel | String: filename | 图片文件删除回调事件(filename: 写在md中的文件名)

这个函数的参数并不是filename，而是一个数组 ，如下
![image](https://user-images.githubusercontent.com/84385636/218236908-679caa9c-0236-4bec-9519-4766bd503a03.png)
所以在删除的时候不应该用

`
        $imgDel(pos){
            delete this.img_file[pos];
        } 
` 
而应该用

`
        imgDel(pos) {
          delete this.imgFile[pos[0]]; 
        } 
`

**Comment by fxxkjs** [comment]
没用错。imgDel(pos) 参数pos是[filename,FileObj]，是一个数组。

错的是文档，图片处理的文档写的稀碎，还得靠猜
