### ISSUE TITLE
上传图片 mavon-editor 中的$vm.$imgAddByUrl(>=2.1.11) or $vm.$imgUpdateByUrl(>=2.1.5)都无法替换路径 version 2.2.6

### ISSUE THREAD

**Issue by Braveheartforyou** [hinesboy/mavonEditor#84]
mavon-editor npm version v2.2.6
```html
<mavon-editor :subfield = "false" @imgAdd="$imgAdd" ref="editorAdd" @imgDel="$imgDel" :toolbars="editorConfig.toolbars" :value="editorValue" @change="saveEditor"/>
```
```javascript
$imgAdd(pos, $file){
				let formData = new FormData();
				formData.append('access_token', 'a3e93f8c81e7463095d2f021311bc61a');
				formData.append('type', 'app_icon');
				formData.append('file', $file);
				API.UploadImage(formData).then((res) => {
					if (res.status === 200){
						console.log(pos);
						console.log(res.data.data);
						console.log(this.$refs['editorAdd'].$children[0].$imgAddByUrl);
						this.$refs['editorAdd'].$children[0].$imgAddByUrl(pos, res.data.data);// 这个方法没有替换成我的url
						this.img_file[pos] = $file;
						// this.$imgAddByUrl(pos, res.data.data);
						// console.log(this.$refs['editorAdd'].$children[0]);
						// this.fileList.push({url:res.data.data})
						// this.checks = true
					}
					// console.log(res);
				})
				// console.log($file);
			},
```
$imgUpdateByUrl方法会直接undefind

**Comment by CHENXCHEN** [comment]
问题同[#82](https://github.com/hinesboy/mavonEditor/issues/82#issuecomment-331764745)
不要在回调函数中使用`this`，回调函数中的`this`不是`vue`的实例
你应该在函数顶层定义一个局部变量，然后在回调函数中使用这个变量。

**Comment by Braveheartforyou** [comment]
$imgAdd(pos, $file){
				let formData = new FormData();
				formData.append('access_token', 'a3e93f8c81e7463095d2f021311bc61a');
				formData.append('type', 'app_icon');
				formData.append('file', $file);
				this.$refs['editorAdd'].$children[0].$imgAddByUrl(pos, '11111');
				console.log(this.$refs['editorAdd'].$children[0].$imgAddByUrl);
			}
这样也是不行的

**Comment by Braveheartforyou** [comment]
这个问题是我引用错了，但是我即使调用了你的$imgUpdateByUrl 或者 $imgAddByUrl 但是页面上的图片的url没有改变，markdown的html中源码的页面数据也有变

**Comment by Braveheartforyou** [comment]
<font color="red">html源码</font>中的图片还是<font color="red"> base64 编码</font>，markdown中的还是 <font color="red">![图片](./0)</font>

**Comment by Braveheartforyou** [comment]
你这个还必须要再输入或者操作才能触发 修改事件，有没有什么好的点方法解决这个问题

**Comment by Braveheartforyou** [comment]
前端解析的样式，有完全版的吗？就是css

**Comment by CHENXCHEN** [comment]
`markdown`暂未分离出来，暂时你可以通过源码将`md`样式拷出来使用

**Comment by milktea555** [comment]
如何把编辑区的内容我点击提交后生成预览区的内容？

**Comment by CHENXCHEN** [comment]
@milktea555 请新开一个issue

**Comment by CHENXCHEN** [comment]
**Version 2.4.7**
