### ISSUE TITLE
[Question]这个可以更换全局样式吗,默认的看起来不是很好看 

### ISSUE THREAD

**Issue by hanqicheng** [hinesboy/mavonEditor#844]
## 💬 Questions and Help
白色的图1是现在默认的样式，黑色的图2是其他Markdown 的展示,可以很明显的看到现有的样式没有图二美观,有没有办法更换UI

![1](https://user-images.githubusercontent.com/64473636/224247627-6df540b9-b000-48b1-bec4-b1c14d06b7cc.png)
![2](https://user-images.githubusercontent.com/64473636/224247642-7fe2addb-ab98-4cea-8740-be027df2521c.png)

**Comment by ygj6** [comment]
如下几个参数可以针对性的修改UI
```vue
<mavon-editor 
                :codeStyle="codeStyle" 
                toolbarsBackground="white"
                previewBackground="white"
                :externalLink="externalLink">
            </mavon-editor>


externalLink: {
        markdown_css: function() {
            return '/markdown/my-markdown.css';  //指向自己工程的文件
        },
    },
```
参考文档：https://github.com/hinesboy/mavonEditor#props
https://github.com/hinesboy/mavonEditor/blob/master/doc/cn/no-cnd.md


有个codestyle的demo可以参考下： https://github.com/hinesboy/mavonEditor/tree/master/src/dev

![image](https://user-images.githubusercontent.com/7699524/224873894-5e1458d0-9ff8-418e-9e82-d43ab94de8e4.png)
