### ISSUE TITLE
初次使用编辑器，请问编辑区的内容如何生出预览的html?

### ISSUE THREAD

**Issue by milktea555** [hinesboy/mavonEditor#86]
有个办法。我目前是复制的

**Comment by yasinshaw** [comment]
监听save或者change事件，在里面把render的值赋给你想保存的值。

**Comment by CHENXCHEN** [comment]
@milktea555 你指的，生出预览的html? `mavon-editor`自动渲染出`html`可供预览
请详述下问题和期望。

**Comment by milktea555** [comment]
就是希望编辑区的内容自动生成预览的内容

**Comment by CHENXCHEN** [comment]
暂未提供这个功能。

**Comment by hinesboy** [comment]
通过监听change或者save事件，或者通过主动调用mavonEditor.markdownIt.render方法获取,具体参考mavon与markdownIt文档
