### ISSUE TITLE
如何获取页内导航HTML？

### ISSUE THREAD

**Issue by yasinshaw** [hinesboy/mavonEditor#87]
mavonEditor貌似不支持TOC功能。
但我注意到编辑器有个按钮可以获得导航(F8)那个，
我也希望能得到文章的导航转化成的html，请问我该如何做呢？

**Comment by CHENXCHEN** [comment]
1. 暂未支持`TOC`语法，这个放到未来版本添加。
2.  @hinesboy

**Comment by hqzh** [comment]
+1
