### ISSUE TITLE
[Bug] Component emitted event "imgAdd"

### ISSUE THREAD

**Issue by leeobrum** [hinesboy/mavonEditor#874]
## 🐛 Bug Report

"vue": "^3.3.4"
"mavon-editor": "^3.0.1"

**Steps To Reproduce**

![image](https://github.com/hinesboy/mavonEditor/assets/28123085/13ae5454-6bc4-4bab-bb07-ea0fe0eb8c6f)

![image](https://github.com/hinesboy/mavonEditor/assets/28123085/f1547e73-eec9-4109-a36f-2e04880ff9f2)

**Screenshots**

![image](https://github.com/hinesboy/mavonEditor/assets/28123085/efc68c38-b137-4ce5-95d8-4b2df1c96db7)

**Comment by leeobrum** [comment]
Hi, There is solution?

**Comment by xbaimiao** [comment]
I also have this question
