### ISSUE TITLE
有没有直接获取编辑器内容的 api？

### ISSUE THREAD

**Issue by under-clouds** [hinesboy/mavonEditor#9]
有没有直接获取编辑器内容的 api？

**Comment by CHENXCHEN** [comment]
v-model可以获得原始md内容
change事件在value发生改变后会返回md原始内容和解析后的html内容

**Comment by CHENXCHEN** [comment]
还有另外一种方法：通过ref获得mavon-editor组件的事例引用，直接获取md值或html，也可以直接调用组件内的markdown解析器解析md.
