### ISSUE TITLE
怎样调用htmlcode事件获取编辑后转换的html内容？

### ISSUE THREAD

**Issue by xiwadai** [hinesboy/mavonEditor#90]
![image](https://user-images.githubusercontent.com/24467843/30946398-5a207f92-a436-11e7-9c1d-73daa985bdf2.png)

**Comment by CHENXCHEN** [comment]
1. 监听事件[change](https://github.com/hinesboy/mavonEditor#events)
2. 通过ref获得`mavon-editor`的引用实例，并通过实例取值`d_render`

**Comment by xiwadai** [comment]
完美解决
