### ISSUE TITLE
关于添加图片之后 删除未再使用的图片

### ISSUE THREAD

**Issue by ycsxxp** [hinesboy/mavonEditor#91]
在编辑MD内容时候  
例如 添加图片 [a.jpg] [b.jpg] [c.jpg] 之后 
三个图片已经保存了服务器上 并且保存了MD内容

在编辑这个MD内容时候  删除了 [b.jpg] 之后保存MD   那么如何删除服务器上对应的b.jpg文件呢？

目前想到的是 在编辑MD保存的时候   根据正则拿到MD内容里面所有的图片 [a.jpg] [c.jpg]  然后跟之前的信息作比较拿到 [b.jpg] 已经被删除   然后在服务器上删除掉没用的 b.jpg 文件 

不知道这样的思路是否对？   或者还有什么更好的实现方法么？

**Comment by CHENXCHEN** [comment]
你的思路是对的。但`mavon-editor`没有提供这个操作

**Comment by yasinshaw** [comment]
`mavon-editor`默认添加图片是转换成了base64暂存在本地。你可以不必在添加图片的时候就把图片上传到服务器，而是在保存内容阶段再上传到服务器。这样可以减少误操作上传的可能性。
[参考](https://github.com/yasinshaw/yasinshaw_frontend/blob/master/src/admin/article/Edit.vue) 230行
当然如果已经上传到了服务器，想要删除。你的思路是对的。

**Comment by ycsxxp** [comment]
谢谢 CHENXCHEN 和 yasinshaw 的回复。
