### ISSUE TITLE
希望作者能添加一个主动调用然后返回 str 和 render 的功能

### ISSUE THREAD

**Issue by zgj233** [hinesboy/mavonEditor#92]
现在只能够在 `mavonEditor` 里面加入change 和 save 的事件监听来得到 `str` 和 markdown 解析后的`render`。可不可以增加个直接主动调用，然后返回`render` 的接口呢？ 
一般用户需要 `render` 的值的时候，应该都是在向服务器发起提交的时候吧。

**Comment by zgj233** [comment]
对了， github 怎么给问题加上标签呢？ 是只能管理员来加标签吗？

**Comment by CHENXCHEN** [comment]
通过`ref`获得`mavon-editor`引用实例，然后通过实例改变其`md`值`d_value`，实例监听了`d_value`的变化，改变之后会调用解析，解析是异步的，解析成功之后会触发`change`事件
只能由协作开发者才能添加标签

**Comment by hinesboy** [comment]
以开放markdown-it解析器对象，可以通过mavonEditor.markdownIt获取，请参考mavonEditor与markdownit的文档
