### ISSUE TITLE
图片默认的上传是转换为base64格式的，调用方法$vm.$imgUpdateByUrl报错，能不能提供一个demo

### ISSUE THREAD

**Issue by xiwadai** [hinesboy/mavonEditor#93]
![image](https://user-images.githubusercontent.com/24467843/31005771-b3a5af6e-a52c-11e7-810f-241a3053d22c.png)

![image](https://user-images.githubusercontent.com/24467843/31005783-c289d136-a52c-11e7-9dce-359ad808ab3b.png)

希望提供一些demo，不知道怎样调取转换路径的方法

**Comment by CHENXCHEN** [comment]
($imgUpdateByUrl)[https://github.com/hinesboy/mavonEditor#methods)方法需要两个参数，第一个参数是文件名也就是`pos`，第二个参数是需要替换为的`url`

**Comment by yasinshaw** [comment]
需要想通过$refs获取mavon-editor对象，再调用该方法。如：
```js
this.$refs.editor.$imgUpdataByUrl(fileName,url);
```

**Comment by mmd0308** [comment]
这个有没有demo呢？

**Comment by hinesboy** [comment]
@mmd0308 @xiwadai 关于图片上传的文档已经完善，可以先参考下README.md
