### ISSUE TITLE
有关图片上传的一点疑问

### ISSUE THREAD

**Issue by Janyet-Lee** [hinesboy/mavonEditor#95]
作者你好，首先对你无私的贡献表示深深的感谢。我在使用这个组件的时候有个小疑问，图片上传这一块是否支持云服务器的图片上传？比如说我希望把图片上传至七牛或者腾讯云 etc……但看遍了文档，demo展示的基本是base64格式的图片，好像没有找到类似的api或者回调，所以想了解下当前是否已实现了这个功能，如果没实现，后期是否会添加？

**Comment by CHENXCHEN** [comment]
在添加图片的时候[imgAdd](https://github.com/hinesboy/mavonEditor#events)事件会被触发，通过监听`imgAdd`事件可以获取到编辑器内部别名以及一个`File`Object，图片上传可以通过对这个`File`进行操作，参照[这里](https://github.com/hinesboy/mavonEditor#images-upload--preview)
我觉得，图片上传到哪，怎么上传，已经是属于`业务逻辑`了，毕竟众口难调，`mavon-editor`仅提供一个基础的操作，至于怎么上传应该是业务逻辑的事

**Comment by Janyet-Lee** [comment]
ok,这下明白了，还是看文档不够仔细，感谢啦~
