### ISSUE TITLE
如何优雅的调整工具栏按钮的排列？

### ISSUE THREAD

**Issue by vosonwang** [hinesboy/mavonEditor#97]
要是能说明下思路或者给个简短的例子，那就太好了。

**Comment by CHENXCHEN** [comment]
暂未提供该功能

**Comment by vosonwang** [comment]
好的，谢谢。

**Comment by CHENXCHEN** [comment]
可以参考[103](https://github.com/hinesboy/mavonEditor/issues/103)，获取`toolbar_left`的`button`元素并排序
