### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by EveLuty** [hinesboy/mavonEditor#98]
IOS not word, because you use 'use strict' and 'const' in the same time. please check and fixed it . thank you

‘’’
"use strict";const r=n(255),i={autoTe
‘’’
你好，我使用你的组件，在ios端出错，原因是同时使用了use strict模式和const。请修改下，谢谢

非常感谢您的项目

**Comment by yasinshaw** [comment]
请问你node.js的版本是？
参考stackoverflow的 [SyntaxError: Use of const in strict mode](https://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode)，如果nodejs版本低于4.x会报'use strict'和'const'同时使用错误，升级后不会报。

**Comment by EveLuty** [comment]
你好，不是打包时出错，而是在ios中运行时会有错，在其他平台不会有这样错误。同时，我修改你的源码后，一切ok了。这个问题挺严重，会导致ios端整个项目无法显示，麻烦了

**Comment by CHENXCHEN** [comment]
@EveLuty 你是如何修改的？

**Comment by EveLuty** [comment]
dist 文件中，替换const r为var r。就这一处有问题

**Comment by alex374** [comment]
iOS9会有这个问题, 2.3.1依然有const r = n(255)呢

**Comment by CHENXCHEN** [comment]
**v2.4.5**修复了该问题
