### ISSUE TITLE
上传图片功能增强，如何去掉外面的那个讨厌的upload按钮

### ISSUE THREAD

**Issue by wsd1** [hinesboy/mavonEditor#99]
实话说，本地添加图片预览的方式真的很不错，用起来很爽，在编辑完成后，再一起上传，是个不错的注意。

repo中给图片上传演示了示例——在编辑器外面添加了一个按钮，这个好难看。
想来想去，觉得还是要和现有的图片机制整合在一起才好，于是决定做点小改变：
1、将“上传图片”改为 “添加图片”；
2、给图片按钮下拉菜单加上一个额外选择——“上传图片”， 如果有图片被加入，那么就显示这个选择。
如图：

![submit_button_feature](https://user-images.githubusercontent.com/5611206/31354419-fbc325b6-acfb-11e7-9611-ae552dbde09a.jpeg)

这个“上传图片”释放一个 imgSubmit的事件，这样就再也不用外面加按钮 一起上传了。

刚改完，😊，若觉得这个方式可取，repo主人可以看一下这个：

https://github.com/wsd1/mavonEditor/commit/14661111253821d0ccf81181b0975b25194aeb6c

或者，期待主线能提供更好的办法。

**Comment by CHENXCHEN** [comment]
@wsd1 `npm run dev`中的那个`upload`按钮是作为测试`demo`放上去的，一般做法是这样的：在你需要保存该文章的时候再做上传处理和替换处理

**Comment by wsd1** [comment]
明白了  这也是个不错的办法~~
